### ISSUE TITLE
[GoldSrc] exec .cfg doesnst work

### ISSUE THREAD

**Issue by sphinxx87** [advancedfx/advancedfx#106]
executing a cfg where i have all my moviemaking commands doesnt work
so when entering for example exec moviemaking.cfg in hlae there is only:
AfxError: Could not install hook.. and nothing happens..
btw one of the commands i already tested that doents work is mirv_cstrike_deathmsg max 5
the game crashes instantly as there is any kill on screen..

**Comment by sphinxx87** [comment]
ok executing the moviemaking.cfg works fine, the AfxError message refers only to the comands that does not work..
further commands that dont work are:
mirv_cstrike_deathmsg offset 40
mirv_cstrike_smoke block 1
and i noticed a bug that every time when i get killed the killmessages in the right upper corner jump like 2-3 cm down..

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.56.1
