### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx#107]
Why does Valve cause always more problems (what comes to editing) with upcoming updates? cl_drawhud neither cl_draw_only_deathnotices wont help me to cover win-message or "bomb has been planted"-message

**Comment by dtugend** [comment]
You can try to report the problem to them by emailing CSGOTeamFeedback at valvesfotware dot com

Meanwhile the only option I know of is this: https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI
