### ISSUE TITLE
 CS:GO 10/30/2018 update: -afxDetourPanorama not working

### ISSUE THREAD

**Issue by OraCheung** [advancedfx/advancedfx#111]
Hi,
     When I update the csgo client, I found that Hlae can't  work.

**Comment by dtugend** [comment]
I can not reproduce the problem.
1) Make sure your HLAE is fully updated.
2) Not every error pop-up message means nothing works.
3)  Please provide more information.

**Comment by OraCheung** [comment]
I restarted the computer and tried it again. The problem is not solved.
My HLAE is HLAE 2.56.2.
It used to create 'panorama.org.zip' . But I can't to find anymore after csgo update. No error alerm when I use HALE to open csgo.

**Comment by dtugend** [comment]
Thank you for reporting this problem, it has been fixed in latest HLAE 2.56.3:
https://github.com/advancedfx/advancedfx/releases/latest

**Comment by OraCheung** [comment]
You are so nice! HALE works well now. 
This project is great and helps me a lot.
