### ISSUE TITLE
Missing interfacess error in CS:GO console

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#113]
Trying to repeat the steps in [this](https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI) guide as I have done before to get the Panorama UI debugger shown. However, now I'm getting an error I've not seen before.

HLAE version: 2.56.4
CSGO version: 1.36.6.0

Followed all the steps, however entering `mirv_panorama_toggledebugger` into the CSGO console yields:

> Error: Missing interfacess.

If I scroll to the top of the console log, I do see this:

> V8 Version: 5.8.283
> FcConfigAppFontAddDir f:\steamlibrary\steamapps\common\counter-strike global offensive\csgo\panorama\fonts\ took 9.390 ms.
> CUiComponent_OptionsMenu::CUiComponent_OptionsMenu
> Steam config directory: F:\SteamLibrary\SteamApps\common\Counter-Strike Global Offensive\platform\config
> ChangeGameUIState: CSGO_GAME_UI_STATE_INVALID -> CSGO_GAME_UI_STATE_INTROMOVIE
> |
> | AfxHookSource (Nov  2 2018 12:33:39)
> | http://advancedfx.org/
> |
> | VClient: VClient018 (CS:GO)
> | VEngineClient: VEngineClient014 (CS:GO)
> | VEngineCvar: VEngineCvar007 (CS:GO)
> | GameDirectory: F:\SteamLibrary\SteamApps\common\Counter-Strike Global Offensive\csgo
> |

... which would lead me to believe HLAE is indeed hooked into CSGO.

**Comment by xNWP** [comment]
As of some recent CS:GO updates the debugger has been completely removed from the game (as far as we can tell). You can still use modified files with -afxDetourPanorama, but the debugger itself is no longer available.

**Comment by dtugend** [comment]
Small comment / correction:

1) The guide has a video tutorial linked that shows how to do most important stuff by editing the files without panorama.

2) The panorama debugger has not been completely removed, however the code from engine.dll caring about setting up the window, the JS environment the debugger runs and so on has been removed.
It is possible to try to replace that code, however it would take too much time that I'd rather put into other HLAE projects.
