### ISSUE TITLE
new update messes up my panorama hud with -afxDetourPanorama

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#114]
The hud was working fine before the update. After the update, the Medi-kit sign would show up whenever im spectating a player and overlay on the bullet count on the bottom right of the hud. I tried removing a few of the 'class="afxhidden"' line but i still cant find a fix for it.

[screenshot](https://imgur.com/a/b26a)
[video example](https://streamable.com/7vs37)

**Comment by ghost** [comment]
help i have no idea how to add the"Bug" label

**Comment by ghost** [comment]
Oh no. I do not know how to use a version control system.

**Comment by dtugend** [comment]
The alternative is to re-apply the changes like in the tutorial video each time from scratch.

Since it's only a few changes it's possible, but for more complex stuff I'd recommend s.th. like GIT to manage the changes / different versions.

**Comment by ghost** [comment]
I see. I shall look for a tutorial that could teach me how to use GIT. Thank you.

**Comment by dtugend** [comment]
I am closing this issue, because there's not much I can reasonably do to ease things fro you from my end at the moment.
