### ISSUE TITLE
MIRV_streams edit <name> actionFilter clear

### ISSUE THREAD

**Issue by ChetdeJong** [advancedfx/advancedfx#116]
Someone suggested to add feature for removing all filters by single command 
i.e. _MIRV_streams edit <name> actionFilter clear_ 
![image](https://user-images.githubusercontent.com/35334571/49003728-fb0ced80-f17b-11e8-8bee-9ad4d231706f.png)

**Comment by NESTOWL** [comment]
Please add this command!

**Comment by NESTOWL** [comment]
Dominik, thank! Right now I will test and rewrite CFG!
without this team had to make crutches!
![image](https://user-images.githubusercontent.com/45520187/49398368-24ff7a80-f74f-11e8-800b-310dfa506c21.png)

**Comment by NESTOWL** [comment]
Dominik, everything is working! Thanks again! This update is just in time!👍👍👍
(I needed the filters to be cleared when reloading the CFG so that they do not wake up again!
Because of this, there were difficulties with ALIAS scripts!)
