### ISSUE TITLE
Error afxhooksource problem in address

### ISSUE THREAD

**Issue by AnanaSka13** [advancedfx/advancedfx#119]
Hello. I have some problems with AfxHookSource. I would like to record small highlights in CS:GO using HLAE. But when I enter all the necessary paths and information, such an error appears (a screenshot is attached), which results in incorrect work of the program. What to do?
![screenshot_1](https://user-images.githubusercontent.com/45688585/49647306-1c4ec300-fa33-11e8-9797-eea17a928e38.png)
Thanks for your help!

**Comment by dtugend** [comment]
Hi, forgot to reply. Updating to latest HLAE should solve it.

**Comment by AnanaSka13** [comment]
Yeah, the problem has been solved. Thank you :)
