### ISSUE TITLE
AGR + Normal record (with gs dof map etc..) bug

### ISSUE THREAD

**Issue by negativepriority** [advancedfx/advancedfx#121]
I started to record in hlae AGR + Normal record (with gs dof map etc..), but the first time it work, when i delete the folder take000 and i started a new record, Hlae doesn't rec the agr file

**Comment by dtugend** [comment]
Hi.

HLAE first creates the take folder, before it directs any new files into it.

I guess there's some misunderstanding here:

If you have these folders

take0000
take0001
take0002

and delete take0000 and start recording again

then it will record into take0003:

take0001
take0002
take0003 <- your new take

**Comment by dtugend** [comment]
I tried to recreate the issue according to your description, but it worked fine for me, please also read my previous message.

If the problem persists, please provide more information that might be useful (exact steps to reproduce).

Just in case: Don't forget HLAE doesn't remember it's config inside the game longer than one session inside the game, so if you close the game and reopen it, it will forget things.

**Comment by negativepriority** [comment]
ah okok i fixed, thank you dtugend :D
