### ISSUE TITLE
Does it work for Day of Defeat Source?

### ISSUE THREAD

**Issue by fuchusito** [advancedfx/advancedfx#129]
Hello everyone, Im editing a day of defeat source movie and I saw that mirv streams commands only works in csgo. Is there any way to work in Day of Defeat SourcE?

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/wiki/AfxHookSource#loading-day-of-defeat-source

However CS:GO specific commands won't work: https://github.com/advancedfx/advancedfx/wiki/Source%3ACommands

**Comment by dtugend** [comment]
I am closing this for now due to no response in the past days.
