### ISSUE TITLE
HLAE 2.35.2 Doesn't work

### ISSUE THREAD

**Issue by Joklet** [advancedfx/advancedfx#13]
Hey all, after updating the newest release of HLAE (2.35.2) I only get loader failed msg. The game launches but the mirv commands doesn't work. It worked perfectly before the new update. I've ran it in administration etc.

**Comment by xNWP** [comment]
Which game are you trying to use HLAE with? Also - HLAE should never be run in administrator mode, this will cause errors.

**Comment by dtugend** [comment]
What's the exact error message(s)?

Try to unblock injector.exe in its File Properties dialogue first (right click the injector.exe and select "Properties" to open it):
https://www.google.com/search?q=File+properties+Security+unblock+Windows+10&tbm=isch

The injector.exe is in the folder the HLAE.exe is (unless your antivirus deleted it), the x64\injector.exe is for 64 bit injection only, but CS:GO is 32 bit.

Also make sure that nothing is set to be run as admin, this is not required and can cause problems.

**Comment by Joklet** [comment]
here is a ss of the error msg [![Screenshot from Gyazo](https://gyazo.com/2d899a1cc6b15826e0c235a85990fafd/raw)](https://gyazo.com/2d899a1cc6b15826e0c235a85990fafd)

**Comment by Joklet** [comment]
After checking the unlbock it still didn't work. But i deleted the older version of it and re-installed the newest, checked the unblock again and now it works perfectly. Thank you :)

**Comment by dtugend** [comment]
Glad you could solve it.
