### ISSUE TITLE
How calcs on chicken?

### ISSUE THREAD

**Issue by nofear-js** [advancedfx/advancedfx#130]
my settings:
mirv_calcs handle add index Chicken 113 (113 index chicken mirv_listentities i'm checked here)
mirv_calcs vecAng add handleAttachment Chickens Chicken facemask
mirv_calcs vecAng add value ChickenFaceMask 67 0 0 0 0 179.9
mirv_calcs vecAng add offset ofsChicken Chicken ChickenFaceMask 1
mirv_cam source calcVecAng ofsChicken

and it not working, he ties the camera to slot 1 (CT PLAYER). How can I tie him to a chicken?

**Comment by nofear-js** [comment]
I'm not sure that the chicken has handleAttachment 'facemask'

**Comment by dtugend** [comment]
1) You have a typo in there, your handleAttachment is named Chickens, but you only use Chicken without s.
2) Use GCFScape ( http://nemesis.thewavelength.net/?p=26 ) to extract the chicken model and use Crowbar ( https://steamcommunity.com/groups/CrowbarTool ) to decompile it, then look for $attachment variables to see if the model has attachments and what thier name is. If it does not have any attachments (but I think it has for the e.g. for the holiday hats a suitable one), then try handleEye vecAng cal on the Chicken.
3) Be aware that the index is not guaranteed to stay the same after each map load, at least I don't know if it does.

**Comment by dtugend** [comment]
I am closing this for now due to no response in the past days.
