### ISSUE TITLE
Is there a way to hide certain part of HUD?

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#132]
I guess many guys like me want to hide radar only or display "1/30" bullets to reinforce the power of 1Tap and so on...
It seems that valve doesn't give enough options: cl_drawhud and  cl_draw_only_deathnotices.
So is there a way to hide certain part of HUD? Maybe pls give me some info leading the way , or could you create some easy commands to enable us to turn it on/off.
Radar , HP/Armor , Bullets , team scoreboard , info of current player at the mid bottom.
Btw, thanks for developing hlae , you've really done a good job!
![sample2](https://user-images.githubusercontent.com/47248616/52160120-d1c38d00-26e9-11e9-883c-1f0f98bd938d.png)

**Comment by dtugend** [comment]
You can edit PanoramaUI with HLAE, but it's some work and needs to be reapplied after updates (a code versioning system would help with that): https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

**Comment by dtugend** [comment]
I am closing this for now due to no response in the past days.
