### ISSUE TITLE
AFXHook  Error

### ISSUE THREAD

**Issue by streetshakaw** [advancedfx/advancedfx#136]
When trying to load CS:go it gives the error "AfxHook error" code:12. Tried to run as admin, tried to deactivate firewall and to use earlier versions, wich got me the same error every time. It seems a problem with the injector but i couldn't find any solution or a cause.

**Comment by dtugend** [comment]
The problem indicates that it couldn't enter the directory of the DLL you told it to inject, this can have multiple reasons:

1) Are you using Custom Loader? If yes your settings here are wrong probably, maybe consider usinge File -> Launch CS:GO instead.
2) Have you extracted all files and folders of the .ZIP file and are running from there? If not, please do that, it can't be run from the .ZIP file.
3) It could also be an access rights problem, try to extract HLAE into a different folder, e.g. C:\HLAE or on your Desktop\HLAE

**Comment by streetshakaw** [comment]
**Problem solved.**

Apparently the error shows up if the folder are somehow too deep into the system. After moving it to C:/ it worked fine. I was using simple loader.

**Comment by dtugend** [comment]
Thanks for reporting back.
