### ISSUE TITLE
won't boot csgo, (unique problem)

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#139]
i unpacked HLAE in the wrong folder, so i tried to look for an uninstall exe and found none, couldn't remove it in windows ether. so i tried to delete all of the files manually, reinstalled it and now it wont launch with this error message i copied to clipboard. I am running the latest version of HLAE.

```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 123
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 123
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```

Thanks!

**Comment by dtugend** [comment]
Please make sure you have no Anti-Cheat client running, make sure e.g. none of these is running:
- ESEA Client
- FaceIt Client
- ChallengeMe.gg Anti-Cheat

**Comment by dtugend** [comment]
Also make sure you have set the csgo.exe path correctly in the dialogue.
It seems like that is the problem according to the error code.

We recommend using File -> Launch CS:GO instead of Custom Loader.

```
ERROR_INVALID_NAME

    123 (0x7B)

    The filename, directory name, or volume label syntax is incorrect.
```

**Comment by dtugend** [comment]
Closing due to lacking feedback, feel free to comment with more feedback.
