### ISSUE TITLE
HLAE Mouse Error

### ISSUE THREAD

**Issue by Strapzy** [advancedfx/advancedfx#14]
So for the past 3 updates for HLAE Ive been trying to record cinematics for my friends team and whenever I load a demo my mouse pointer wont get off of the screen. I tried everything such as reinstalling everything and nothing works please tell me if you have a solution to this :D thanks

**Comment by dtugend** [comment]
There is no simple solution I know of to that. The few people that reported it in the past either couldn't / didn't want to help with tracking it down further or it was simply a config related problem and would happen without HLAE using the same launch options and config too.
If you have time and are not afraid of it, we can use [TeamViewer](https://www.teamviewer.com/) so I can check what's going on on your PC, just add me in Steam ( http://steamcommunity.com/id/ripieces ) and tell me why you added me / who you are.

The thing is, afaik HLAE should not tamper with your mouse, unless you are using mirv_input camera.
The mouse problems seem to be more likely when having multiple monitors.

**Comment by dtugend** [comment]
Alternatively contact me in the advancedfx Discord (the link is on the top of http://www.advancedfx.org/ ), I am admin there and named dtugend.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
