### ISSUE TITLE
Unhandled exception has occurred

### ISSUE THREAD

**Issue by La1ing** [advancedfx/advancedfx#141]
https://imgur.com/gallery/psV2Ljj

**Comment by esolman** [comment]
the link to the picture
https://imgur.com/gallery/psV2Ljj

**Comment by dtugend** [comment]
Please provide more information about what you did before the error happened.

Also provide more information about your operating system you use with HLAE and which AntiVirus you use.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
