### ISSUE TITLE
Recommend a fast,easy script for deathmsg

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#142]
It comes from a script I saw on hlae website somewhere.I expanded the function.
It based on "xTrace" to block deathmsg beside current suspected player  set display time to 120s and hide assists.
Just press 1 binded key , it works and echoes hints in console.
To turn it off to normal, press again. Also , there's hints
There's 2 versions, 1st one display with red border and the 2rd one with normal border.

------------------------------------------
Red border version:
**bind "," "auto_highlight";
alias "auto_highlight" "auto_highlight_on";
alias "auto_highlight_on" "alias auto_highlight auto_highlight_off;mirv_deathmsg filter add attackerMatch=!xTrace block=1 lastRule=1;mirv_deathmsg localPlayer xTrace;mp_display_kill_assists 0;mirv_deathmsg lifetime 120;echo -->Highlight+Red Border<--;";
alias "auto_highlight_off" "alias auto_highlight auto_highlight_on;mirv_deathmsg filter clear;mirv_deathmsg localPlayer default;mp_display_kill_assists 1;mirv_deathmsg lifetime 15;echo -->Highlight Off<--;";**

------------------------------------------
Normal border version:
**bind "." "localplayer";
alias "localplayer" "localplayer_on";
alias "localplayer_on" "alias localplayer localplayer_off;mirv_deathmsg filter add attackerMatch=!xTrace block=1 lastRule=1;mirv_deathmsg lifetime 120;mp_display_kill_assists 0;echo -->Highlight On<--;"
alias "localplayer_off" "alias localplayer localplayer_on;mirv_deathmsg filter clear;mirv_deathmsg lifetime 15;mp_display_kill_assists 1;echo -->Highlight Off<--;";**

**Comment by dtugend** [comment]
@advancedfx/doc do we want to integrate this in the wiki or close?

**Comment by xNWP** [comment]
I think any useful config stuff that others will benefit from (and especially ones like this which are asked a lot in the discord) would be great to add somewhere on the wiki. It would save us needing to lookup cfg snippets all the time in older messages too.

**Comment by Purple-CSGO** [comment]
Errr Ive made a new one. I will upload it later.   Its originally from hlae wiki.

**Comment by dtugend** [comment]
I will close this then for now. because as you said yourself, the ones already in the Wiki are similar.
