### ISSUE TITLE
HLAE is not recording my streams

### ISSUE THREAD

**Issue by tonsqq** [advancedfx/advancedfx#145]
So these are all of my commands what i put in my console 

//RAW layer
mirv_streams add baseFX raw
mirv_streams edit raw
mirv_streams edit raw drawhud 0
mirv_streams edit raw DrawViewModel invisible
mirv_streams edit raw PlayerModelsAction invisible
mirv_streams edit raw WeaponModelsAction invisible

//HUD layer
mirv_streams add MatteEntity hud
mirv_streams preview hud
mirv_streams edit hud
mirv_streams edit hud drawHud 1
mirv_streams edit hud drawViewModel 0
mirv_streams edit hud playerModelsAction invisible
mirv_streams edit hud WeaponModelsAction invisible

//models layer
mirv_streams add matteEntity models
mirv_streams edit models
mirv_streams edit models drawVievModel 0
mirv_streams edit models playerModelsAction draw
mirv_streams edit models weaponModelsAction invisible

//guns layer
mirv_streams add matteEntity guns
mirv_streams edit guns
mirv_streams edit guns drawViewModel 1
mirv_streams edit guns playerModelsAction invisible
mirv_streams edit guns weaponModelsAction draw

//depth layer
mirv_streams add depthWorld depth
mirv_streams edit depth playerModelsAction drawDepth
mirv_streams edit depth weaponModelsAction drawDepth
mirv_streams edit depth drawViewModel 0
mirv_streams edit depth drawHud 0
mirv_streams edit depth depthValMax 1500
mirv_streams edit depth depthval 200
mirv_streams edit depth depthval 350
mirv_streams edit depth depthval 400

//record settings
mirv_streams record name "D:\Newclips"
mirv_streams record format tga
host_framerate 300; host_timescale 0; mirv_snd_timescale 1; startmovie "D:\Newclips\audio" wav; toggleconsole; mirv_streams record start?
mirv_streams record end; endmovie; host_framerate 0

and it always looks like it starts to record but still doesn't

**Comment by dtugend** [comment]
`mirv_streams record start?` remove that question mark (?), meaning replace it with `mirv_streams record start`

Does that work for you?

**Comment by tonsqq** [comment]
> `mirv_streams record start?` remove that question mark (?), meaning replace it with `mirv_streams record start`
> 
> Does that work for you?

Yes it did work finally thank you i didn't even notice that question mark over there :D
