### ISSUE TITLE
Will hlae give an option to record with compression?

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#146]
Loseless tga sequence really takes huge space of hard drives. But in some cases we don't need that kind of quality , especially when learning to use hlae. Will hlae leave an option to record sth that take less space? Just need some compression that does little damage to image quality.
My hard drive want me to thank first Lol

**Comment by dtugend** [comment]
Thank you for your suggestion, it's already on the todo list:
https://github.com/advancedfx/advancedfx/issues/54

Please understand I don't know myself if and when it will be done.

**Comment by dtugend** [comment]
We already experimented with PNG output earlier, but the time that compression took notably longer than saving the image to disk, while reducing the files not enough.
