### ISSUE TITLE
mirv_streams add matteEntity is black not green

### ISSUE THREAD

**Issue by rygrma15** [advancedfx/advancedfx#151]
After creating matteEntity stream, stream is black and not green. There is no way key the black color out.
So it looks like this:
![image](https://user-images.githubusercontent.com/32158979/55252096-54804880-5252-11e9-92b0-d356e428c66b.png)

**Comment by dtugend** [comment]
1) Make sure you really extracted all files and folders from the download.

2) You might also be affected by this issue (it has a workaround inside): https://github.com/advancedfx/advancedfx/issues/65

**Comment by rygrma15** [comment]
Thanks for answer. That was it, the non-ASCII letters in hlae location caused it.
