### ISSUE TITLE
Hlae launches old CS:GO version

### ISSUE THREAD

**Issue by TmoWrnz** [advancedfx/advancedfx#153]
Hi,
the first problem is the error that I receive when I try to launch csgo.
The second problem is that HLAE launches the cs version of Operation Hydra which is pretty old, so I am not able to watch demos that are newer than operation hydra.
![Unbenannt](https://user-images.githubusercontent.com/49363819/55684834-2be20800-5950-11e9-98ce-06cabb2f5117.PNG)

**Comment by dtugend** [comment]
Right click CS:GO in Steam library > properties > local files tab  >  browse local files button - then make sure you use that full path for csgo.exe in HLAE. You are probably using an old install of cs:go for HLAE at the moment.

**Comment by TmoWrnz** [comment]
I followed your instructions and copy pasted the path into the HLAE.exe now it says: 
System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

**Comment by dtugend** [comment]
Don't forget you have to close all Anit-Cheat Clients: ESEA, FaceIt, Chalengeme.gg and so on.

**Comment by TmoWrnz** [comment]
I have never played on such servers, but just in case how do disable them?

**Comment by TmoWrnz** [comment]
I'm still receiving the error 
![Unbenannt](https://user-images.githubusercontent.com/49363819/55686010-a4e75c80-595c-11e9-8759-1a9fc13b727e.PNG)

**Comment by dtugend** [comment]
What is your csgo.exe path?
Most of the time it should be in `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

**Comment by TmoWrnz** [comment]
C:\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe

**Comment by dtugend** [comment]
When you enter `version` into console what does it say?

and Have you checked `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe` yet?

Edit: also what AfxHookSource version is printed into console after lauchning the game from HLAE when scrolling up?

**Comment by TmoWrnz** [comment]
it works now thanks so far, but the demos are kinda laggy so it doesn't play really smooth it looks like 20 fps or even lower.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos
