### ISSUE TITLE
Application csgo.exe has been blocked from accessing graphics hardware

### ISSUE THREAD

**Issue by davencsgo** [advancedfx/advancedfx#154]
When I start the game with HLAE I get this windows error message. I installed csgo on my F: drive to have more space to create .tga files.

**Comment by dtugend** [comment]
Which Anti Virus software do you use? It's probably related to that.

**Comment by davencsgo** [comment]
> Which Anti Virus software do you use? It's probably related to that.

I'm using only Windows Defender, before I used Avira. But I found a solution without downgrading my windows version. (Because this happened after my windows update the night before.)

For everybody in the future that would have the same problem
1. I blocked windows defender
2. I verified the csgo game files and it had 78 corrupting files (lol)
3. It didn't work still so I reinstalled the graphics driver.
4. I completely uninstalled csgo and installed the game on my C: drive again. (It worked)
5. I moved my game again from C: to F:

**Comment by dtugend** [comment]
Thanks for sharing the solution :-)

You should be able to use Windows Defender with HLAE though most of the time (apart from some very fresh updates). Updating Windows in Windows Update will also update the Defender definitions (but only after reboot).
We recommend to leave it enabled if you don't have another Anti-Virus.
