### ISSUE TITLE
cs go after recording...pc become so slow ! 

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#158]
after i stop recording... my pc starts working too much !!! untill i close cs go 
plz help and thx

**Comment by dtugend** [comment]
how do you stop the recording?

**Comment by iqhl** [comment]
bind f11 "host_framerate 300; host_timescale 0; mirv_snd_timescale 1; mirv_streams record start; startmovie zzz"

bind f12 "mirv_streams record end; startmovie; host_framerate 0"

**Comment by dtugend** [comment]
Please remove ’ statmovie;’ from f12

**Comment by dtugend** [comment]
Please replace startmovie with endmovie in your f12 bind:

`bind f12 "mirv_streams record end; endmovie; host_framerate 0"`

**Comment by dtugend** [comment]
For solving your problem see above.

Another hint, since I am not sure if it's intended:

The binds you use will create zzzXXXXX.tga files in the Counter-Strike Global Offensive/csgo folder.

If that's intended it's fine, otherwise don't forget to remove those and also remove startmovie (as said only if you don't want those there).

**Comment by iqhl** [comment]
how to change location of zzzXXXX.tga files  ?????
i want to put all image in one folder !  like   ' E: fragmovie/csgo/zzzXXXX.tga......  '
and thx

**Comment by dtugend** [comment]
Regarding your last question:

Put this in your cfg folder or mmcfg/cfg folder in a file named mm.cfg (not mm.cfg.txt, use e.g. [Notepad++](https://notepad-plus-plus.org/) to save it porperly):
```
// Mirv_streams config:
// ( https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams )
mirv_streams record name "E:\fragmovie\csgo"
mirv_streams add normal zzz
mirv_streams edit zzz drawHud -1

// Smoother demos:
// ( https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos )
sv_cheats 1
host_timescale 0
mirv_snd_timescale 1
cl_clock_correction 0
mirv_fix playerAnimState 1

// Binds:
bind f11 "host_framerate 300; mirv_streams record start"
bind f12 "mirv_streams record end; host_framerate 0"

echo mm.cfg loaded
```

Then **after** loading the demo enter `exec mm.cfg` into console and you should see `mm.cfg loaded` printed in console.

This config will make it record to the "E:\fragmovie\csgo\takeXXXX\zzz\YYYYY.tga" files and the audio file will be in "E:\fragmovie\csgo\takeXXXX\".

For more info / documentation see the links in the config above.

**Comment by iqhl** [comment]
you helped me alot <3 thank you
