### ISSUE TITLE
How disable AWP's zoom?

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#159]
Hi, I have a question.
Does exist any command to disable AWP's zoom?
I am not talking about "cl_drawhud 0", just disable totally the zoom.
I searched infos about this but can't find anything, I honestly think that is impossible but if it isn't,  this would be cool 👍 

Thank you and regards

**Comment by dtugend** [comment]
Possible:
See [mirv_fov command](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_fov) + `mirv_fov handleZoom 0` + use a [mirv_streams](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams) normal stream with drawHud 0.
