### ISSUE TITLE
mirv_deathmsg block !ID  dont work

### ISSUE THREAD

**Issue by brankoj123** [advancedfx/advancedfx#16]
i tried this command with my ID and it shows me instructions of how i can use command mirv_deathmsg block. I tried other ID`s of another players and it show same instructions like earlier. please help

**Comment by dtugend** [comment]
As the instructions should indicate you need at least two arguments to mirv_deathmsg block, you only gave one. Maybe you will find this manual page useful: https://github.com/ripieces/advancedfx/wiki/Source%3Amirv_deathmsg

**Comment by dtugend** [comment]
I consider this solved.
