### ISSUE TITLE
How remove viewmodel only for myMatte & myDepth?

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#160]
I have another question.
It is possible to hide the viewmodel only for myMatte & myDepth?
If "r_drawviewmodel 0" executed, the viewmodel is removed on all layer, I don't want it 👎 

Thank you one more time 👍 
Regards

**Comment by dtugend** [comment]
```
mirv_streams edit myMatte drawViewModel 0
mirv_streams edit myDepth drawViewModel 0
```

Please close the questions when they are answered.
