### ISSUE TITLE
Clean up MIT license

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#162]
I'd like to clean up the MIT license, since I am unhappy with the corrent mess in there: https://github.com/advancedfx/advancedfx/blob/master/LICENSE

OLD:
```
Copyright (c) 2019 advancedfx.org
Copyright (c) 2007-2018 Dominik Tugend ( https://github.com/ripieces )
Copyright (c) 2018-2018 Juice ( https://github.com/juicejuicejuice )
Copyright (c) 2018-2018 Devostated ( https://github.com/Devostated ) 
Copyright (c) 2018-2018 Anders 'Dec' ( https://github.com/fj0d09r )
Copyright (c) 2016-2017 Ivan Molodetskikh ( https://github.com/YaLTeR )
Copyright (c) 2015-2015 Niklas Koep ( https://github.com/nkoep )
Copyright (c) 2004-2009 Gavin Bramhill ( http://www.madabouthats.org/ )
```

And only have one copyright holder listed (advancedfx.org):

PROPOSED NEW:
```
Copyright (c) 2019 advancedfx.org
```

We will still be mentioned in the credits of course, as always was the case (new online version of credits: https://www.advancedfx.org/credits/ )

I want to ask for the other copy right holder's permission to do that, since it probably also has legal implications.

Of some copyright holders their contribution could be replaced / recoded, however for others their consent would be required (Gavin, Yalter, me) for sure.

Please reply in this issue, whether you are okay with that step or not:
- [x] Dominik Tugend - I consent hereby
- [x] @juicejuicejuice
- [x] @Devostated 
- [x] @fj0d09r
- [x] @YaLTeR
- [x] @nkoep
- [x] Gavin Bramhill

**Comment by YaLTeR** [comment]
Hm, is this really a good idea? It disconnects the credits from the code. This means that the website has to be always kept online, and also this prevents proper history tracking (going back to a particular commit and seeing people who have contributed to the code at this particular point in time). For example, if you'll have to rewrite some part of the code at some point in the future to "remove" one of the contributors, you will do that and remove them from the website, but the older version of the file won't indicate that this contributor should be credited for some part of that particular version of the file.

**Comment by dtugend** [comment]
The team / contributors / credits / licenses are still distributed with each HLAE download in the readme.txt:
https://github.com/advancedfx/advancedfx/blob/master/resources/readme.txt
But I need to automate them being generated from the the credits collection used in the page somehow.

I am not planning on erasing commit history in the repository, if that was what you meant[?]

This is "only" about the MIT License file, since I thought it's a bad idea to add each contributor in the future there, I mean it will get really long to the point that GitHub can't handle the file + I see no other projects doing that with their MIT License?

**Comment by dtugend** [comment]
If you guys have a better idea how to battle the LICENSE mess the proper way, please tell.

Also I just saw Yalter has multiple LICENSES merged into one LICENSE file, is this the way to do it?

**Comment by Dechno1337** [comment]
I, **fj0d09r** (a.k.a **Dec**) humbly accept your request.

_I wish you good fortune in the license wars to come._

**Comment by YaLTeR** [comment]
Is this really necessary? Are there so many contributors being added that LICENSE is getting out of hand?

**Comment by dtugend** [comment]
It's not really necessary at the moment and not getting out of hand yet, but I wanted to solve that problem, before people involved are dead / unreachable.

An other option is too freeze the LICENSE file, apart from the first advancedfx.org part and not accept changes to it anymore. But I like things clean and tidy sometimes.

The list in the credits will probably grow, since we are planning a separate doc repo ( https://github.com/advancedfx/doc ) for the manual.

**Comment by dtugend** [comment]
An other option is to continue as is and add people to license files on a per project (repo) basis and give a **** about if GitHub will be able to parse the files or not, hm.

**Comment by Devostated** [comment]
pro change -.-

**Comment by dtugend** [comment]
Contacted Gavin by email as usual, he said he doesn't mind.

**Comment by nkoep** [comment]
No objections from my side

**Comment by etojuice** [comment]
I don't mind

**Comment by YaLTeR** [comment]
We discussed this issue in PM; I give my consent for the change.

**Comment by dtugend** [comment]
The major concern of YaLTeR was that people would be removed from credits and then won't be credited anymore.

To clarify, we never removed people from the credits and I do not plan at all to change that.
Example neomic:
https://www.advancedfx.org/credits/#contrib_neomic 
His wxwidge GUI was never released / used in the final "product", but he is still credited.

The second major concern was that the credits might be only available online.

To address this we should continue to package the credits with each HLAE release (as has been done manually until now in readme.txt, maybe we can change that to be automated). We should also consider to package the credits with other advancedfx projects (e.g. afx-unity-interop), especially if we can do it efficiently / automatically somehow.

**Comment by dtugend** [comment]
Thank you all guys for supporting the license clean up :-)
