### ISSUE TITLE
crash when i type mirv_input camera

### ISSUE THREAD

**Issue by vecnhan** [advancedfx/advancedfx#164]
when i type mirv_input camera in CSS it crash my game and runtime error run unsual something ... show up
any one know how to fix this

**Comment by dtugend** [comment]
Which CSS version are you using?

Can you try if the previous release crashes too, please?:
https://github.com/advancedfx/advancedfx/releases/tag/v2.64.1

**Comment by dtugend** [comment]
Hi, this is indeed a bug I need to fix, thanks for reporting, it.

This version might work for CSS meanwhile: https://github.com/advancedfx/advancedfx/releases/tag/v2.63.4

**Comment by vecnhan** [comment]
no way it's actually work holy s*** thanks so much you made my day
