### ISSUE TITLE
mirv_listentities Causes Crash

### ISSUE THREAD

**Issue by xNWP** [advancedfx/advancedfx#166]
**OS**: Windows 10 64-Bit
**HLAE Version:** [v2.64.4.1](https://github.com/advancedfx/advancedfx/releases/tag/v2.64.4.1) (Mislabeled as v.2.64.4.4)

**Steps to produce the bug:** Run the mirv_listentities command (with any parameters) in a CS:GO demo.

**Expected Result:** A list of all entities.

**Actual Result:** Immediate game lock-up and crash.

**Comment by YiyaMaster** [comment]
me too

**Comment by dubcorn** [comment]
is anyone going to fix this shit?

**Comment by xNWP** [comment]
Abuse towards team members will absolutely not be tolerated. I suggest you learn some manners or don't bother commenting.

**Comment by dtugend** [comment]
Thank you for reporting, please update your HLAE to latest: https://github.com/advancedfx/advancedfx/releases/latest
