### ISSUE TITLE
csgo crashes after executing pov cfg (new update)

### ISSUE THREAD

**Issue by davencsgo** [advancedfx/advancedfx#167]
After the new update which was released last night I can't execute my pov config anymore. The task closes instantly. The cfg was working before update. My hlae is up2date.

Following commands I'm using and after the execute csgo.exe shuts down:
"
mirv_calcs handle add key key 5 ;
mirv_calcs handle add activeWeapon aw key 1 ;
mirv_calcs vecAng add handleAttachment awm aw muzzle_flash ;
mirv_calcs vecAng add handleAttachment awh aw weapon_hand_R ;
mirv_calcs vecAng add or awmh awm awh ;
mirv_calcs vecAng add value weaponOfs 10 0 0 0 0 179.9 ;
mirv_calcs vecAng add offset awmOfs awmh weaponOfs 1 ;
mirv_cam source calcVecAng awmOfs ;
mirv_cam offset none ;
spec_mode 5"

**Comment by dtugend** [comment]
Thank you for reporting, please update your HLAE to latest: https://github.com/advancedfx/advancedfx/releases/latest
