### ISSUE TITLE
stream removal while previewing = crash

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#171]
removing a stream while previewing would cause hlae+csgo to crash. I suggest making the preview move to another one from the array (or just disabling the preview automatically) if currently in preview and a command for removal is executed.
not that important ,but might save someone some time

**Comment by dtugend** [comment]
note to myself: probably only happens when attach / detach commands are used (the old problem).

**Comment by dtugend** [comment]
Should be fixed in HLAE 2.65.1 (2019-05-18T11:20Z) or newer, thanks for reporting it.
