### ISSUE TITLE
launch CSGO flash

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#172]
- [x] I have searched exiting **open** issues to verify this is a new bug report.
When I update my windows 10 to ver.1809,use hlae launch CS GO it show nothing for me.no log no error report,what is going on?

**Comment by dtugend** [comment]
I am on Windows 10 ver 1809 as well, that's not the problem.

If you mean the dialogue is not appearing (so you can not even click the "Launch" button / select csgo.exe etc:
Is your Windows version legit? Sounds as if you are missing some system component or DLL?

You can find more info in the EventViewer in Application Logs: https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/
Please check there for HLAE.exe and provide us with the info from there.

**Comment by ghost** [comment]
now have an error report
AfxHook error：Unknown error code
code:1007
NO description available

I think not that mean,I mean"flash" is when I click HLAE Launch CS GO button,the game just quickly appear and then quickly disappear and without any error report before. ,but launch on steam or Faceit battle platform which is normal.I have used HLAE before,just recently change the Graphics card and upgrade the windows.

**Comment by dtugend** [comment]
```
ERROR_FULLSCREEN_MODE

    1007 (0x3EF)

    The requested operation cannot be performed in full-screen mode.
```

Which Graphic driver and version are you using?
What is your screen resolution and what resolution did you set in HLAE and did you enable fullscreen?

Also make sure that FaceIT etc are off before launching CS:GO from HLAE.

**Comment by dtugend** [comment]
If you are on a AMD graphic card like #173 then please try this:

Can you please try to use the latest AMD driver for your graphic card, maybe it's a driver bug:
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-19-5-1

Also if you have enabled some sort of overlay in the driver, then turn it off and see if it still crashes.

**Comment by dtugend** [comment]
Might also be a good idea to use this to uninstall the old one before that first: https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

**Comment by dtugend** [comment]
Can you send us the newest .mdmp file from the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive` folder (or similar) or if there is none the newest .dmp file from `C:\Program Files (x86)\Steam\dumps`folder (or similar), please?

You can compress it with https://www.7-zip.org/ and then upload it to https://send.firefox.com/ and 
then  send it to contact@advancedfx.org. Do not share the link publicly, since the crash dump files can contain sensitive info.

**Comment by dtugend** [comment]
Hi.

In this similar issue it turns out the user has an addons folder in the csgo sub-folder, please try if the suggested solution fixes your problem too:
https://github.com/advancedfx/advancedfx/issues/173#issuecomment-493724841

**Comment by dtugend** [comment]
Closing this due to no reply, the linked issue should have solved your issue too.
