### ISSUE TITLE
Wrong code 1007

### ISSUE THREAD

**Issue by Crolfhym** [advancedfx/advancedfx#173]
- [x] I have searched exiting **open** issues to verify this is a new bug report.
My version is up to date,but it is not the problem.
I can open CSGO via all way but HLAE,which means I could not launch it via HLAE.
Once I launch it via HLAE it will show me fail code 1007
Description:No description available
Solution:No solution available
I hope someone can give me a hand.

**Comment by dtugend** [comment]
Please provide a screenshot of the message or use the "Copy to Clipboard for Support" button and paste it here.

**Comment by Crolfhym** [comment]
------------------ 原始邮件 ------------------
发件人: "Dominik Tugend"<notifications@github.com>
发送时间: 2019年5月18日(星期六) 凌晨1:39
收件人: "advancedfx/advancedfx"<advancedfx@noreply.github.com>;
抄送: "Crolfhym"<947814132@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [advancedfx/advancedfx] Wrong code 1007 (#173)



Please provide a screenshot of the message or use the "Copy to Clipboard for Support" button and paste it here.
 
&mdash;

**Comment by dtugend** [comment]
In case you replied with an Image by email: That didn't work :(

**Comment by dtugend** [comment]
```
ERROR_FULLSCREEN_MODE

    1007 (0x3EF)

    The requested operation cannot be performed in full-screen mode.
```

Which Graphic driver and version are you using?
What is your screen resolution and what resolution did you set in HLAE and did you enable fullscreen?

Also make sure that FaceIT etc are off before launching CS:GO from HLAE.

**Comment by Crolfhym** [comment]
I am using AMD RX580 8G.
version 19.4.3
Length 1920 and width 1080 Fullscreen
No faceit running when I use hlae

**Comment by dtugend** [comment]
Can you please try to use the latest AMD driver for your graphic card, maybe it's a driver bug:
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-19-5-1

Also if you have enabled some sort of overlay in the driver, then turn it off and see if it still crashes.

**Comment by dtugend** [comment]
Might also be a good idea to use this to uninstall the old one before that first: https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

**Comment by Crolfhym** [comment]
now there is a new problem
I update HLAE and try the way you said.now it crashes without any mention,neither code 1007

**Comment by dtugend** [comment]
Can you send us the newest .mdmp file from the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive` folder (or similar) or if there is none the newest .dmp file from `C:\Program Files (x86)\Steam\dumps`folder (or similar), please?

You can compress it with https://www.7-zip.org/ and then upload it to https://send.firefox.com/ and 
then  send it to contact@advancedfx.org. Do not share the link publicly, since the crash dump files can contain sensitive info.

**Comment by dtugend** [comment]
Hi, I got your email:

It seems you have sourcemod/metamod installed.
Please temporarily delete / rename the addons folder (`f:\Steam\steamapps\common\counter-strike global offensive\csgo\addons`) to see if that fixes the problem.

If it fixes the problem, you need to update your metamod / sourcemod or avoid to use it together with HLAE.

It is possible for HLAE and sourcemod / metamod to clash, especially after CS:GO updates.
