### ISSUE TITLE
IS FFMPEG available now

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#177]
Feel really excited when seeing that twit. But there's not much information about ffmpeg and how to use it. Are you just fixing some bugs?Could you offer more details?
Really wanna save a lot of space when recording with hlae.

**Comment by dtugend** [comment]
Fore more instructions please read the changelog (it also has an example):
https://github.com/advancedfx/advancedfx/releases/tag/v2.70.1

Yes you can use FFMPEG with HLAE now, but it needs to be installed into the HLAE folder first as described in the readme.advancedfx.txt mentioned in the changelog.

Using the `mirv_streams settings` command you can also add own FFMPEG settings, to see examples look at the existing afxFFMPEG* default settings accessible by that command (print / edit).

Currently it's only for encoding image streams to video, the audio will still be .wav and also combining audio & video into one file is not supported yet.

If you have further questions, please let us know.

**Comment by Purple-CSGO** [comment]
![image](https://user-images.githubusercontent.com/47248616/58317957-6f81ca00-7e49-11e9-9fa2-ff6dd01d38af.png)
Couldn't understand the instruction on installing ffmpeg. Any detailed explanation？

**Comment by dtugend** [comment]
1.) http://ffmpeg.org/ -> http://ffmpeg.org/download.html -> http://ffmpeg.org/download.html#build-windows -> https://ffmpeg.zeranoe.com/builds/ -> Make sure Windows 64 bit is selected and click the blue download button there (be aware to not click one in an ad on that page, I mean the real one)

2.) Download and Install latest HLAE as you normally would, then extract the contents of the "ffmpeg- [....]" folder into the "ffmpeg" folder in the HLAE install: ![ffmpeg in HLAE](https://user-images.githubusercontent.com/3610128/58319150-988a6680-7e19-11e9-8912-60ffb8923c49.jpg)

**Comment by Purple-CSGO** [comment]
Ok, I've recorded some clips.I tested with stream called raw.When recording with
```
mirv_streams edit raw settings afxFfmpeg;
//or
mirv_streams edit depth settings afxFfmpegLosslessBest;
```
Sth went wrong. Looks like this↓. I'm using Win10 1903.
![image](https://user-images.githubusercontent.com/47248616/58321187-14070a80-7e50-11e9-8892-26df2a762d3a.png)
-- --
When recording with
```
mirv_streams edit raw settings afxFfmpegYuv420p;
```
It really saves a lot of space.
##### A 30s 300fps clip takes about 130MB
afxFfmpegYuv420p is awesome. but in order to edit and render videos with nice quality, it's not weird to seek for other options to record with little bit larger bitrate but far from original .tga sequence or fraps.
##### Video quality as well as bitrate goes up little bit to a acceptable level.
A 1min 300fps clip taking 500MB~1GB or up to 2GB  sounds reasonable, maybe.
-- --
Anyway, really thx your great work!

**Comment by dtugend** [comment]
Which Video editor / player did you use for afxFfmpeg / afxFfmpegLosslesBest?
For those several video editors / players / browsers are not capable of playing them back.

http://www.videolan.org/ Can should be able to though, if VLC is not able either, then something is wrong on my end / with HLAE.

As said you can make your own encoding settings, use `mirv_streams settings` to do that (and have a look with print / edit at the existing afxFfmpeg* settings, so you see how it is used). For possible options have a look at the FFMPEG documentation ( http://ffmpeg.org/ffmpeg-codecs.html#Video-Encoders ) and FFMPEG tutorials on the internet.

afxFfmpeg is libx264 in yuv444p format and afxFfmpegLosslessBest is libx264rgb, I myself can't use those with Sony Vegas 14 sadly :(

If you find good lossless settings that work well for you without problems, don't hesitate to share them with us / other HLAE users.

Edit: Also might be helpful to know the settings of the "raw" stream you mentioned / how it is created, it's not a default HLAE stream.

**Comment by Purple-CSGO** [comment]
I'm using Premiere Pro and Potplayer.
I've tried and found `afxFfmpeg` works well with Pr though Potplayer goes wrong when playback.
For `afxFfmpegLosslessBest` ... GG.
-- --
raw stream is just a basic steam i'm using. It just records what is displayed on the screen.
-- --
Talking about FFMPEG, I feel headache. My English is poor. Often, I use a tool built upon ffmpeg that displays Chinese and is good to use, so I don't know much about FFMPEG.
Also, i don't know how to change or deal with the preset.
Maybe, knowing how to turn the bitrate up a little bit is quite enough.

**Comment by dtugend** [comment]
I found this guide helpful myself: https://trac.ffmpeg.org/wiki/Encode/H.264
The lower the `-crf` value, the higher the bitrate.

Which tool built upon FFMPEG do you use? Some tools can reveal the command line for FFMPEG used, but that might be not the case.

Edit: If possible you should preffer afxFfmpeg over afxFfmpeg420p, because of better color quantization (less lossy).

**Comment by Purple-CSGO** [comment]
To be honest, I'm really headache with ffmpeg.
I know something about encoding , crf, 2pass ,etc.
Could you make some change with preset?
Example : `afxFfmpeg`
Using `afxFfmpegCrf20` to use the preset but set Crf to 20
I don't know what is the default value, but leaving some options to let us change value o' Crf can surely make it easier.
That's just a suggestion. Maybe there are some other ways.

Btw, I've post a blog explaining how to use it. It's written in Chinese, but many browser like Chrome can translate. Maybe you can take a look.

https://purple-csgo.github.io/hlae/hlaeffmpeg.html

**Comment by dtugend** [comment]
I see there's still [some bugs in there](https://github.com/advancedfx/advancedfx/issues/178), but

Here is how to view existing settings:
```
] mirv_streams settings
mirv_streams settings print - List currently registerred settings
mirv_streams settings edit <name> - Remove setting.
mirv_streams settings remove <name> - Remove setting.
mirv_streams settings add [...] - Add a setting.

] mirv_streams settings edit afxFfmpeg
afxFfmpeg (type ffmpeg) recording setting options:
mirv_streams settings edit afxFfmpeg options [...] - FFMPEG options.

] mirv_streams settings edit afxFfmpeg options
afxFfmpeg (type ffmpeg) recording setting options:
mirv_streams settings edit afxFfmpeg options option1 ... optionN - Set output options, use {QUOTE} for ", {AFX_STREAM_PATH} for the folder path of the stream, \{ for {, \} for }.
Current value: -c:v libx264 -preset slow -crf 22 {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}
```

And here is how to add yours:
```
] mirv_streams settings add ffmpeg myFfmpegCrf20 "-c:v libx264 -preset slow -crf 20 {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}"
```

Then you can set it on a stream:
```
] mirv_streams add normal norm

] mirv_streams edit norm settings myFfmpegCrf20
--- Editing stream "norm" ----
```

Don't forget to set host_framerate before recording.

Please do not start presets with "afx", those are meant to be reserved, I forgot to check for that, to disallow those being created.

Edit:

A note: -crf 0 is almost lossless, but not quite, because it libx264 is YUV color space and converting from RGB gives some loss, that's why the afxFfmpegLosslessBest preset uses libx264rgb.

**Comment by dtugend** [comment]
I read your Chinese article you linked.

I could not find any mistakes.

**Hint:** You can change the `-preset slow`to e.g. `-preset medium` or even `-preset fast`, the latter will mean larger file size but record faster at same quality. (As documented here: https://trac.ffmpeg.org/wiki/Encode/H.264)

Do you have further questions?

**Comment by Purple-CSGO** [comment]
nope. Pretty clear how to deal with it.

**Comment by dtugend** [comment]
Okay, closing the issue then :-)
