### ISSUE TITLE
Sharing my ffmpeg.cfg

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#179]
I've tested with several x264 settings, recording time and output videos' size.
Thus, i made this [`ffmpeg.cfg`](https://github.com/Purple-CSGO/Cfg-Preset-By-Purp1e/blob/v1.1/ffmpeg.cfg) written in Chinese(Maybe Someone can translate( ͡° ͜ʖ ͡°)).
These 4 commands appears in `ffmpeg.cfg`
- afxFfmpeg
- SuperfastCrf20
- SuperfastCrf18
- UltrafastCrf16
- --
All you have to do is change all the names o' streams where "alias" appears according to you.
Place it in cfg folder and: 
```
exec ffmpeg
```
Use the command printed in console, then it'll print "Setting changed"
- --
It only changes record settings. Do other things as usual.

Link: https://purple-csgo.github.io/hlae/hlaeffmpeg.html

**Comment by dtugend** [comment]
@advancedfx/doc do we want to integrate this in the wiki or close?

**Comment by xNWP** [comment]
Looks useful! Although if someone could translate / if @Purple-CSGO could rewrite the comments + console messages in English (as that is the dominant language of our user group) that would make it even better :-)

**Comment by Purple-CSGO** [comment]
I have an idea: why not create a command that changes all the streams record setting?Since whoever wants to record with hlae would use ffmpeg or tga sequence on all of the streams.Who want to record world stream with lossy mp4 but matte with lossless sequence?
Therefore, it's gonna be easier and I'll change my cfg which could be a lot easier to understand by others, not having to change stream names or sth.

**Comment by xNWP** [comment]
+1 to that idea, but definitely keep a way to individually address stream settings since many users will want something like OpenEXR for their depth streams. I think this could be a good implementation:

```
mirv_streams settings default SomeSettingHere;
mirv_streams edit MyStream settings <someOtherSetting>;

// All other streams are set to the default value otherwise
```

**Comment by dtugend** [comment]
@xNWP please open a separate issue for that, it's not directly related to this issue asking to merge the config with the documentation.

**Comment by Purple-CSGO** [comment]
I'll do that

**Comment by dtugend** [comment]
Please reopen when this closes, I accidentally referenced the wrong issue number.

**Comment by dtugend** [comment]
Closing in favour of #189
