### ISSUE TITLE
"mirv_deathmsg block" does not block assists anymore

### ISSUE THREAD

**Issue by twinplay** [advancedfx/advancedfx#18]
As stated in the title, after entering "mirv_deathmsg_block !uid *" the assist-giver is still beeing shown in the killfeed.

My version:
> Protocol version 13604 [577/577]
> Exe version 1.36.0.4 (csgo)
> Exe build: 13:38:20 Sep  6 2017 (6878) (730)

**Comment by xNWP** [comment]
Can confirm that I am also seeing this behaviour ! :(

**Comment by dtugend** [comment]
There is a console variable / command by Valve:
```
mp_display_kill_assists 0
```

In the unlikely case this does not solve your issue, please provide the demo file.
