### ISSUE TITLE
how can i remove hud like this 

### ISSUE THREAD

**Issue by qwdqwdqw2323** [advancedfx/advancedfx#182]
- [x] I have searched exiting **open and closed** issues to verify this is a new question.

like this vid : https://www.youtube.com/watch?v=FkJ6XYQp26g&t=3s

not a cl_drawhud or draw_only_deathnotices

i want record with hud money/player count/armors

**Comment by dtugend** [comment]
You can do this by editing Panorama UI, but it's a lot of work and not easy, read more here:
https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

**Comment by dtugend** [comment]
Closing because the question has been answered and there's no further replies in the past days.

**Comment by shamint** [comment]
In case you were curious, the video you linked uses POV demos, not GOTV demos. You can record POV demos using the console command record (demonname). A recent patch made it so you may only record demos in warmup or freeze time so keep that in mind. POV demos will give you the effect you are looking for without going through the work of editing panorama ui. If you want to disable the radar as well the command is cl_drawhud_force_radar -1.
