### ISSUE TITLE
Request for adding a command to change record settings of all streams

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#185]
> why not create a command that changes all the streams record setting?
Since whoever wants to record with hlae would use ffmpeg or tga sequence on all of the streams.Who want to record world stream with lossy mp4 but matte with lossless sequence?

So it's kind of good to add a command that change all streams' record settings. Maybe it's like
```
mirv_streams edit all afxFfmpeg;
//or like
mirv_streams edit settings afxFfmpeg;
```
It doesn't conflict wtih original commands.
After adding this command,  placing it and user presets into .cfg,  users don't have to care much about switching record settings. Just choose one of his favorite settings. When he/she wants to change, just using one command is enough.

**Comment by dtugend** [comment]
mirv_streams edit is an command used to edit existing streams and the stream names are not limited too much atm, so I can not do those, I#'ll morel ikely do s.th. similar to [this](https://github.com/advancedfx/advancedfx/issues/179#issuecomment-496278653).

**Comment by Purple-CSGO** [comment]
Okay. Name doesn't matter too much. Just don't conflict with existing commands and acheive the funtion. 
Really looking forward to next update QwQ

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/commit/a4c23efb4c46314508f28a9e1ecc9909ebe5d0fe
