### ISSUE TITLE
how to record audio with startmovie command 

### ISSUE THREAD

**Issue by shamint** [advancedfx/advancedfx#186]
the audio recorded from startmovie is always super laggy and bad 
the commands i use are 
host_framerate 120
host_timescale 0
mirv_snd_timescale 1

**Comment by dtugend** [comment]
You need to use mirv_streams to record only audio (meaning don't add any streams (by default there are none)) at the same time as you use startmovie / endmovie:

Example
```
bind f8 "startmovie tga mymovie; mirv_streams record start"
bind f9 "endmovie; mirv_streams record end"
```

This will also fix the startmovie audio.
However you will need to **occasionally delete the "untitled_rec" folder in the csgo.exe,** where mirv_streams stores an own copy of the audio.

----

You might also find this tutorial helpful additionally:
[Source:Smoother Demos](https://github.com/advancedfx/advancedfx/wiki/Source%3ASmoother-Demos)

**Comment by dtugend** [comment]
I hope it's solved.

**Comment by shamint** [comment]
Hi sorry to comment back so late.. i tried using those commands however the frames stop recording pretty much instantly and I get an error in the console that tells me I need to specify whether it’s “raw avi or both” I’m also using custom sound files, which could be interfering possibly.

**Comment by dtugend** [comment]
Sorry I mixed up part of the command it should probably be

startmovie mymovie tga

**Comment by shamint** [comment]
alright ill try that command when i get the chance thanks for the quick response

**Comment by dtugend** [comment]
so to clarify, the full thing should be

```
bind f8 "startmovie mymovie tga; mirv_streams record start"
bind f9 "endmovie; mirv_streams record end"
```

**Comment by dtugend** [comment]
I hope this is solved now, if not please comment.
