### ISSUE TITLE
Easy-to-use ffmpeg.cfg with several presets

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#189]
> Due to an update, this page has been changed on Aug.6th, 2019

After HLAE 2.71.0 update, I've changed my [ffmpeg.cfg](https://github.com/Purple-CSGO/Cfg-Preset-By-Purp1e/blob/v1.2/ffmpeg.cfg)([English Version](https://github.com/Purple-CSGO/Cfg-Preset-By-Purp1e/blob/v1.2/en/ffmpeg.cfg)) and tested with some presets. It is now quite easy to use. I also update my [blog](https://purp1e.site/hlae/hlaeffmpeg.html)([English Version](https://purp1e.site/hlae/hlaeffmpeg-en.html)). Forgive my poor English.

## Brief Description

Step 1: Install ffmpeg to `hlae/ffmpeg/`. (With installer, it is automatically done)
Step 2: Download ffmpeg.cfg to you cfg folder.
Step 3: Open and check ffmpeg.cfg. Change default setting appears in Line 30 if you want to.
Step 4: Start csgo with hlae, exec your cfg and ffmpeg.cfg.

It only changes record settings. Do other things as usual. And it's done if you're satisfied with default preset. If not, use commands appear in console to change settings.
![1565080764180](https://user-images.githubusercontent.com/47248616/62528250-1da8e780-b86f-11e9-8edb-4254cec9c40d.png)

For instance, default preset is `p3`. I want to record with smaller size. So type `p1` in console, then it is done.

## Which preset to use

- After testing all the presets, I highly **recommend** using **`p2`**, **`p3`** and **`p4`**.
- I **don't recommend** **`afxFfmpeg`** cuz it's slow when recording.
- I can hardly tell the difference between **`p3`**, **`p4`**, **`p5`** and lossless tga files.
- If you are making an epic fragmovie, **just use `p5`**. HDDs and SSDs will clap for you cuz it takes only 1/4 space compared to lossless .tga files with ≈0 loss.
- `afxClassic` switches settings back to output tga files.

**Comment by Purple-CSGO** [comment]
If your edit software can't recongize clips or crash when dragging the clips. Change x264 settings and add ` -pix_fmt yuv420p` may solve the problem.
Original: 
```
mirv_streams settings add ffmpeg qp12 "-c:v libx264 -preset ultrafast -qp 12 {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}"
```
After: 
```
mirv_streams settings add ffmpeg qp12 "-c:v libx264 -preset ultrafast -qp 12 -pix_fmt yuv420p {QUOTE}{AFX_STREAM_PATH}\video.mp4{QUOTE}"
```

**Comment by Devostated** [comment]
Hello @Purple-CSGO can we quote and link this and your blog post in our manual ?

**Comment by dtugend** [comment]
by quote devostated means to quote / copy parts into the HLAE manual / wiki.

**Comment by Purple-CSGO** [comment]
Yeah sure! I've also made a video to show how to use it. It's on a CN video website and made in Chinese, but I can add English subtitle , so it's not a nbig problem.
https://b23.tv/av56424646

**Comment by dtugend** [comment]
Saw you added it to the Wiki already:
https://github.com/advancedfx/advancedfx/wiki/How-to-use-FFMPEG-HLAE-to-record-with-ready-to-use-config-preseted

Thanks. Closing this issue :-)
