### ISSUE TITLE
Cant download the .zip

### ISSUE THREAD

**Issue by flapzdercoole** [advancedfx/advancedfx#19]
Download stops after a few seconds from itself. Every other tool and stuff i downloaded works , the sourcecodes download working aswell for me. Only the HLAE 2.41.1.zip is not working.

**Comment by dtugend** [comment]
The downloads are hosted by GitHub on the S3 Amazon Web Services. There seem to be a routing issues from Germany to these servers when traffic goes through telia.net, it doesn't get past that.

Please try again later.

**Comment by dtugend** [comment]
They (whoever it is) seem to have fixed it, can you confirm?

**Comment by dtugend** [comment]
I am considering this solved for now.
