### ISSUE TITLE
GPU accelerated encoding

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#195]
- https://bxt.rs/blog/fast-half-life-video-recording-with-vulkan/

**Comment by Purple-CSGO** [comment]
It seems ffmpeg support gpu encode. Does it work fine to use native ffmpeg commands to accellerate? heard that CUDA works well encoding HEVC/H265

**Comment by dtugend** [comment]
I didn't check if the FFMPEG builds used by HLAE support GPU accelerated encoding.

However what this issue means is to support it without having to download form the GPU into system memory and back again etc. (this is not possible with the way FFMPEG is currently integrated with HLAE through pipes).

**Comment by maxpain** [comment]
Are there any plans in the near future for this feature? @YaLTeR did fantastic work on optimizing the encoding pipeline for Half-Life, especially converting colors in GPU and using Vulkan to capture frames.

In our case, we record hundreds of CS:GO highlights for our users per hour and recording speed is the most important factor, so I'm doing research on how to optimize it.

**Comment by dtugend** [comment]
The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
