### ISSUE TITLE
Cant change skybox

### ISSUE THREAD

**Issue by DeagleAcer** [advancedfx/advancedfx#196]
I type sv_cheats 1, then sv_skybox "blue1" but nothing happens I dont even get an error message. Works on no maps whatsoever. Also I get "exec couldnt exec afx/update workaround" when entering this string: "
sv_cheats 1;
fov_cs_debug 105;
sv_skyname orange3;
exec afx/updateWorkaround;
mirv_streams record format tga;
mirv_streams record name "Videos - Montage Clips";
host_timescale 0;
cl_draw_only_deathnotices 1;
host_framerate 240"

 even after trying the fixes listed in the already posted threads here. Really hope people check these because no one on reddit is answering me and theres 0 youtube vids also. Executing Frustration.exe

**Comment by dtugend** [comment]
1) [Non-ASCII chracters in HLAE install location can cause problems #65](https://github.com/advancedfx/advancedfx/issues/65)

2) [Tutorial: CS:GO: Replace sky](https://github.com/advancedfx/advancedfx/wiki/Tutorial%3A-CS%3AGO%3A-Replace-sky-with-mirv_streams-on-nuke---inferno---train)

Edit: In case you use CustomLoader: We recommend using File -> Launch CS:GO dialogue instead.

**Comment by DeagleAcer** [comment]
are you a bot? because I said 1 already was tried and didnt work and 2
doesnt apply to my question

**Comment by dtugend** [comment]
I am not a bot. Both issues issues can apply to your question, especially the second one. Your problem description indicates you have two problems (cfg not working + skybox not changing).

Please tell us your HLAE install location / path if it's not secret.

(Btw. In case you use CustomLoader: We recommend using File -> Launch CS:GO dialogue instead.)

**Comment by dtugend** [comment]
Closing due to no feedback, hoping it's solved.
