### ISSUE TITLE
How get the entire playermodel from recorded demo

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#197]
Hi, I done a cool clip offline with bot using "record <name>" command to get the demo.
But when I try to do a cinematic or weapon cam, only the viewmodel is showed.
This create a kind of floating viewmodel ^^
Have any command to do in demo or before recording the demo?
Thanks.
![floatingviewmodel](https://user-images.githubusercontent.com/42187538/59881867-ed85b200-93b0-11e9-8cb1-533f1fcada66.PNG)

**Comment by dtugend** [comment]
You need to switch into free look mode, this can be done by entering `spec_mode 6` into the game console.

**Comment by qriosserra** [comment]
Thank you for your answer, but `spec_mode 6` does nothing in my demo at my surprise :/

**Comment by xNWP** [comment]
Hi @Atsxshi ,

Try first typing `sv_cheats 1` and then `spec_mode 6` or `thirdperson`. From there you should be able to enter the HLAE free cam with `mirv_input camera`. Hope this helps :-)

**Comment by qriosserra** [comment]
Done!
`thirdperson` works in my case but not `spec_mode 6`
Thanks all.

**Comment by xNWP** [comment]
Happy to hear!

**Comment by dtugend** [comment]
spec_mode 6 is for GOTV demos. You are probably on a POV (in-eye) demo, be aware that thirdperson works there, but it will only record things it considers visible to the player that records the demo.
