### ISSUE TITLE
[Wiki] How to record a GOTV demo on a local server

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#199]
# How to record a GOTV demo on a local server

## 1. 
If you want the local GOTV demo to be recorded in 128 tick then add the command line `-tickrate 128` to your Counter-Strike: Global Offensive [launch options on Steam](https://support.steampowered.com/kb_article.php?ref=1040-JWMT-2947).

## 2.
Start CS:GO like you normally would.

## 3.
Go into a local practice with bots game and put it on whatever map and game mode you want.
![Image of Practice with bots](https://user-images.githubusercontent.com/52090508/60192687-965f6180-9836-11e9-8ffa-3d21f45f5a78.PNG)

## 4.
Once you've loaded into your offline game open up the developer console and write `tv_enable 1` to enable GOTV on your server.

Then change the map with the console command `changelevel [de_nameofmap]`, for example `changelevel de_mirage`.

## 5.
When the level/map has changed write `tv_record [nameofdemo]` in the developer console and it will start recording a GOTV demo.

*(The .dem GOTV demo file will be stored in your default csgo directory)*

## 6.
You can now do whatever you want until you're done with the actions that you wanted to record.

## 7.
Once you wish to stop recording your GOTV demo write `tv_stoprecord` in the developer console and then you may disconnect from the local server if you'd like.

## 8.
That's it, you're done! Now to play the GOTV demo just do like you normally would, either with the demoui or with the console command `playdemo [nameofdemo]`.

**Comment by dtugend** [comment]
Added to manual: https://github.com/advancedfx/advancedfx/wiki/How-to-record-a-GOTV-demo-on-a-local-server
Added you to credits: https://www.advancedfx.org/credits/
Thank you.
