### ISSUE TITLE
Det går inte att hitta filen// The file can not be found

### ISSUE THREAD

**Issue by Ahlster** [advancedfx/advancedfx#2]
när jag startar cs med HLAE kommer det upp en ruta som säger "System.ComponentModel.Win32Expection (*numbers*) det ger inte att hitta filen.
Vid 
Sysytem.Diagonostics.Process.StartWithCreateProcess(ProcessStartInfostartinfo)
vid System.Diagnostics.Process.Start ()
vid AfxGui.loader(Enumerable'1 getHookPathCollection, String prigramPath, String cmdLine, String enviroment) 
Fattar inget och undrar om någon kunde hjälpa mig med problemet...

When I start cs with HLAE, there will be a box that says "System.ComponentModel.Win32Expection (* numbers *) does not help find the file.
At
Sysytem.Diagonostics.Process.StartWithCreateProcess (Process Start Start Info Info)
At System.Diagnostics.Process.Start ()
At AfxGui.loader (Enumerable'1 getHookPathCollection, String prigramPath, String cmdLine, String enviroment)

Does not matter if anyone could help me with the problem ...

**Comment by dtugend** [comment]
1) HLAE can not be run directly from the ZIP file, please make sure to extract all files and folders in an (new / empty) folder you like.

2) Make sure that the injector.exe file is not missing, some Anti Virus like Sophos tend to delete it: http://advancedfx.style-productions.net/forum/viewtopic.php?p=6481#p6481

**Comment by dtugend** [comment]
Closing due to missing feedback / no reply. Hopefully it was solved.
