### ISSUE TITLE
Can't open CSGO through HLAE

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#20]
Hello!

Whenever I try to open CSGO through HLAE, It gives me the following error message:

> System.ApplicationException: Failedto launch program, error code: 5 at AdxGui.Loader.Load (IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment)

I don't have any custom loader enabled or done anything weird in CSGO itself. The weird thing is, that 3 days ago, it worked just fine. Could it have been a CSGO update?

I tried the following:

- Reinstall HLAE
- Verify game cache of CSGO
- Disbale movie making config

Anyone know how to fix this?

**Comment by dtugend** [comment]
You need to disable anti cheats like ESEA / FaceIt / ChallengeMe.gg

**Comment by ghost** [comment]
Ahh that fixed it! Thanks! 

I feel stupid now hahaha
