### ISSUE TITLE
How render bigger resolution than screen's one

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#201]
Hi, I need to render a clip with 2203x2203 resolution.
My screen is a typical 1080x1920 and `-weight` & `-hight` launch options don't allow me to open CS:GO's window with a bigger resolution than my screen.
So, is there a trick or something to open CS:GO's window with a bigger resolution?
Thanks.

**Comment by dtugend** [comment]
You can change your virtual Desktop resolution in many
- NIVIDA Drivers: It's called Dynamic Super Resolution (DSR)
- AMD Drivers: It's called Virtual Super Resolution (VSR)

For 2203 height you need the DSR factor at approximately 2.4 or greater.

Please be aware that resolutions that have an odd dimension size can cause problems with CS:GO, e.g. with the Cross Hair (e.g. lines missing).

Also might be a good idea to use a pixel dimension size dividable by 4, e.g 2200 or 2204.
