### ISSUE TITLE
Wiki contributors to add to credits

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#203]
Edit:

If you have contributed to the Wiki, you can make an [issue in contrib repository](https://github.com/advancedfx/contrib) in order to be added to or updated in the credits.

**Comment by Purple-CSGO** [comment]
+1

**Comment by dtugend** [comment]
Hi.

I have seen the issue here: https://github.com/advancedfx/advancedfx/issues/189
Thank you for your contribution there.
However we haven't come around yet to merge it into the Wiki itself ourselves, which is why you haven't been added yet to the list. If you want, you can add it yourself directly, since the Wiki should be writeable for you: https://github.com/advancedfx/advancedfx/wiki

Or did I overlook a contribution to the Wiki [?]

**Comment by dtugend** [comment]
@Purple-CSGO saw your contributions. Thank you. updated advancedfx/contrib accordingly.

**Comment by dtugend** [comment]
If you have contributed to the Wiki, you can make an [issue in contrib repository](https://github.com/advancedfx/contrib) in order to be added to or updated in the credits.
