### ISSUE TITLE
Error code: 13 and customloader error when launching csgo from customloader

### ISSUE THREAD

**Issue by waterskyy** [advancedfx/advancedfx#204]
``` AfxError #13: Title: AfxHook error ```
![image](https://user-images.githubusercontent.com/20155464/61687306-c5c89780-ad2a-11e9-8c6d-5e1f47607aad.png)
![image](https://user-images.githubusercontent.com/20155464/61687327-d37e1d00-ad2a-11e9-82d4-c258d4ec10c4.png)

**Comment by dtugend** [comment]
1) We recommend using File -> Launch CS:GO instead of Custom Loader.
2) Please check that the path to AfxHookSource.dll in your Custom Loader is correct / valid. Also make sure you don't have empty entries in the list.

**Comment by waterskyy** [comment]
> 1. We recommend using File -> Launch CS:GO instead of Custom Loader.
> 2. Please check that the path to AfxHookSource.dll in your Custom Loader is correct / valid. Also make sure you don't have empty entries in the list.

![image](https://user-images.githubusercontent.com/20155464/61688718-65d3f000-ad2e-11e9-8802-7f53a6984faf.png)

**Comment by dtugend** [comment]
CS:GO is 32 bit, ReShade64.dll is 64 bit and thus is wrong.

Here's a proper ReShade tutorial:
https://youtu.be/oBU9z75gTFg

**Comment by waterskyy** [comment]
> CS:GO is 32 bit, ReShade64.dll is 64 bit and thus is wrong.
> 
> Here's a proper ReShade tutorial:
> https://youtu.be/oBU9z75gTFg

okay, well done, im idiot thx ya
