### ISSUE TITLE
HLAE not working properly 

### ISSUE THREAD

**Issue by danedits** [advancedfx/advancedfx#205]
Hello! I'm quite new to HLAE but probably have used it for 2 months now without any problems. Today I got this error popup sign c:\source\advancedfx\afxhooksource\addresses.cpp:897
I have tried to check for updates but theres none, and I also have the latest version.
Anyone knows how to solve this issue? Thanks in advance and have a great weekend.
![afxhooxsource hlae issue](https://user-images.githubusercontent.com/53370313/61993942-04848780-b074-11e9-92cb-955ea95f5a02.png)

**Comment by dtugend** [comment]
1) Please compare the _**full**_ path (not only shortened version, click on it please to see the full) when you right click CS:GO in Steam library -> Properties -> Local Files tab -> Brows Local Files button with the one you set in HLAE options. HLAE should be the same.

2) Make sure that you are not signed into any beta version of CS:GO (Betas tab in properties dialogue).

3) Verify Game Cache and let it re-download files if required (Local Files tab).

3) Sometimes a reboot of the PC will already fix the problem.

**Comment by danedits** [comment]
thanks for help! I must've been unlucky cause my steam needed an update today and I was already auto-logged in, rookie mistake :D
