### ISSUE TITLE
Suggest adding lastround/nextround command (plus echo-like command)

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#207]
I don't know how many people have the same feeling as me: We have `demo_resume` ,`demo_pause` and `demo_togglepause` to bind keys to control the demo. We have `demo_timescale [num]` to slow down or speed up. However, we couldn't find a command that helps move back to the last round or forward to the nextround!
These 2 commands are quite useful even if they're usable only with hlae. Simple as `mirv_nextround` and `mirv_lastround` may work pretty well. pls!
-- --
In addition, I myself want a command like `mirv_echo` that works with non-ASCII characters, yet without adding "".
```
//Input
echo 你好
//Output   
� � � � � � 

//Input
echo "你好"
//Output   
你好

//Input
bind x "echo 你好"
//Press x
� � � � � � 

//Input
bind x "echo "你好""
//Press x

```
It could be figured out that console sees `"`echo `"` as a pair and ignore `你好""`. So it prints `\n` in the end, which is terrible when I'm writing scripts that print hints and instructions when pressing a key. The only solution is to create another cfg to print the info.  Valve :(
But it is only a selfish request. next/last round commands are important and Frequently Asked.
Orz...

**Comment by dtugend** [comment]
The echo command would require fixes deep in the CS:GO engine, except if you want to enter everything in hex code or something like that. So not sure if I'll do that command, probably not for now.

About the first idea I will try to think later.

Please avoid merging issues not related into a single issue, this makes it harder to manage them :-)

**Comment by dtugend** [comment]
I solved the mirv_echo issue, but a bit differently, there will be an mirv_exec command in one of the next releases:

Command help:
```
mirv_exec <sCommandName> "<arg1>" ... "<argN>" - Pass arguments <arg1> to <argN> to command named <sCommandName>,  use {QUOTE} for ", \{ for {, \} for }.
```

Example usage
```
mirv_exec bind x "echo {QUOTE}你好{QUOTE}"
```

Edit: will only work in CS:GO though.

**Comment by dtugend** [comment]
mirv_exec command released: https://github.com/advancedfx/advancedfx/releases/tag/v2.77.0

**Comment by dtugend** [comment]
Other feature released too https://github.com/advancedfx/advancedfx/releases/tag/v2.78.0 - just use the DemoUIPanel commands through mirv_vpanel command command.
