### ISSUE TITLE
Weird cut while in a campath

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#21]
Hi,

I'm trying to record a grenade kill, nothing special. But whenever the grenade explodes, the camera just cuts out to the next campath position. I don't quite know how to explain it any better so I recorded it: [Video](https://drive.google.com/file/d/0BxgPkmT-lpbmZnlOYWRZZFVEdkk/view?usp=sharing)

Any ideas on how to fix this? Is it something I'm doing wrong myself?

Thanks in advance,

Cyborg

**Comment by dtugend** [comment]
Might be a problem with the demo.

Try to follow the Smoother Demos Guide closely first:
https://github.com/ripieces/advancedfx/wiki/Source%3ASmoother-Demos
Especially don't ignore this: **Don't use the game's highlight feature, always use playdemo or demoui.**

If this doesn't fix your problem, consider providing the demo itself, demo time and tick, so I can check if anything can be done, but there is no guarantee, sometimes demos themselves are already broken.

**Comment by ghost** [comment]
That fixed it! I loaded the demo through demoui instead of the watch tab and ran those 3 commands mentioned in the link that you provided.

Thanks for your help!
