### ISSUE TITLE
HLAE 2_76_2_1 error

### ISSUE THREAD

**Issue by eryknowiak** [advancedfx/advancedfx#210]
Keep getting this error whenever I launch HLAE.
c:\source\advancedfx\afxhooksource\addresses.cpp:233

I get the error and then I close the error message. Then the game proceeds to start like normal but the game is very out of date. Most of my downloaded GOTV games are not available either. I tried to watch one of the few GOTV clips that I have and the game crashes before I get into the game everytime.

**Comment by dtugend** [comment]
Hi.

Some people have two CS:GO installs on their system and launch the old one.

You can find the path to the current one by right clicking CS:GO in Steam Library -> Properties -> Local Files tab -> Browse Local Files button. Compare the full (_not the shortened_) path to the csgo.exe there in the explorer window with the one in HLAE.exe. It's probably different, you need to use the one from Steam.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
