### ISSUE TITLE
HLAE failed to connect to local steam client service

### ISSUE THREAD

**Issue by outxge** [advancedfx/advancedfx#212]
I have searched exiting **open and closed** issues to verify this is a new question.
I have read and tried multiple solutions including the below: 
turn off all apps from opening using admin
launching using the actuall thing not a shortcut
verifying game cache
verifying client is up to dat
verifying hlae app is up to date 
and more! still no fix

Please help - issue message says fatal error - could not connect to local steam client process

**Comment by dtugend** [comment]
You probably have either Steam.exe or csgo.exe set to run as admin.
Please either set those to not run as admin (recommended) or set HLAE.exe to run as admin (not recommended).

To change the settings, right-click the exe file -> Properties -> Compatiblity tab, make sure that nothing is selected there and press OK.

**Comment by outxge** [comment]
neither of them are set as admin! I have checked this and changed up the permissions etc to see if it fixes it but still nothing!

**Comment by outxge** [comment]
@dtugend

**Comment by dtugend** [comment]
Hi, can you check the path to csgo.exe you set in HLAE:
Right click CS:GO in Steam Library -> Properties -> Local Files tab -> Browse Local Files button. Compare the full (not the shortened) path to the csgo.exe there in the explorer window with the one in HLAE.exe. It might be different (some people end up with two CS:GO installs after a while, where one is outdated), you need to use the one from Steam.

It's also possible that the Anti-Virus program interferes sometimes.

**Comment by outxge** [comment]
@dtugend Have tried all that as well! Aint looking good for me DX

**Comment by dtugend** [comment]
What's the path to your csgo.exe?
Steam is running though when you launch csgo from HLAE?
Consider contacting us in the HLAE Discord, since I am not sure if we'll be able to solve it through GitHub issues in a timely manner: https://www.advancedfx.org/support/

**Comment by outxge** [comment]
do you think its worth reinstalling steam? Would I have to reinstall all my games tho if I did?

**Comment by dtugend** [comment]
It's not worth it. Have you tried running HLAE as admin yet?
Edit: As said, it can also be caused by Anti-Cheat running in the background or your Anti-Virus too.

**Comment by outxge** [comment]
OK so Just retied it as admin and it said error 2002! However the game did launch through HLAE and although the vac warning stuff did appear! Do I need to fix this or ? and why is it not recommended to use HLAE  as admin?

**Comment by dtugend** [comment]
2002 is not a valid error code of HLAE, maybe you mean 2000 or 2001?

Here's a list with common solutions for common error codes:
https://github.com/advancedfx/advancedfx/issues/202#issuecomment-511399016

**Comment by outxge** [comment]
hey so just read some more stuff and am scared itless. So if you run HLAE how do you stop it running completely to be able to join vac protected servers?

**Comment by outxge** [comment]
and can you still get a ban even when it is'nt on?

**Comment by dtugend** [comment]
As long as you don't join VAC protected servers servers when csgo.exe is launched from HLAE you are fine.
In default settings HLAE adds -insecure to the launch options (so VAC is disabled and you can not join VAC protected servers) and these days that can not even be removed, so it should be impossible to get VAC banned with the latest official HLAE version.

**Comment by outxge** [comment]
why is it not recommended to use HLAE as admin?

**Comment by dtugend** [comment]
It's not required, it gives HLAE rights it doesn't need usually.
You can use it as admin. But if it doesn't work without, it means your Steam.exe or Steam shortcut is still running as admin.

**Comment by dtugend** [comment]
Is this solved?
