### ISSUE TITLE
How remove blood texture when hited?

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#214]
Hi, I search the command for remove that ugly blood texture from a stream (not the blood decal)
![screen](https://user-images.githubusercontent.com/42187538/62965223-d9848c80-be04-11e9-980d-5e661af21a33.PNG)
That's all, thanks!

**Comment by dtugend** [comment]
If you only want to remove this material, use:
https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams---picker---hiding-materials--entites-and-special-effects

If you want to remove more use this:
https://twitter.com/MolenTV/status/1134400694335791105

**Comment by dtugend** [comment]
Closing due to lacking feedback.
