### ISSUE TITLE
Can't start CS:GO from HLAE Client

### ISSUE THREAD

**Issue by Wormyyyxd** [advancedfx/advancedfx#216]
Every time I try launching CSGO with HLAE (on multiple versions including latest of both the game and the client) I get the same error message: 
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

Any help is appreciated.

**Comment by dtugend** [comment]
`2001	5	Faceit, other anticheats or antivirus blocking it`

Please make sure to turn off / exit FaceIt / Challengeme.gg / ESEA client before using HLAE.

Related: #202 Add possible solutions to more error codes

**Comment by Wormyyyxd** [comment]
> `2001	5	Faceit, other anticheats or antivirus blocking it`
> 
> Please make sure to turn off / exit FaceIt / Challengeme.gg / ESEA client before using HLAE.
> 
> Related: #202 Add possible solutions to more error codes

After closing all clients I am now getting error code 740. Might this be antivirus?

Full error info:

System.ApplicationException: Failed to launch program, error code: 740
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

**Comment by dtugend** [comment]
2001	740	make sure neither HLAE.exe nor Steam.exe nor csgo.exe are set to run as admin

**Comment by dtugend** [comment]
Closing due to lacking feedback.
