### ISSUE TITLE
Possible to bypass -insecure check

### ISSUE THREAD

**Issue by xNWP** [advancedfx/advancedfx#218]
The following check: https://github.com/advancedfx/advancedfx/blob/21b6dfe9da68937927e20cc583734c6bcd0e9ee0/AfxHookSource/main.cpp#L2223

Will return false for an input such as _+echo " -insecure"_. Needs a more robust system for detecting a proper insecure launch.

**Comment by dtugend** [comment]
Confirmed, but the actual problem* is `+echo " -insecure "` - where it thinks it's in -insecure mode, but is not.
