### ISSUE TITLE
hlae doesn't launch cs

### ISSUE THREAD

**Issue by ast-n** [advancedfx/advancedfx#219]
i got no error reports or nothin in steam it shows i start the game but it goes back to online after a few seconds. Looked around couldn't find answers, i don't have any anti-cheat installed for cs and i have tried on different versions using the cs launch option and custom loader. 
Thanks

**Comment by dtugend** [comment]
Please check if you have an "addons" folder in the csgo sub-folder of your CSGO install. If yes please rename it temporarily or delete it.

**Comment by ast-n** [comment]
No "addons" folder :(

**Comment by dtugend** [comment]
Can you

**Comment by dtugend** [comment]
Sorry hit the wrong button.

Can you please check if there's .mdmp or .dmp files in your csgo.exe folder or the Steam dumps folder and send the latest one that is bigger than 0 bytes to contact@advancedfx.org (you can use send.firefox.com)?

**Comment by dtugend** [comment]
Also check if you have any d3d9.dll in your csgo.exe folder or the bin subfolder, if so please delete it from those folders.

**Comment by ast-n** [comment]
No .dmp nor .mdmp neither d3d9.dll in any of the cs folders and bin folders

**Comment by dtugend** [comment]
Did you check C:\Program Files (x86)\Steam\dumps?

**Comment by tymehaha** [comment]
oh yeah which one?

**Comment by ast-n** [comment]
alright shot you an email

**Comment by dtugend** [comment]
Replied you, sadly could not figure out the problem with what you sent yet, see mail for more details / hints.

**Comment by dtugend** [comment]
Btw, are you using NVIDIA Overlay (e.g. from Geforce Experience)?

There's a known problem with older versions of that crashing when using HLAE, when it tries to display that sliding bar in the top right.

If yes, please temporarily disable it and try without the overlay / shadowplay. If it works then, consider upgrading your graphic drivers.

Other graphic overlays might cause problems too (e.g. Discord / Teamspeak / Overwolf / ...).

**Comment by dtugend** [comment]
Still waiting for the feedback about what I told you by email :/

**Comment by dtugend** [comment]
Closing due to lacking feedback.
