### ISSUE TITLE
HLAE + MIGI

### ISSUE THREAD

**Issue by negativepriority** [advancedfx/advancedfx#227]
Hi dear dtugend, i dont know if you knew MIDI, it's an alternative csgo launcher when is easy to launch csgo mods (you can add easly new weapon models or change skins) if you can make possible to record clips by using their launcher, this can be a great thing!

**Comment by dtugend** [comment]
No I don't know it.

Might be easier the other way round - to integrate HLAE into the launcher, just like csgo-demos-manager.com did.

Hint1/2: I usually ignore closed issues.
Hint2/2: I recommend to avoid targeting issues at specific people.

**Comment by negativepriority** [comment]
Thank you anyway,
I asked to Zool (the creator of MIGI Launcher) and he told me to write in launch option of hlae, -game migi/csgo and It worked!

PS: Yesterday i was really tired so i missclicked two times and i typed MIDI instead of MIGI 😂
