### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#228]
### Core interface features

- version
- enumerate installed plugins
- state of core and other plugins
- Common runtime info. e.g., path to hlae.exe, dlls and csgo.exe.
- System info. e.g., win7 / win10 / linux (if the core could run)
- Update checking (Something like nskinz's one). Both hlae and plugins
- Undo / redo. History list including all operations of plugins. (oof)
- "Macro. Seems like cfgs but it saves operations of (even different) plugins, then loads."

### Plugin interface features

- allow communication between plugins

### Game interface features
- Execute commands to csgo console
- After executing certain commands, Get feedback msgs from csgo console (related directly to the command)
- Get msgs from csgo console (general)
- Read and modify engine convars
- Get players' info(i.e. steamid) through Index(0~9)
- Get current demo's filepath
- Get current status of mirv_steams / streams' record settings / voice block settings / deathnotice highlight settings etc...
- Game state, e.g., main menu / demo / match (for live).
- Match state, e.g., demo info / mirv_listentities
- e.g., mirv_pgl. Both raw data and drawing tasks.

## Modules/Interfaces of an HLAE plugin (?)
- GUI
- DLLs to be run in HLAE.exe process (64bit) (is this really needed?)
- DLLs to be run in game process (32/64bit, depends on game)
- own processes to be launched with certain parameters?

----

References:

- https://github.com/advancedfx/advancedfx/issues/322#issue-609713211
- https://github.com/advancedfx/advancedfx/issues/322#issuecomment-1463760665

----

- https://docs.rs/wasmtime/latest/wasmtime/
- https://github.com/bkaradzic/bgfx
- https://github.com/grpc-ecosystem/grpc-gateway
- https://crates.io/crates/ipc-channel

----

- CppCon 2016: John Lakos “Advanced Levelization Techniques (part 1 of 3)": https://www.youtube.com/watch?v=QjFpKJ8X
- CppCon 2016: John Lakos “Advanced Levelization Techniques (part 2 of 3)": https://www.youtube.com/watch?v=fzFOLsFASjU

Old notes bellow:

The first interfaces are still in draft, but start to take shape:
* https://github.com/advancedfx/advancedfx/tree/main/interfaces/c

The interfaces **will not solve** the following problems:
- Package sources and management system for installing / managing the plugins - **If you have good ideas for that, let us know.** (I would like to make use of https://github.com/features/package-registry, we are in the beta of that).

Important things missing:
* System for modules (nodes) that can be represented in a GUI interface (e.g. https://github.com/Nelarius/imnodes)

**Comment by dtugend** [comment]
## Why Invalidateable Reference Counting?

- Solves Dependency and life-cycle management while avoiding deadlocks that would happen with non-invalidateable references
- Solves Implementation / code becoming unavailable for various reasons
- Solves Reliable explicit deletion of objects

**Comment by dtugend** [comment]
Probably I will drop the idea of invalidatable Reference Counting idea:
```
//
// AdvancedfxIReferenced

struct AdvancedfxIReferencedVtable
{
	void(*AddRef)(struct AdvancedfxIReferenced* This, struct AdvancedfxRoot* child);
	void(*Release)(struct AdvancedfxIReferenced* This, struct AdvancedfxRoot* child);

	struct AdvancedfxRoot* (*GetSomeChild)(struct AdvancedfxIReferenced* This);
};

#define AdvancedfxIReferencedVtable_UUID_FN(fn) ADVANCEDFX_UUID_APPLY_FN(fn,0xFDC23842,0xEC90,0x4E84,0x9361,0x0C,0x1B,0x0C,0x61,0xC4,0xC2)

struct AdvancedfxIReferenced
{
	struct AdvancedfxIReferencedVtable* Vtable;
};

#define AdvancedfxIReferenced_UUID_FN(fn) ADVANCEDFX_UUID_APPLY_FN(fn,0xE46F9D70,0xC445,0x476B,0xB0D7,0xF5,0x7C,0xA6,0x09,0xF5,0xC4)
```

Instead each node will maintain a list of childs (which is expensive, but I don't see a better way that won't end in a mess) and offer the GetSomeChild function, so you can recurse into childs until you hit a leaf and can release so it will delete it instantly and so on.

**Comment by dtugend** [comment]
Decided we will start a bit simpler and get rid of some over-engineering for now:
- https://github.com/advancedfx/advancedfx/tree/v3/interfaces/c

Will (probably) also expose to other languages with SWIG ( http://www.swig.org/ ) sooner or later.

**Comment by dtugend** [comment]
- Observer Pattern  
https://www.reddit.com/r/learnprogramming/comments/ldr8gd/elevated_hookable_destructor_ehd_whats_this/

**Comment by dtugend** [comment]
@DuKeM-CSGO in response to https://github.com/advancedfx/advancedfx/issues/322#issuecomment-1463760665

If possible please elaborate in this issue on what these mean:

- Game State
  - Engine hooks.
- GUI
  - Receive user input from keyboard, mouse and others. e.g., joystick or touchpad. They should be modifiable for the user.

**Comment by DuKeM-CSGO** [comment]
1. It's up to developers if engine hooks are needed by plugins. e.g., d3d9 hook was used by me for `mirv_stream` developing.
2. [The issue](https://github.com/advancedfx/advancedfx/issues/704) told that the hard code key binding should be modifiable, but obviously not only for `mirv_input` but any others. _If the gui is only an in-game overlay, it needs input from only keyboard and mouse. But when the gui could display on other devices, such as smartphone, it's necessary to adapt new input way. Joystick is for match living I think._

**Comment by dtugend** [comment]
@DuKeM-CSGO 2. Do you mean the plugins can react to user interface input to the GUI [e.g. to make shrotcuts]? Or are you talking about plugins being able to spawn own overlay windows / windows and handle events targeted at those windows?

**Comment by DuKeM-CSGO** [comment]
It's the core's duty to create a window, and handle input events at a low level. Plugins would like to use a higher level interface.
e.g., the core receives a "drag" event from mouse. Then my plugin's gui reacts to it, changing the value of a slider. Soon the user can do the same "drag" by touchpad, but my plugin doesn't need to know the event is from a different device.
It's not a good idea for plugins to use their own input handler. Especially for plugins in other languages, such as python, it's better to use a generic interface.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
