### ISSUE TITLE
mirv_streams and reshade

### ISSUE THREAD

**Issue by negativepriority** [advancedfx/advancedfx#229]
Hi dtugend, in these days im record some clips using hlae and reshade, but if i put some reflections and shadows effects (from reshade), when i want to record using mirv_streams record start, custom reflections and shadows are not recorded.
Real result: http://prntscr.com/p9hj94
After recording result: http://prntscr.com/p9hklw
So my advice (if is possible) that in the future if you can implement reshade features inside hlae.

**Comment by dtugend** [comment]
You can record reshade with startmovie https://www.youtube.com/watch?v=oBU9z75gTFg

Closing, because this is a duplicate of #63
