### ISSUE TITLE
Is it possible to remove dead bodies from "matteEntity" stream?

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#232]
Hi, I have a question. I tried to figured out if it is possible to remove dead bodies? I tried with "playerModelsAction", but that removes alive people aswell. So is it possible to split "alive" and "dead" people?
Thanks in advance!

**Comment by dtugend** [comment]
Yes, but:

First you need to apply this workaround:
https://github.com/advancedfx/advancedfx/issues/23

Then you can use `mirv_stream edit <streamName> picker ent [....]` to hide them by entity handle (it can be done with `mirv_stream edit <streamName> actionFilter addEx [....]`, it's explained in the longer tutorial how to use it): https://github.com/advancedfx/advancedfx/wiki/Tutorials#mirv_streams---picker---hiding-materials--entites-and-special-effects

**Comment by ghost** [comment]
Thanks a lot!
