### ISSUE TITLE
agr record

### ISSUE THREAD

**Issue by yellowfisherz** [advancedfx/advancedfx#233]
why agr record dont have pov’s player’ model(have other player’ action model)now?
only lost pov’s player’ model.

**Comment by Devostated** [comment]
Hey,
can you provide us with the commands you used ?
We are not aware of any changes from our or CSGOs side.

**Comment by yellowfisherz** [comment]
bind "F11" "host_timescale 0;mirv_snd_timescale 1;host_framerate 24;fps_max 24;mirv_streams add normal normal;mirv_streams record agr enabled 1;mirv_streams record agr recordCamera 1;mirv_streams record agr recordPlayers 1;mirv_streams record agr recordWeapons 1;mirv_streams record agr recordProjectiles 0;mirv_streams record agr recordViewmodel 0;mirv_streams record bvh cam 1;mirv_streams record start"

**Comment by Devostated** [comment]
mirv_streams record agr recordViewmodel 0 has to be set to  1 in order to get PoV

also do you really  need bvh cam, since you already record AGR camera and the normal stream ? Not that it would break anything, just wondering :)

**Comment by yellowfisherz** [comment]
hi, this is my bad. i expressed the wrong meaning. i update the question.Can you watch the question again ?pls

**Comment by Devostated** [comment]
Could it be that you are looking for mirv_streams record agr recordInvisible 1 ?
It would record the 3rdperson character model while you are in the PoV.
If not try to tell us what you want to do in your native language and we will try to find someone to translate.

**Comment by yellowfisherz** [comment]
录制agr的时候，我需要第一人称视角的第三人称模型
但是目前只有除了第一人称视角的第三人称模型，其他玩家的模型都有，只有第一人称视角的没有。(chinese)

if fov’s player is 1, other player is 23456789
, i need 1’s 3rdperson model

**Comment by dtugend** [comment]
Try to set `mirv_agr recordInvisible 1` before recording, as Devostated said.

**Comment by yellowfisherz** [comment]
thank you , mirv_agr record Invisible 1 is useful.

**Comment by dtugend** [comment]
I think this is solved (?).
