### ISSUE TITLE
[GoldSrc/1.6] Minor bug thanks to a new update

### ISSUE THREAD

**Issue by Dechno1337** [advancedfx/advancedfx#237]
There was an update to CS 1.6 recently:
[https://steamcommunity.com/games/10/announcements/detail/1582377291594251504](https://steamcommunity.com/games/10/announcements/detail/1582377291594251504)

Error message when launching CS 1.6 with HLAE 2.81.3:
_Problem in
C:\source\advancedfx\AfxHookGoldSrc\hl_addresses.cpp:738_

However, clicking OK still causes HLAE to get hooked into the game and most features should still work. (I only tried recording, sampling and sound export.)

**Comment by dtugend** [comment]
This is related to the crosshair fix, reading the changelog they tampered with the crosshair, so makes sense.
