### ISSUE TITLE
Recording only a part of the screen?

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#240]
Hello,
I wanted to know if it is possible to record a videofile with not the whole display being captured, but only a part of it? For example we have 1920x1080 fullscreen, can I get only top left corner with 400x400 resolution and record it in videofile?
Thanks in advance!

**Comment by dtugend** [comment]
This is currently only possible when using an FFMPEG preset (e.g. one for uncompressed Avi), by making a custom one with FFMPEG options set for cropping. Of course it will still capture the full frame, but ffmpeg will crop it before writing it to disk. For more information see
- https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#ffmpeg-image-stream-encoding-to-video
- https://github.com/advancedfx/advancedfx/wiki/Tutorials#how-to-use-ffmpeghlae-to-record-with-ready-to-use-config-preseted

**Comment by ghost** [comment]
That will do for me, since I already using customized FFMPEG.
Would I need to use smth like this: **ffmpeg -i before.mp4 -vf "crop=w: h: x: y" after.mp4**?

**Comment by dtugend** [comment]
HLAE communicates with ffmpeg directly over pipes, maybe have a look at the config in the tutorial I linked, on how to set the parameters there, for example instead of the " you have to use {QUOTE}

**Comment by ghost** [comment]
Got it, thanks a lot!

**Comment by dtugend** [comment]
If you have trouble installing FFMPEG correctly into HLAE manually, you can use the HLAE_Setup.exe (installer version) instead, it downloads FFMPEG by default from https://ffmpeg.zeranoe.com/builds/ and installs it correctly.
