### ISSUE TITLE
Installer improvement

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#241]
The process of installation is not perfect. "optional choice" is 95% ignored but In some areas, downloading ffmpeg is quite slow, thus installation is stuck, which is one of the FAQs asked everyday.

It is better to put "optional choice" directly into page2. page1 as before. By clicking "next step", "FFMPEG" page is shown up.

That is quite necessary though!

**Comment by dtugend** [comment]
I moved the option from the options page to the install page (and made space for that by removing the red sidebar).
Hope it will do till v3.
