### ISSUE TITLE
"Guide" page

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#243]
I'm assuming adding an "Guide" page to hlae. In China, leaners gather from  forums and video website(like bilibili) to our "QQ Groups" that could hold up to 2k people for each one (QQ is a communication tool developed by Tencent) . However many basic, repeated , sometimes very stupid questions are asked each day, and that makes us headache. In my opinion, it is of some help to offer some guides to hlae learners no matter where they are.

Would it be possible to add a "Guide" page that pops up everytime hlae lauches and can be easily turned off if he/she don't need it?

The "Guide" page displays differently according to the language/area, and is written by donators from the same country. It could show many FAQs and solutions and I think it could help much to new learners!

**Comment by dtugend** [comment]
?

**Comment by dtugend** [comment]
Please elaborate, it's not obvious.

**Comment by dtugend** [comment]
![image](https://user-images.githubusercontent.com/3610128/72211199-899b1600-34c7-11ea-953c-ca73b00a45d9.png)

- I'd suggest to use the free grey space for putting a big help button that is translatable (text and link).
- I personally prefer to have the HLAE Wiki as only acceptable entry point for that page, which also means not limiting that page to donors, example `Home` = default, `de: Start` = German, and so on. The disadvantage of this is vandalism can occur.

**Comment by Purple-CSGO** [comment]
Both are OK, I think.

btw, I'm talking with a big buddy who's already working on developing websites. I've suggested to create a forum website mostly targetting CN hlae learners, offering FAQs and solutions. Might use gitment to realize it. Yet it needs some time.

**Comment by dtugend** [comment]
This is already finished, but depends on finishing #258 for being able to be useful for you.

**Comment by dtugend** [comment]
![image](https://user-images.githubusercontent.com/3610128/72250212-5ce81b00-35fb-11ea-9acf-6be955901be5.png)
Basically there will be this blue button at the bottom and the link / text should point at localized "Home" page (e.g. de: Start) in HLAE Wiki (has to be HTTP or HTTPS URL).
