### ISSUE TITLE
GetImage failed. Code 1002

### ISSUE THREAD

**Issue by solarlfow** [advancedfx/advancedfx#245]
Make sure that AfxHook.dat is not missing / broken and accessible.

When trying to Launch HLAE this shows up and ive been trying to fix it so i can start editing clips/recording

**Comment by dtugend** [comment]
This probably means you didn't extract all files and folders from the ZIP folder into an new empty folder and ran HLAE.exe from there.

HLAE can not be run from the ZIP file.

If unsure use the HLAE_Setup.exe Installer version, that one is easier to use and less can go wrong.

**Comment by solarlfow** [comment]
thank you its working now much love
