### ISSUE TITLE
CS:GO quick demo jump / rewind / forward

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#247]
https://twitter.com/dtugend/status/1183669680034201601
- [x] tamper with demo buffer
- [x] check if full updates will work: yes, but not fast forwarding without further actions taken ("GetDynamicBaseline: FindStringIndex(34-CC4) failed.")
- [ ] fake full updates
- [ ] support fast forwarding

**Comment by xNWP** [comment]
fixed typo in title

**Comment by dtugend** [comment]
Closing in favor of https://github.com/advancedfx/csgo-demo-problems/issues/1

**Comment by dtugend** [comment]
This has been done in CS:GO direclty instead and released around Octobe 2020 as `demo_index 1`.
