### ISSUE TITLE
addresses.cpp:954 (AfxHookSource.dll)

### ISSUE THREAD

**Issue by durielone** [advancedfx/advancedfx#248]
A few hours ago I was using hlae without problems, but now I have the following problem:
[https://i.imgur.com/UqETMYp.jpg](url)

I have noticed that the main csgo panel has changed(update), can this be the reason?

 FYI: 

> ChangeGameUIState: CSGO_GAME_UI_STATE_INVALID -> CSGO_GAME_UI_STATE_MAINMENU
> |
> | AfxHookSource (Nov  1 2019 17:37:55)
> | http://advancedfx.org/
> |
> | VClient: VClient018 (CS:GO)
> | VEngineClient: VEngineClient014 (CS:GO)
> | VEngineCvar: VEngineCvar007 (CS:GO)
> | GameDirectory: G:\Steam\steamapps\common\Counter-Strike Global Offensive\csgo
> |

**Comment by dtugend** [comment]
There's been released an update a few seconds ago:
https://github.com/advancedfx/advancedfx/releases/tag/v2.82.0

**Comment by durielone** [comment]
Oh wow, this should be the fastest response in history! thank you very much
