### ISSUE TITLE
[GoldSrc/1.6] failed to initalize authentication interface

### ISSUE THREAD

**Issue by MaximilianKohler** [advancedfx/advancedfx#251]
I searched for this error and got no results so posting this fix for anyone who searches. 

Run as admin. 

If you're using coldemoplayer, probably good to run that as admin too. 

win 8.1 x64.

**Comment by dtugend** [comment]
This is only required when your Steam runs as admin. Ideally neither Steam.exe, nor HLAE.exe nor hl.exe nor the shortcuts would be set to run as admin.

Edit: thanks for sharing the solution.

**Comment by MaximilianKohler** [comment]
I can't remember the exact reason - it might have been the overlay or integration with non-steam games or other programs - but I've had to run steam (and lots of other programs) as admin, or I run into all sorts of problems.
