### ISSUE TITLE
Improve zh-CN translation

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#253]
https://github.com/Purple-CSGO/hlae-translation-into-Chinese

The latest `HyperlinkTheme_zh-CN.wxl` and `zh-CN.wxl`

It's for better understanding when downloading ffmpeg is unbearably slow in some areas.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/commit/c6c9aaba87cce1821be3b6295b42a0f52f482750
