### ISSUE TITLE
Broken AGR files in 2.83.0

### ISSUE THREAD

**Issue by Devostated** [advancedfx/advancedfx#254]
AGR files of the HLAE version 2.83.0 can't be loaded
Blender gives error:
WARNING: Unknown packet at 2574

HLAE 2.82.0 AGR still works fine!

**Comment by dtugend** [comment]
Does it happen with any new recording?

Otherwise I will need:
-  AGR settings
- demo
- demo tick

**Comment by Devostated** [comment]
I tried different demos and it happened for every new recording

Settings used:
```
host_timescale 0
host_framerate 30
mirv_streams record agr enabled 1 
mirv_streams record agr recordPlayers 1
mirv_streams record agr recordCamera 1
mirv_streams record agr recordInvisible 1
mirv_streams record agr recordWeapons 0
mirv_streams record agr recordProjectiles 0
mirv_streams record agr recordViewmodel 0
```
