### ISSUE TITLE
Remove problems on "mirv_calcs" commands

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#260]
Here's what I'm using, called `cals.cfg`
```
mirv_calcs handle add key key 5;
mirv_calcs handle add activeWeapon aw key 2;
mirv_calcs vecAng add handleAttachment awm aw muzzle_flash;
mirv_calcs vecAng add handleAttachment awh aw weapon_hand_R;
mirv_calcs vecAng add or awmh awm awh;
mirv_calcs vecAng add value weaponOfs 20 0 0 0 0 179.9;
mirv_calcs vecAng add offset awmOfs awmh weaponOfs 1;
mirv_cam source calcVecAng awmOfs;
mirv_cam offset none;
spec_mode 5
```
Now I want to improve this config, but I face problems.
After cals.cfg is executed, I can't change that player number `5` to another one like `1`
I've tried to remove `key` but then it says `{key} is already in use. can't remove it `, so I went confused.

Can't find instructions or hints on Wiki so I create this issuse.

**Comment by dtugend** [comment]
mirv_calcs are designed poorly and supposed to be replaced by scripting / JIT in the future for HLAE v3.x.

mirv_calcs can only be removed in "reverse" (backwards) order they were created (meaning you have to remove them starting at the leaves of the dependency tree).

Instead it might be easier to use the editing capability of the calcs:
`mirv_calcs handle edit key key 1`

Use `mirv_calcs <calcType> edit <calcName>` to see what can be edited.

**Comment by Purple-CSGO** [comment]
thx it's done. Now it's pretty easy to use with `[` and `]`  as hotkeys. `cls` command could set the views back to normal. Though it's written with zh_CN hints, scripts could be understandable(some bind&alias). So I tag the link below.
`https://github.com/Purple-CSGO/Cfg-Preset-By-Purp1e/blob/v1.3/cals.cfg`

**Comment by dtugend** [comment]
Thanks for sharing.
