### ISSUE TITLE
Sampling System afxSampler30

### ISSUE THREAD

**Issue by robbyjm** [advancedfx/advancedfx#262]
How does the afxSampler30 work? The motion blur it produces looks really good!

**Comment by dtugend** [comment]
It computes the integral of the frame RGB pixel channels for each pixel channel using the trapezoidal integration rule.
(Edit: The integral of each pixel's chanel is normalized by a white point value (maximum value that can happen when the pixel would be white).)
The code behind is the same as in AfxHookGoldSrc, you can read more here:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ASampling-System

If you want a sampler with different settings (e.g. output FPS), use `mirv_streams settings add smapler mySampler` then use `mirv_streams settings edit mySampler` to edit it and change properties.

**Comment by dtugend** [comment]
Btw after HLAE other programs have used the same technique (but most of them only use the rectangle rule and not the trapezoidal rule):
- https://github.com/YaLTeR/hl-capture
- https://github.com/crashfort/SourceDemoRender

But it's likely that idea was used earlier by other programs than HLAE already.

**Comment by robbyjm** [comment]
@dtugend Thank you. This is exactly what I was looking for. Fantastic work!
