### ISSUE TITLE
HLAE Loader Failed | Code: 2001

### ISSUE THREAD

**Issue by lainad97** [advancedfx/advancedfx#263]
When I try launch CSGO for the first time, shows Error:
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 740
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 740
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
![1](https://user-images.githubusercontent.com/47137793/73085627-3754ee80-3ee4-11ea-88e9-ec4ff22cfcda.PNG)
![2](https://user-images.githubusercontent.com/47137793/73085628-3754ee80-3ee4-11ea-9d95-1dcfe3f02090.PNG)

**Comment by dtugend** [comment]
make sure neither HLAE.exe nor Steam.exe nor csgo.exe are set to run as admin

**Comment by lainad97** [comment]
I've just opend HLAE as admin and it does worked corectly
ty man for you help  <3

**Comment by dtugend** [comment]
that works, but would be better if you don't run any of these 3 as admin, would solve it too.
