### ISSUE TITLE
HLAE  ERROR AfxHookSource

### ISSUE THREAD

**Issue by Vossi2003** [advancedfx/advancedfx#264]
Hey guys idk what to to can you help me 

[https://imgur.com/a/hobv2ki]

**Comment by dtugend** [comment]
Your HLAE / AfxHookSource.dll you are using is either outdated (please make sure you have latest) or you are one of serveral people that have multiple CS:GO installs.

- make sure you are using latest HLAE version: https://github.com/advancedfx/advancedfx/releases/latest

- If you are using Custom Loader it's easy to select a wrong AfxHookSource.dll, please instead use File -> Launch CS:GO from the HLAE menu.

- For the latter please right click CS:GO in Steam Library -> Properties -> Local Files tab -> Browse Local Files button.
It should open Windows Explorer. Please click inside behind the folder in the "address" bar, so it will show the full path. Make sure to use the same path inside HLAE for csgo.exe. The most common path is usually: `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`.
