### ISSUE TITLE
i get only sound file ! no images...

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#268]
**i get only sound file** !!!! and demo go so fast... and no images 

i use this cfg : 

sv_cheats "1"
host_timescale 0
mirv_snd_timescale 1
mirv_gameoverlay enable 1

mirv_streams record name ztest_rec

cl_clock_correction 0
mirv_fix playerAnimState 1
mirv_streams record matPostprocessEnable 1
mirv_streams record matDynamicTonemapping 1
mirv_streams record matMotionBlurEnabled 0
mirv_streams record matForceTonemapScale 0

net_graph 0

bind f11 "host_framerate 100; host_timescale 0; mirv_snd_timescale 1; mirv_streams record start; startmovie"

bind f12 "mirv_streams record end; endtmovie; host_framerate 0"

**Comment by dtugend** [comment]
Hi. By default mirv_streams has no streams added, so you need to add them.

- If you like video tutorials, then see https://www.youtube.com/watch?v=N27MiMkafqY
- Related: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams

**Comment by dtugend** [comment]
Edit: If you don't want multiple image streams, just add this to your config insterad:

```
mirv_streams add normal myNormal
```
