### ISSUE TITLE
Render a higher resolution than screen's

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#269]
Hi
Is there a way to render in 4K (4096×2160) my CS:GO clip while my monitor's screen is at 1080p (1920×1080).
The -width & -height can not open the CS:GO window with a higher resolution than my screen.
Thanks!

**Comment by dtugend** [comment]
Hi. HLAE has not special feature for that, but you could simply use the Dynamic Super Resolution (DSR, NVIDIA) or Virtual Super Resolution (VSR, AMD) feature of your graphic card driver and use an 4K Desktop resolution with that.
