### ISSUE TITLE
Can't launch HLAE

### ISSUE THREAD

**Issue by LayonYT** [advancedfx/advancedfx#27]
![as](https://user-images.githubusercontent.com/34515653/33947616-89ff2bea-e02d-11e7-8d25-fa9b81f26349.png)
![untitled](https://user-images.githubusercontent.com/34515653/33947631-8eb9a282-e02d-11e7-8a0c-a2fd3683bacd.png)

**Comment by dtugend** [comment]
1) Make sure that no AntiCheat (ESEA Client / FaceIt / ChalengeMe.gg / ...) is running.
2) Make sure that neither csgo.exe nor Steam nor HLAE.exe are set to be launched as admin.
3) Also we recommend to use File menu -> Launch -> CS:GO instead for CS:GO.

**Comment by dtugend** [comment]
Due to lacking feedback I am closing this issue as solved.
In case it's not solved, please provide further feedback.
