### ISSUE TITLE
Помогите пожалуйста,что мне делать с ошибкой?

### ISSUE THREAD

**Issue by Meymoro** [advancedfx/advancedfx#275]
AfxError #2002: 
Название: Загрузчик не может создать запрошенный процесс.Описание: GetLastWin32Error = 5: Отказано в доступеРешение: Не забудьте закрыть античиты ESEA Client, FACEIT Client, Challengeme.gg и т.д. перед тем, как использовать HLAE.```

**Comment by dtugend** [comment]
Hi.
1) We can only help people in English on GitHub, we do not speak Russian.
2) The recommended solution is in the green box already: "Отказано в доступеРешение: Не забудьте закрыть античиты ESEA Client, FACEIT Client, Challengeme.gg и т.д. перед тем, как использовать HLAE."
3) Closing and reopning the issue will not get you a faster response.
