### ISSUE TITLE
demotick Restore/Load function

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#276]
### intro

Jumping from tick to tick and take quite some time. Often I pressed SHIFT+F2 to toggle display demoui, where I can see actual tick. I type tick number into console manually to remember. When I wanna jump, I use demo_gototick xxx.

The whole workflow can be much more minimized if there's commands to load/restore tick. We can bind keys to fast go back to where we want by just pressing keys.

### Example

just take it for example.

`mirv_demo restoretick` command to restore current demo tick, and `mirv_demo loadtick` to load and goto that tick.

It could go a bit further, like enabling several `saving points`.

**Comment by dtugend** [comment]
Closing this one, since it's a subset of demo tick store/load and `Current tick` feature #340

**Comment by Dechno1337** [comment]
Isn't this [partially] solved by the demo_index command?

**Comment by Dechno1337** [comment]
Isn't this obsolete now with CS2? 🥲
