### ISSUE TITLE
Dedicated notice area/module/bar

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#277]
### Intro

It's often hard to bind/alias commands and notice users at the same time well enough. CSGO don't support quote nesting. 

HLAE has got `mirv_exec` command to solve that problem, but printing msgs into console is not always the best way. Imagine when users press a button and open console to see msgs, close console, press another button and open again...etc.

A dedicated notice area could gain more efficiency, on top left of the screen maybe. When writing scripts we could use special commands to print msgs into `notice area`. It automatically displays on topleft. And it must support UTF-8 unicode and could be better if it uses i.e. `<` `>` `(` `)` to quote strings. Really don't want to see conflicts with original quote `""`.

Also, it could be a startpoint to build Half-Life-Advaned-Console (name it cool~) 

### Example

Print Msg
`mirv_printmsg <Hello, World!>`

Print Msg for a specific time(8s)
`mirv_printmsg <Hello, World!> 8`

Change default display time to 5s
`mirv_printmsg disptime 5`

`mirv_printmsg fontsize 18`

`mirv_printmsg color purple`

`mirv_printmsg font SC Gothic`

### Notice

notice area should be unable to be recorded in certain stream, cuz it causes issues.

**Comment by Shadoweee77** [comment]
That's somewhat posibble in source's console via vscrip library.
https://github.com/samisalreadytaken/vs_library
Other than I'd say if You would liek to deploy something of such big scale at one point it would be easier to make in as an dedicated app that can run cs inside ( or just screengrabs it) and You control everything from there and not the game.

**Comment by Shadoweee77** [comment]
Also for now You could print it into console and add developer cvar with filters to display it on top left.
Make messages printed with a prefix (HLAE_print_message) and use something like:

developer 1
con_filter_text "HLAE_print"
con_filter_enable "2";

Not the best solution but works for now.

**Comment by Purple-CSGO** [comment]
No, it does not work well.
I've tried this long time ago. messeges gonna stack in one line and need much more tricky stuff to make it somehow works a little bit.

**Comment by NESTOWL** [comment]
@Purple-CSGO 
> No, it does not work well.
> I've tried this long time ago. messeges gonna stack in one line and need much more tricky stuff to > make it somehow works a little bit.

If you really want, then you will succeed!
You just need to think a little!
I made a tool menu, which is also updated
everything is done by the standard means of the game itself!
![6Pjl8MNb4H](https://user-images.githubusercontent.com/45520187/83410039-4b72a480-a41e-11ea-99de-309965a34f02.gif)

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
