### ISSUE TITLE
Update the FAQ to be more useful to beginners

### ISSUE THREAD

**Issue by xNWP** [advancedfx/advancedfx#279]
We should probably update the FAQ: https://github.com/advancedfx/advancedfx/wiki/FAQ

It does have some good stuff there already but doesn't cover more common questions like:
- how do I get fov to work for awps/scopes
- how do I do a basic recording (from start to finish)
- how do I do depth streams
- what's the campath workflow

Also it lacks any structure in how it's written making it difficult to use. If anyone has any other common problems that should be added to the FAQ please add them :smiley:

**Comment by dtugend** [comment]
- https://github.com/advancedfx/advancedfx/wiki/Wanted
- https://github.com/advancedfx/advancedfx/wiki/_Footer/_edit
- https://github.com/advancedfx/advancedfx/wiki/Tutorials
- https://github.com/advancedfx/advancedfx/wiki/Source%3ACommands

**Comment by fj0d09r** [comment]
Regarding a basic recording, what about making something like this guide?
https://github.com/advancedfx/advancedfx/wiki/GoldSrc:First-Steps

And where would we put it? In the [AfxHookSource](https://github.com/advancedfx/advancedfx/wiki/AfxHookSource) page? or in the [mirv_streams](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams) wiki page?

**Comment by Dechno1337** [comment]
>     * how do I get fov to work for awps/scopes
Update: Added. :heavy_check_mark: 
>     * how do I do a basic recording (from start to finish)
Added: https://github.com/advancedfx/advancedfx/wiki/Your-first-recording-in-CS%3AGO :heavy_check_mark: 
>     * how do I do depth streams
mirv_streams wiki page covers that?
>     * what's the campath workflow
Added some examples to the mirv_campath wiki :heavy_check_mark:

**Comment by Dechno1337** [comment]
Added table of contents to the FAQ, Source FAQ and tutorials page :heavy_check_mark: 

Also added some common questions (and may add more). :heavy_check_mark:

**Comment by xNWP** [comment]
Closing this as the FAQ is looking much better now 😄 

Thanks so much to @Dechno1337 for his hard work, he really did all the work on everything and deserves 100% credit, thanks for all your awesome work :-)
