### ISSUE TITLE
Change color of xray elements

### ISSUE THREAD

**Issue by nielsbm** [advancedfx/advancedfx#282]
It would be great to have the ability to change the xray color ingame - mainly the teamspecific ones. If made individually for T/CT, this could be used to have them match the colors of custom HUDs better, or complete color scheme change (eg. green/red).

This would include elements such as:
- Player outline (most important) + the overhead names
- Grenade trails
- Player aim direction
- Defusekit (when dropped)

**Comment by dtugend** [comment]
- The over head names are controlled by Panorama UI in `styles\hud\hudreticle.css`, (see .playerid--team-(c)t related CSS selectors there) and since you probably already edit panorama for other stuff, I'd recommend to go that way for those.
- The rest I will check what I can do.
