### ISSUE TITLE
a new thinking to make seperate HUD

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#283]
I suddenly come across a way to make seperate HUD

That is: do not think how to separate HUD from raw game images, but how to make HUD by hlae itself

- copy paste HUD's css .... to build up a system to generate 'alpha bg' HUD:

- as the game went on, hlae somehow generate xml/json/etc files to save stats. Later we can generate HUD images/videos using these xml/json/etc files. ofc it can generate images/videos when it is recording, since now hlae can recall ffmpeg.

- Also, we can change HUD's style whatever we want.

**Comment by dtugend** [comment]
https://github.com/advancedfx/afx-cefhud-interop

**Comment by dtugend** [comment]
Closing in favour of separate related project (still under development):
-https://github.com/advancedfx/afx-cefhud-interop

Related:
- https://lexogrine.com/manager/

**Comment by dtugend** [comment]
Reopening, the browser thing is not the way to go for most plugins, it's too much dependencies and too heavy.

**Comment by dtugend** [comment]
closing in favor of #761
