### ISSUE TITLE
mirv_stream now has bug due to csgo update

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#285]
![raw](https://user-images.githubusercontent.com/47248616/75415763-87055a80-5967-11ea-9e19-2fc5bb6b8f97.jpg)

![VMandPlayer](https://user-images.githubusercontent.com/47248616/75415768-88368780-5967-11ea-85f4-22fa2ef153b5.jpg)

![wh](https://user-images.githubusercontent.com/47248616/75415770-88cf1e00-5967-11ea-8edb-df101877fdf3.jpg)

![depth](https://user-images.githubusercontent.com/47248616/75415759-840a6a00-5967-11ea-9314-195b8b7eb69d.jpg)

**Comment by dtugend** [comment]
Can you please provide a demo link?

**Comment by Purple-CSGO** [comment]
Round1 about 9500tick
using my [stream.cfg](https://github.com/Purple-CSGO/Cfg-Preset-By-Purp1e/blob/master/stream.cfg)
F1 - F4 - F7 - F6 -> pic1 2 3 4 above

<steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-yMNFe-dMJoU-mVEkX-hLE8j-dYmQD>

[download link](https://c-t.work/s/e342ce4da6ae41)
>Don't know if it works
