### ISSUE TITLE
Grey/Green And Glitchy Recordings With FFMPEG

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#286]
When recording with ffmpeg, (afxFfmpegLosslessBest) It is very glitchy and changes colors. Example: https://streamable.com/me745 . I have tried resetting my entire computer and it doesn't help.

**Comment by dtugend** [comment]
I am sorry, but the reason probably is many video editors/players can't handle rgb MP4 correctly. It's not an HLAE bug, try it in [VLC Player](https://www.videolan.org/) and it should be fine there.

You will have to use a different preset. Most video editors can handle the yuv420 one, some yuv422
