### ISSUE TITLE
``` AfxError #13:  Title: AfxHook error ``` GoldSrc 

### ISSUE THREAD

**Issue by goldsky980** [advancedfx/advancedfx#290]
![1](https://user-images.githubusercontent.com/61819318/75957252-fdbccd80-5efc-11ea-9644-29c6cd64b46d.PNG)
![2](https://user-images.githubusercontent.com/61819318/75957257-feedfa80-5efc-11ea-9c04-3822564c5e00.PNG)

**Comment by goldsky980** [comment]
what is this ..

**Comment by dtugend** [comment]
Please update your HLAE, your HLAE is outdated, newer versions have solutions recommended in the error message:
https://github.com/advancedfx/advancedfx/releases/latest

The error means:
DLL can't be found, remove DLLs and readd them and maybe check antivirus

HLAE can not run from the ZIP File, be sure to extract all files and folders.

**Comment by goldsky980** [comment]
Can you explain exactly?

**Comment by goldsky980** [comment]
Thank you very much. You're the best!!
