### ISSUE TITLE
Recording back-look [CS 1.6]

### ISSUE THREAD

**Issue by jocasrb** [advancedfx/advancedfx#293]
Is it possible to somehow record a back look of a POV demo? I have idea of doing battle runs, so having a back-view will make it more interesting

I have tryed with _mirv_cameraofs_cs_ but its not rotating camera so another command is needed, thanks in advance!

**Comment by dtugend** [comment]
Will ad a feature for this when the next HLAE version is released.
As of now you could record camera motion data and rotate all keyframes e.g. in Blender editor by 180° but that's not really convenient: https://github.com/advancedfx/advancedfx/wiki/Camera-Motion-Data

**Comment by dtugend** [comment]
ETA for release: 2020-03-14T12:00Z
If you don't want to wait you can try this DLL: [AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/4312218/AfxHookGoldSrc.zip)

Edit: mirv_cameraofs_cs has 3 new parameters, enter without parameters for help.
Edit2: `mirv_cameraofs_cs 0 0 0 0 180 0`

**Comment by dtugend** [comment]
Another hint: You can record normal view at same time and record the back view at same time:
```
mirv_movie_stereomode 1
mirv_movie_stereo_centerdist 0
mirv_movie_stereo_yawdegrees 180
```
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_movie_stereomode

**Comment by dtugend** [comment]
Ignore that stereo view comment, it was wrong.

**Comment by jocasrb** [comment]
@dtugend  Interesting, thanks, just tested it. In my case, this back-view will be used always with normal (forward view) of the demo. What do you think, is it possible to implement:

mirv_camexport_mode 4 -> so it will create current view (like mode 1) but plus that back-view, so it is like imported 'mirv_cameraofs_cs 0 0 0 0 180 0' in it...and you will have like: motion.bvh and motion-back.bvh

I hope you get what I mean :) This cameraoffset is really good, and its working well...but implementing all these as whole project is a bit....frustrating :/

**Comment by dtugend** [comment]
I think you can combine stereo recordings and mirv_cameraofs_cs to achieve what you want:

```
mirv_cameraofs_cs 0 0 0 0 90 0
mirv_movie_stereo_centerdist 0
mirv_movie_stereo_yawdegrees 90
mirv_movie_stereomode 1
mirv_camexport_mode 2
```

You can look those commands up here: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ACommands

**Edit**: Fixed mirv_cameraofs_cs values to be 90° yaw as intended and not pitch.
