### ISSUE TITLE
GoldSrc: Unable to view demos after patching with stuck fix. CL_EntityNum error.

### ISSUE THREAD

**Issue by etojuice** [advancedfx/advancedfx#299]
I'm getting this error when trying to play a patched demo (recorded on a server with maxplayers 9):
> Host_Error: CL_EntityNum: 2040 is an invalid number, cl.max_edicts is 1935

I think the solution might be to patch maxplayers and patch some *svc_* messages (not exactly sure, probably *svc_spawnbaseline*, *svc_spawnbaseline*, *svc_packetentities*, svc_deltapacketentities) in a way so non-player entities would occupy indices higher than patched maxplayers variable.

**Comment by etojuice** [comment]
I'm certain that entities are created at index starting with 10:
map: de_dust2
maxplayers: 9

> 1 player
> 10 func_breakable
> 11 func_breakable
> 12 func_breakable
> 13 func_illusionary
> 14 func_illusionary

**Comment by dtugend** [comment]
Hi. Thank you for you message and thoughts.

I am not sure if to count an best-effort fix not working as a bug (it says in the dialogue "This fix **tries** to [...] and thus **usually** fixes the problem.".

This basically is a known limitation of the fix, solving this limitation can be done by using the methods you described, however my GoldSrc demo knowledge, time and motivation is limited and the HLAE demo tools are not coded well and rather rudimentary to be honest.

Meaning while it's theoretically possible to solve the problem in many cases with the methods your described, it probably won't happen with HLAE any time soon, unless someone can help and contribute the changes required (but then again not sure why they'd not just want to make a standalone tool instead).

**Comment by dtugend** [comment]
Currently not planned.
