### ISSUE TITLE
Error - afxhooksource

### ISSUE THREAD

**Issue by levigd** [advancedfx/advancedfx#303]
https://imgur.com/a/LgvLnB4
what should I do to fix this error

**Comment by dtugend** [comment]
You probably have two CS:GO installs and are launching the older one.

To solve this you need to find the right _full_ path to the newer csgo.exe.

1. Right click CS:GO in Steam Library
2. Properties
3. Local Files tab
4. Browse Local Files button
5. Click in the top bar where it shows the shortened path in order to get the fullpath.

Use that and add `\csgo.exe` to it, so e.g. mine / the most common path is this one:
`C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

**Comment by levigd** [comment]
Yes you are right I pointed the wrong way but now there is another error
GetLastWin32Error = 5: access is Denied
Don't forget to close the anti-cheat ESEA Client, FACE IT Client, and Challenge me.gg etc. before using HLAE.
But I deleted faceit esea and their antichits a long time ago

**Comment by levigd** [comment]
```
AfxError #2002: 
Название: Загрузчик не может создать запрошенный процесс.Описание: GetLastWin32Error = 5: Отказано в доступеРешение: Не забудьте закрыть античиты ESEA Client, FACEIT Client, Challengeme.gg и т.д. перед тем, как использовать HLAE.```

**Comment by dtugend** [comment]
It can also be caused by antivirus or some other anti cheat client or permission problems.

**Comment by levigd** [comment]
All antivirus programs are disabled user with administrator rights

**Comment by dtugend** [comment]
Please right click csgo.exe and go to Properties -> Compatiblity tab, make sure nothing is ticked and press OK.
Do the same for steam.exe and for the shortcut you use to open Steam.
Close Steam / CSGO / HLAE and open it again and try again.

**Comment by dtugend** [comment]
(Btw.: Don't disable Windows Defender, it should work with HLAE when fully update.)

**Comment by levigd** [comment]
All as wrote above did the tick is not present anywhere else but the same error

**Comment by dtugend** [comment]
I think it's best if you can join the advancedfx.org Discord ( https://discord.gg/NGp8qhN ) for live chat when you have time, that way me or some other team member might be able to help solving the problem together with you.
Chances on GitHub messages are much lower for this particular problem where we tried most standard options already now.
You can try to run HLAE as admin (even though we don't recommend that), if that fixes it it's an permission problem.
It can also be other software like CCleaner that causes problems I think.

**Comment by levigd** [comment]
I would not mind but I am from Russia and my conversational level of English is quite weak

**Comment by levigd** [comment]
I understand what you are writing and what needs to be done I did it but it still doesn't work

**Comment by levigd** [comment]
I don't know why but I decided to make a custom launch and it worked without errors and if you run the cs go through then the above was thrown off

**Comment by levigd** [comment]
You can close the topic

**Comment by levigd** [comment]
But if you will fix this error please write me

**Comment by dtugend** [comment]
Please provide your custom loader settings and your File -> Launch CS:GO settings.
Asking, because they go through the same code path, so there's nothing I know of yet that I can fix.

**Comment by levigd** [comment]
![image](https://user-images.githubusercontent.com/44722334/77818336-a4eaea00-70e2-11ea-9cd4-e6737dd8d5e9.png)

**Comment by dtugend** [comment]
Can you please provide the screenshot of the other dialogue that didn't work?
(I am guessing the paths are different, but don't know.)

**Comment by levigd** [comment]
![image](https://user-images.githubusercontent.com/44722334/77818690-89cda980-70e5-11ea-80d5-6b1ebc902268.png)

**Comment by dtugend** [comment]
you forgot to append `\csgo.exe` in the top box, then it should work, can you try please?

**Comment by levigd** [comment]
Yes it does work thank you

**Comment by dtugend** [comment]
Glad it could be solved.
