### ISSUE TITLE
player model shadows not visible on mirv_streams world layer

### ISSUE THREAD

**Issue by filiperino** [advancedfx/advancedfx#304]
When previewing the world stream with playerModelsAction set to noDraw, the shadows on player models appear only upon death or not at all. Tested on 3 different computers, so that's why im reporting it.

myWorld preview: https://i.imgur.com/BROHoHA.jpg
normal stream: https://i.imgur.com/5Eqr3Z7.jpg

HLAE Version: 2.91.3.1
CSGO Version: Latest update as of 3/28/2020

**Comment by dtugend** [comment]
You can restore the old behavior as follows:
```
mirv_streams edit myWorld actionFilter addEx "shader=DepthWrite" "isPlayer=1" "action=draw"
mirv_streams edit myEntity actionFilter addEx "shader=DepthWrite" "isPlayer=1" "action=noDraw"
```
We will discuss and consider restoring the old behavior by default in the HLAE team.

----

The other most notable change is weapons carried by players, if you need to change them, here is how the current afx/wh.cfg detects them (replace stream name `afxWh` and change to desired action (e.g. `noDraw` or `draw`):
```
mirv_streams edit afxWh actionFilter addEx "name=models/weapons/w_models/arms/\*ct_\*" "action=afxWhCT"
mirv_streams edit afxWh actionFilter addEx "name=models/weapons/w_models/arms/\*t_\*" "action=afxWhT"
mirv_streams edit afxWh actionFilter addEx "name=models/weapons/\*" "action=afxWhWeapon"
mirv_streams edit afxWh actionFilter addEx "className=weapon\*" "action=afxWhWeapon"
```

**Comment by filiperino** [comment]
Thank you for your reply. will add it to my cfg, much appreciated!

**Comment by dtugend** [comment]
Can I reopen this issue or do I need to make a new one?

**Comment by filiperino** [comment]
Yeah, sorry

**Comment by dtugend** [comment]
No need to be sorry, sorry if it sounded harsh or something, wasn't intended that way :)
