### ISSUE TITLE
mirv streams with reshade

### ISSUE THREAD

**Issue by Aves31** [advancedfx/advancedfx#306]
I saw that there are such closed questions, but I still did not understand if there is such an opportunity to use reshade effects with starmovie? when I start recording in layers everything remains the same. I read this answer # 229 and in that video it is not shown how recording down layers and effects from reshade. can you  tell some commands or help me something?

**Comment by dtugend** [comment]
Please make sure to also read the [video's](https://www.youtube.com/watch?v=oBU9z75gTFg) comments
> Note: To record ReShade with the "startmovie" command, you need to set mat_queue_mode to -1, mirv_streams won't work with ReShade.

**Comment by Aves31** [comment]
Okay,thank you

**Comment by dtugend** [comment]
I meant description sorry.

**Comment by Aves31** [comment]
I realized already, it’s sad anyway that there is no such possibility :(

**Comment by dtugend** [comment]
(startmovie itself should work, only multiple streams / layers with mirv_streams will not.)

**Comment by dtugend** [comment]
[Older Integrating mirv_streams and Reshade feature request](https://github.com/advancedfx/advancedfx/issues/63)
