### ISSUE TITLE
Virus detected in 2.44.2

### ISSUE THREAD

**Issue by whpb** [advancedfx/advancedfx#31]
When I try to download the latest version (2.44.2) windows defender cancels the download, and flags a trojan called Azden.A!cl

**Comment by dtugend** [comment]
Please use the previous version [HLAE 2.44.0]( https://github.com/advancedfx/advancedfx/releases/tag/v2.44.0) until the issue is resolved, the new version is only required if you need the latest AGR updates.
I contacted Microsoft Defender team regarding the issue, but that might take a while.

**Comment by dtugend** [comment]
The issue has been resolved it seems.
If you still have the issue, please make sure your Windows Defender definitions are up to date (check for Windows updates).
If that still doesn't solve the issue, please report it here.
Thank you.
