### ISSUE TITLE
Editing the CS:GO panorama interface

### ISSUE THREAD

**Issue by tabam1** [advancedfx/advancedfx#311]
Hello, is it currently possible to edit the panorama interface in CS:GO ? I want to edit only the panorama menu, remove unnecessary things, change colors etc.

**Comment by dtugend** [comment]
Panorama UI can be edited when using HLAE by editing XHTML / CSS files: https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI

However it works only when launched from HLAE with the right parameters, meaning not suitable for normal gaming.

**Comment by tabam1** [comment]
yes, but now the panorama works only thanks to the code.pbin file, which cannot be modified, i.e. uploading folders generated by half is useless, am I wrong?

**Comment by tabam1** [comment]
lol, this is weird but its working, big thanks

**Comment by tabam1** [comment]
Its possible to edit this file: ItemModelPanelCharWeaponInspect.res ?

**Comment by dtugend** [comment]
This file is not part of Panorama UI.
It's contained in `root\resource\ui\econ\itemmodelpanelcharweaponinspect.res` inside `pak01_pak.dir`.
While there's several options to edit pak files, I think the best option is to use MIGI instead:
- https://www.reddit.com/r/GlobalOffensive/comments/adlo6y/migi_the_ultimate_tool_to_load_and_combine_mods/

MIGI can be used together with HLAE in case you still need it.

**Comment by tabam1** [comment]
it's harder to do than write about it: D

**Comment by dtugend** [comment]
Hint: Some colors are also in `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\resource\csgo_english.txt`
