### ISSUE TITLE
Is possible to edit Killfeed (Kill Notification bar) ?

### ISSUE THREAD

**Issue by nutellazpw** [advancedfx/advancedfx#312]
Hello,
is possible to edit design of killfeed bar with HLAE , like here for example - https://prnt.sc/roxuac

Thanks !

**Comment by dtugend** [comment]
I answered that in Discord already:
- The screenshot you are referring to is an external CS:GO HUD overlay, it's not done by editing Panorama UI / no HLAE needed. (Example: https://github.com/osztenkurden/CS-GO-Observer-Custom-HUD, but there's others.)
- And yes you can edit it by changing Panorama UI files (https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI) but it won't be easy to achieve the same or a similar result as on the screen.
