### ISSUE TITLE
error mirv_streams! HELP ME!

### ISSUE THREAD

**Issue by ON1KSeo** [advancedfx/advancedfx#315]
layer error entity, models, weapons(greenscreen).
its entity layer.

where is the green background????????

![00000](https://user-images.githubusercontent.com/63420605/78927375-7a683c00-7aa7-11ea-9926-b4fdec3be7f1.png)

**Comment by dtugend** [comment]
Hello.

Please move HLAE folder into a location without special characters in the name (e.g. C:\HLAE).
Other option is to use HLAE_Setup.exe which enforces this.

**Comment by ON1KSeo** [comment]
> Здравствуйте.
> 
> Переместите папку HLAE в папку без специальных символов в имени (например, C: \ HLAE).
> Другой вариант - использовать HLAE_Setup.exe, который обеспечивает это.

Thank u, i go try
