### ISSUE TITLE
Hlae problems

### ISSUE THREAD

**Issue by lida474** [advancedfx/advancedfx#316]
Why do I look at reviews of this program and there it takes screenshots , and I take pictures in BVH format what to do.

**Comment by dtugend** [comment]
I think good idea could be to watch some video tutorials first, since HLAE is not very beginner friendly:
https://www.youtube.com/watch?v=x_gPlgkmdRI&list=PLkBtoHVFgchy0ULyuXckfvvi7HD5DiR_R
