### ISSUE TITLE
Unbind leftarrow/rightarrow from nextplayer/prevplayer

### ISSUE THREAD

**Issue by nthnwllms** [advancedfx/advancedfx#318]
It seems that since Panorama UI release, leftarrow and rightarrow are bound to switch to next player and previous player. Something that might be useful to look into since 99% of time spent using HLAE is in a replay and arrow keys are pretty useful

mirv_fix unbind_spectator_arrowkeys?

**Comment by dtugend** [comment]
would
mirv_bind key "commands"
be acceptable instead?

**Comment by nthnwllms** [comment]
Whatever you think makes the most sense. I wouldn't mind using mirv_bind key for the arrow keys. Does it serve a purpose other than overriding those valve default bindings?

**Comment by dtugend** [comment]
It could serve other purposes, e.g. allowing to rebind mirv_input and other stuff if designed properly, but the main purpose would be to over-come forced CS:GO bindings.

**Comment by nthnwllms** [comment]
That makes a lot of sense and sounds like a good solution. I like this idea :)

**Comment by dtugend** [comment]
@nthnwllms Is this problem still sort of in CS2, or we can close this issue?

**Comment by nthnwllms** [comment]
Just tested and the issue has become more weird now...

The issue only occurs if the key is bound. If leftarrow and rightarrow are left unbound, it does not swap players. When I bind them to a command (in my test, I created a bind to toggle the spectator xray on/off), only then does it start swapping players, but also inputs my command. Unbind the key and it stops swapping players.

To reproduce...
1. Load a replay
2. Use console `unbind leftarrow` `unbind rightarrow` - Now they should not switch players when in first person mode
3. Use console to `bind leftarrow slot1` - You will see that left arrow now switches between players in first person mode

Up to you and other users if this is important and worth the effort. Like I mentioned to you personally, I don't work on CS stuff at the moment, but I do think arrow keys are nice to be able to use with HLAE.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
