### ISSUE TITLE
Freecam in demo

### ISSUE THREAD

**Issue by adamoumouid** [advancedfx/advancedfx#319]
Hello
I have installed hlae for doing a cinematic and when I use the mouse wheel for go in freecam mod it not work.
Can you Help me please!

Thanks ;)

PS: sorry if it have dôme postale but I am french ans I am 12 years old ;)

**Comment by dtugend** [comment]
If you are in `mirv_input camera` mode the mousewheel might be bound to something else depending on your settings and might be not available for normal use.

You can end mirv_input camera mode by either pressing ESC while in-game or entering `mirv_input end`.

If you are using CS:GO, you can also switch to thirdperson in GOTV demos by entering `spec_mode 6` into console.

**Comment by adamoumouid** [comment]
I tryed to reset m'y controles settings ans I try `mirv_input end` ans et not work but thanks you

**Comment by dtugend** [comment]
I didn't 100% understand the problem to be honest, so went for the most likely problem.

Can you describe:
1) What you do.
2) What you expect.
3) What happens instead.
Please?

**Comment by adamoumouid** [comment]
Ok will use Google trad for explain me

**Comment by adamoumouid** [comment]
I try to do a kinematics on cs: go with HLAE but I can't get to freecam mode to be free to place the "campath"

**Comment by dtugend** [comment]
You need to enter `mirv_input camera` and then can use the keys described here:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_input

Maybe also search for "mirv_campath" on YouTube, some of those tutorials there are okay / good.

**Comment by adamoumouid** [comment]
Ok I will try so thanks you :)

**Comment by adamoumouid** [comment]
Can we Switch to freecamera out of GOTV
But I have recorded demo ans I have wroten `demoui` in the console

**Comment by dtugend** [comment]
To be honest I didn't understand what you said, can you try to rephrase it with different words?
