### ISSUE TITLE
Permission?

### ISSUE THREAD

**Issue by P0is0NisHere** [advancedfx/advancedfx#32]
When i drag the AfkHookSource.ddl and press ok , it tells me that i need permission from the administrator to use that

**Comment by dtugend** [comment]
Please provide more info about the operating System etc. you are using.
For example HLAE will not work on Windows S: https://support.microsoft.com/en-us/help/4020089/windows-10-s-faq

**Comment by dtugend** [comment]
Due to lacking feedback I am closing this issue as solved.
In case it's not solved, please provide further feedback.
