### ISSUE TITLE
HLAE plugin Interface requests

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#322]
These following interfaces are requested for developing GUI plugins for HLAE:
- [ ] Execute commands to csgo console √
- [ ] After executing certain commands, Get feedback msgs from csgo console 
- [ ] Get msgs from csgo console
- [ ] Get players' info(i.e. steamid) through Index(0~9)
- [ ] Get current demo's filepath
- [ ] Get current status of mirv_steams / streams' record settings / voice block settings / deathnotice highlight settings etc...

 ----

 Edit by @dtugend:
-  https://github.com/advancedfx/advancedfx/issues/322#issuecomment-1463760665

**Comment by dtugend** [comment]
@Purple-CSGO 

What's the difference between "After executing certain commands, Get feedback msgs from csgo console" and "Get msgs from csgo console" (it's not really safely possible to tell which command caused which message in console).

**Comment by Purple-CSGO** [comment]
> @Purple-CSGO
> 
> What's the difference between "After executing certain commands, Get feedback msgs from csgo console" and "Get msgs from csgo console" (it's not really safely possible to tell which command caused which message in console).

For example, I wanna get feedback msgs from executing `voice_show_mute`, then it should a 1 -> 1 relation. Getting such responses through filters does not sound like a good idea.

Ofc hlae could choose to expose commands and their feedbacks through return values, or a value in a form of struct or json string, but it increases the burden of dealing with all commands.

> As to `(it's not really safely possible to tell which command caused which message in console).`

if it's not safe enough, is it possible to divide msg into parts or blocks or whatever, making it easier to distinguish which part/block of msg comes from which command through sth. like regex?

**Comment by DuKeM-CSGO** [comment]
The following features are requested.

Base
- Available interfaces for C++23.
  - Common runtime info. e.g., path to `hlae.exe`, dlls and `csgo.exe`.
  - System info. e.g., win7 / win10 / linux (if the core could run)
- Update checking (Something like nskinz's one). Both hlae and plugins.
- Undo / redo. History list including all operations of plugins.
- Macro. Seems like cfgs but it saves operations of (even different) plugins, then loads.

Communication
- With the core, and then the game:
  - Version of core. 
  - List of installed(?) plugins. A plugin could check if its dependence is installed.
  - The state of core and other plugins, e.g. 
  - Game console. _Not recommended to receive its output text; just send messages._
  - Engine convars. Read them and modify.
  - Engine hooks.
  - Game state, e.g., main menu / demo / match (for live).
  - Match state, e.g., demo info / `mirv_listentities`
- With another plugin, even it's from another author.
- With another process, e.g., `mirv_pgl`. Both raw data and drawing tasks.

GUI
- Custom GUI design. (Something like Blender's one)
- Standard file explorer of the os.
- Receive user input from keyboard, mouse and others. e.g., joystick or touchpad. They should be modifiable for the user.

_Some things are features of the core, not the interfaces themselves. Talk about the core next time._

**Comment by dtugend** [comment]
Closing this in favor of #228 
Thank you all for your input.
