### ISSUE TITLE
recordWeapon not recording spectated player

### ISSUE THREAD

**Issue by Devostated** [advancedfx/advancedfx#325]
A few people reported to me that the weapon of the spectated player is not being recorded, but the player is.
I thought it's a pov demo problem, but it's not. I tried an official mm demo myself.
Seems like it's only the weapon and nothing else missing.

Commands in use:

host_timescale 0
host_framerate 30
mirv_streams record agr enabled 1
mirv_streams record agr recordPlayers 1
mirv_streams record agr recordCamera 1
mirv_streams record agr recordInvisible 1
mirv_streams record agr recordWeapons 1
mirv_streams record agr recordProjectiles 0
mirv_streams record agr recordViewmodel 1

**Comment by dtugend** [comment]
- please elaborate on "spectated" in GOTV
- 1st person or 3rd person weapon model?

**Comment by dtugend** [comment]
> spectating in gotv: watching the player you want to record in first person
> the thirdperson gun is missing 
> even tho record invisible and record weapons is enabled

I will try to look into it when having time, but cannot promise I'll manage to find a good solution.
While it's unexpected behavior (people might think recordInvisible will record it), it's might be technically accurate.
