### ISSUE TITLE
Inferno afx/wh white floor bug

### ISSUE THREAD

**Issue by Ariotegar** [advancedfx/advancedfx#328]
I don't know why, but this just happened so suddenly. i've recorded the same demo 1 month ago and it was normal. but now it has this white floor. which ruins the wallhack effect

Now
![same1](https://user-images.githubusercontent.com/43881983/82287553-a641e000-99ca-11ea-8ae0-ba1767e76b11.PNG)

30 days ago
![same2](https://user-images.githubusercontent.com/43881983/82287563-acd05780-99ca-11ea-89b8-b4563dd76e22.PNG)

Does anyone have a workaround for this?

**Comment by dtugend** [comment]
Hi, as a workaround please execute/enter these in console after loading afx/wh.cfg, until an HLAE update is released (then do not use them anymore):
```
mirv_streams edit afxWh actionFilter remove 1
mirv_streams edit afxWh actionFilter addEx "name=dev/\*" "action=noDraw"
mirv_streams edit afxWh actionFilter addEx "shader=Sky_HDR_DX9" "action=afxWhBlack"
