### ISSUE TITLE
Command value changer between certain ticks.

### ISSUE THREAD

**Issue by dReaMLike1337** [advancedfx/advancedfx#329]
Is it possible to make a function that smoothly changes command values between certain ticks
example: from tick100 to tick200 the value of viewmodel offset X changes from -1 to 1 smoothly
in this case those are 100 ticks difference , and from -1 to 1 that will be 0.04 value change per tick
and instead of putting the commands for each tick in the demoplayback options , it does it automatically.

**Comment by dtugend** [comment]
Please review https://github.com/advancedfx/advancedfx/releases/tag/v2.96.0

**Comment by dReaMLike1337** [comment]
Thanks so much man !!!
Can't wait to try this.

EDIT: Works perfecty so far!
