### ISSUE TITLE
[Texture Streaming Beta] HLAE error when launching CS:GO

### ISSUE THREAD

**Issue by Dechno1337** [advancedfx/advancedfx#330]
![image](https://user-images.githubusercontent.com/40070135/82729795-9859cb00-9cfa-11ea-8d0b-113a260d3313.png)

HLAE still manages to inject successfully though, for now. :smiley:

**Comment by dtugend** [comment]
This was fixed in code already: https://github.com/advancedfx/advancedfx/commit/177fcd90bd3dfd51aa5ab79c6392e3859503ddee

Just waiting for update or new HLAE release, whatever happens first.
