### ISSUE TITLE
HLAE should have a proper log file.

### ISSUE THREAD

**Issue by Shadoweee77** [advancedfx/advancedfx#331]
HLAE should get a proper log file for trouble shooting. At every star up it should log stuff like:

1. Version of HLAE and Game
2. Devices connected as they can sometimes cause trouble
3. Method of recording ( FFMPEG, streams, etc )
4. Amount and type of errors.
5. Other stuff like - Was mirv_pgl used etc.

**Comment by cherinyy** [comment]
I urgently need this log. I don’t know why CS:GO will not respond as soon as I start recording the stream.
![csgo](https://user-images.githubusercontent.com/9050713/86532951-46fb4900-bf00-11ea-9ef2-e0fdf116074d.png)

When I removed FFmpeg, it seemed to work fine.
So it seems to be a problem with FFmpeg, but I don’t know what caused the problem.
![ffmpeg](https://user-images.githubusercontent.com/9050713/86533059-0223e200-bf01-11ea-99da-26968ada7050.png)

I completely wrote the cfg file according to the reference parameters on the Wiki.
![cfg](https://user-images.githubusercontent.com/9050713/86533119-62b31f00-bf01-11ea-83fe-d7a65891433e.png)

**Comment by dtugend** [comment]
It can be caused by some Anti-Virus software that blocks or alters stdin / stdout (standard input/output) between HLAE and ffmpeg.exe.

**Comment by dtugend** [comment]
Not a fan of this feature to be honest.
If we do it, it must be off by default and completely optional.

**Comment by dtugend** [comment]
If anyone has good suggestions on how to do a good logging system in Rust (considering there will be multiple processes and threads and maybe even remote endpoints over network in HLAE 3), please let me know.

**Comment by dtugend** [comment]
- https://docs.rs/log/latest/log/

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
