### ISSUE TITLE
Camera smooth cinematic starts earlier then supposed to.

### ISSUE THREAD

**Issue by zarakenn** [advancedfx/advancedfx#332]
Hello, so basically after i record the cinematic (mirv_input camera) and and enable it, whenever i try to go back in the demo in order to watch it, it starts earlier by random seconds time sometime 10 secs earlier other times 5 and so, it's really frustrating.

**Comment by dtugend** [comment]
Please check if you have mirv_time in your movie making config or are using it.
If so, please remove it / stop using it.

If unsure how mirv_time works, please don't use it: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_time

Edit:
Also if you are using mirv_campath edit start, be aware edit sets a new start time to the _current_ time.

**Comment by zarakenn** [comment]
Thank you very much, it actually worked and everything is back to normal!
