### ISSUE TITLE
Timelapse Feature for Mirv_Time Command

### ISSUE THREAD

**Issue by Twissen** [advancedfx/advancedfx#334]
Also, I found this video and while I was watching I noticed that he speeds up the game with the "host_timescale" command and he creates timelapses. I know, that way wouldn't work for demos. Because it also would speed up the campaths but is it possible to implement this feature for mirv_time? Kinda like campaths have their own time scales.
[https://www.youtube.com/watch?v=OMPB66xespA](url)

**Comment by Dechno1337** [comment]
One way to make a timelapse is to simply make the campath last longer? Depending on the effect you want to achieve, it might be enough to record in 30-60 fps (if disk space is an issue) and then speed it up in post.

**Comment by Twissen** [comment]
Yes. You can make that way too. But the point is to make everyone's life easier, right? Also, that's the main reason why HLAE exist in the first place. So, it's just a feature that I would love to see in the future if possible.
