### ISSUE TITLE
Can't load demos

### ISSUE THREAD

**Issue by ShreKyy** [advancedfx/advancedfx#335]
So I was trying to load a demo and it redirected me back to the dashboard after 2 seconds,then I tried installing the latest version of hlae,and the issue persisted.It was working fine a week ago,not sure what is causing the problem.Need to fix it ASAP

**Comment by dtugend** [comment]
make sure to use playdemo with quotes:
e.g. `playdemo "demo name.dem"`
or `playdemo "replayes/replay demo name.dem"`

**Comment by ShreKyy** [comment]
I use shift+f2 and go to load and then select the demo,isnt that right?

**Comment by dtugend** [comment]
it should work yes, unless the demo is broken.
Set `developer 2`
and check for messages (warnings / errors) after loading the demo in the console.

**Be aware that CS:GO must have internet access and not be in off-line mode in case that (e.g. due to update) it has to download a past version of the map used in the demo, or it will fail as well.**

**Comment by ShreKyy** [comment]
I think its the demos,I cant even open them in regular csgo,and in the console it says this 

Weird RouterPingReply timestamps from canu#153 (157.255.37.16:27059).  Reply contained 2125392704, current is 2140361659 (elapsed 14968955)

Weird RouterPingReply timestamps from pwu#69 (61.182.135.16:27029).  Reply contained 2123870638, current is 2140362044 (elapsed 16491406)

**Comment by dtugend** [comment]
These messages are sadly not related.
Have you made sure that csgo.exe can download old map versions if required as said above?

**Comment by ShreKyy** [comment]
I'm not quite sure what you mean if csgo.exe can download old map versions

**Comment by dtugend** [comment]
The game updated.
The map used in the demo might have updated too by now and the demo now uses an older "version".
So the game will try to download the older version of the map so you can still view the demo.
However if that download fails, it will behave too as you described.

**Comment by ShreKyy** [comment]
Ohh,I understand,alright I'll talk to the guy that sent me the demos,thanks man :)

**Comment by ShreKyy** [comment]
and what should I do to get the demos working?

**Comment by dtugend** [comment]
Try if you can install a map from Workshop in CS:GO, if that works the demo download should work too usually.
Also make sure these are correct:
```
cl_allowdownload 1
cl_download_demoplayer 1
```

If all that doesn't help, consider to upload a demo on https://send.firefox.com and send me the link at contact@dtugend.com.

I will try to have a look, but if the demo is really broken then there's not much I can do.

**Comment by ShreKyy** [comment]
But what if I downgrade the version of csgo and hlae,will it work then?

**Comment by dtugend** [comment]
I don't know - if you manage to get the previous version, might be worth a try.
(Btw. latest HLAE also works with previous CS:GO version.)

**Comment by ShreKyy** [comment]
alright then I'll give that a shot,but I dont really know yet how to get the previous version of csgo xd

**Comment by dtugend** [comment]
![image](https://user-images.githubusercontent.com/3610128/83129486-2cea7180-a0dd-11ea-9b8f-a4f167d86c22.png)
Select 1.37.5.2 on betas tab.

**Comment by ShreKyy** [comment]
alright and do I have to type some sort of code in there?

**Comment by ShreKyy** [comment]
I've launched the game in 1.37.5.2 and demos still dont load :x

**Comment by dtugend** [comment]
> If all that doesn't help, consider to upload a demo on https://send.firefox.com and send me the link at contact@dtugend.com.
>
> I will try to have a look, but if the demo is really broken then there's not much I can do.

**Comment by dtugend** [comment]
I don't know if this is solvable at all, but I didn't get a demo from you, so closing this for now.
