### ISSUE TITLE
Add numbers animation points

### ISSUE THREAD

**Issue by NESTOWL** [advancedfx/advancedfx#338]
It is necessary to add a display of the numerical sequence of camera points.
When creating a complex camera path, you often have to remove unsuccessful(bad/wrong) camera movement points.
In order not to count it manually — we want each camera point to display their numerical number.
![Без имени-1](https://user-images.githubusercontent.com/45520187/83145574-a85c1b00-a0fd-11ea-9955-fef2ff7e1072.jpg)
Also, to be able to **enable/disable** the display of this function.
**Example command:** `mirv_campath showPathNumbers 0|1`

**Comment by Shadoweee77** [comment]
Wouldn't dispalying a tick be better? Since ticks only grow - it would be easy to see which anchor is newer and also display tick which could be usefull for timing stuff.

**Comment by NESTOWL** [comment]
> Wouldn't dispalying a tick be better? Since ticks only grow - it would be easy to see which anchor is newer and also display tick which could be usefull for timing stuff.

@Shadoweee77 I would not refuse such a thing!
A better way is to display the point number and tick
and it would be nice to be able to include this separately

**Comment by Dechno1337** [comment]
> Wouldn't displaying a tick be better?

Well, when selecting keyframes, it would be useful to know their id.

**Comment by dtugend** [comment]
Please review the feature in HLAE v2.98.0 (mirv_campath draw keyIndex, default 0.618, 0 to disable), since I want to add it the same to GoldSrc if it's okay enough.

**Comment by NESTOWL** [comment]
@dtugend Fine!
Maybe it's better to remove the black background?

**Comment by NESTOWL** [comment]
@dtugend  **Nice, it works, thank you!**
![image](https://user-images.githubusercontent.com/45520187/83915526-15b22080-a77c-11ea-9c64-be9fb2002cd1.png)
