### ISSUE TITLE
demo tick store/load and `Current tick` feature 

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#340]
https://github.com/advancedfx/advancedfx/releases/tag/v2.96.0

In this pre-release page, I could see the possibilities of making more advanced things.

- add current tick command or feature like xTrace, for example , replace 5000 with CurrentTick
```
// When it's around the start tick of recording
mirv_cmd addAtTick CurrentTick "demo_resume;mirv_streams record start"
// When it's around the end tick of recording
mirv_cmd addAtTick CurrentTick "demo_pause;mirv_streams record end"
```
- add tick store and load feature
`mirv_tick_store A` `mirv_tick_store B` etc...

After aliasing & binding to commands like this, recording(with hlae) could be much more automatic. It's like pressing the i for `in` and o for `out`, j for `jumping to 200tick before start tick`. then resume the demo, recording job gets automatically done.

And it's easier for plugins to realize `auto-record` function , although there's demos manager that could do this.

## See also
- demotick Restore/Load function #276

**Comment by dtugend** [comment]
There's already
mirv_cmd add - for current time
mirv_cmd addTick - for current tick
and mirv_cmd save / load as well.

The mirv_tick_store is an feature request of course and not possible with HLAE itself yet I think.

**Comment by dtugend** [comment]
Hi after re-reading it seems the only thing missing is what was described in #276 separately, so I am closing this one in favor of the other one, since all other bases are covered.
