### ISSUE TITLE
how to disable weapons sound !!!

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#341]
is there any command to disable or decrease weapon sounds 
i played demo(faceit)...i want to record voice but because guns and nades cant hear shit ....
i hope u understand what i mean ! :p

**Comment by dtugend** [comment]
Recommended way: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_voice
Other ways: https://github.com/advancedfx/advancedfx/wiki/Source:mirv_snd_filter

**Comment by iqhl** [comment]
thnk u so much
so there is no command for weapon sounds ! ??

**Comment by NESTOWL** [comment]
@iqhl 🤦🤦🤦

**Comment by dtugend** [comment]
> i want to record voice but because guns and nades cant hear shit

First page I linked with mirv_voice handles exactly that.

>so there is no command for weapon sounds ! ??

On the second page linked there's commands by Valve listed for mixers / mixlayers, which allow exactly that.
