### ISSUE TITLE
How is the sky change for 2020?

### ISSUE THREAD

**Issue by M5TF** [advancedfx/advancedfx#344]
Hello guys, can you help me with this?

**Comment by Dechno1337** [comment]
This tutorial should still work?
https://github.com/advancedfx/advancedfx/wiki/Tutorial%3A-CS%3AGO%3A-Replace-sky-with-mirv_streams-on-nuke---inferno---train
Or is there any problem with it?

**Comment by M5TF** [comment]
Do you have a youtube tutorial video about it?

**Comment by M5TF** [comment]
Do you have a youtube tutorial video about it?
