### ISSUE TITLE
HLAE Error Loader failed. Code: 2001

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#345]
System.Runtime.Serialization.SerializationException: End of Stream encountered before parsing was completed.
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at advancedfx.injector.interop.Formatter.System.Runtime.Serialization.IFormatter.Deserialize(Stream serializationStream)
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

I don't have any anti-cheat running. I have .NET Framework 4.8, Windows 10 and the newest Steam version (not the beta). I also have specified the correct patch becouse the game launches. Just the commands don't work.

**Comment by dtugend** [comment]
Which AntiVirus do you use?
Sometimes you need to add an exception for both HLAE.exe and the injector.exe (there's two injector.exe, one should be next to HLAE.exe and the other one in x64 sub-folder).
Edit: Also make sure to use latest HLAE please.

**Comment by ghost** [comment]
> 
> 
> Which AntiVirus do you use?
> Sometimes you need to add an exception for both HLAE.exe and the injector.exe (there's two injector.exe, one should be next to HLAE.exe and the other one in x64 sub-folder).
> Edit: Also make sure to use latest HLAE please.

right now i'm using WINdefender and Comodo which is disabled, but i'll try to add it in a minute or tommorow and i'll give a reply.

**Comment by dtugend** [comment]
If you mean Windows Defender, please make sure the definitions are fully updated, then at least Windows Defender will be fine.
HLAE had problems with Comodo in the past, especially it's behavior blocking and stuff.

**Comment by ghost** [comment]
> 
> 
> If you mean Windows Defender, please make sure the definitions are fully updated, then at least Windows Defender will be fine.
> HLAE had problems with Comodo in the past, especially it's behavior blocking and stuff.

yeah Windows Defender... I'll add these files to trusted files in Comodo tommorow. I mean I disabled it so it doesn't run it in sandbox. Ok, we'll C tommorow.

**Comment by ghost** [comment]
> If you mean Windows Defender, please make sure the definitions are fully updated, then at least Windows Defender will be fine.
> HLAE had problems with Comodo in the past, especially it's behavior blocking and stuff.

It still pops out 😞 Once Comodo blocked Terraria from Steam hahahah

**Comment by ghost** [comment]
guess i'll need to uninstall it

**Comment by ghost** [comment]
and so I downloaded it only for the sandbox

**Comment by ghost** [comment]
tysm for help it works now <3
