### ISSUE TITLE
Track player velocity 

### ISSUE THREAD

**Issue by dPexxIAM** [advancedfx/advancedfx#346]
Could an option be added to show the player's velocity? This would be ideal for making surf/bhop movies.

example of how it looks:
https://www.youtube.com/watch?v=3PXfBfFywFs

It was implemented into a similar program here; https://github.com/crashfort/SourceDemoRender/commit/9c0275fddc2eac3aae1e8e4aa3066158d3629ab9

**Comment by Shadoweee77** [comment]
cl_showpos 1 does it technically, but not in a nice way

**Comment by dtugend** [comment]
This probably won't be implemented too soon, but of what is velocity measured? The player eye origin or the player origin (relevant when ducking a lot e.g.)? (This and other (e.g. over which time it is smoothed) information could help later with coding this.)

Edit: It measures the entity abs velocity from the engine (meaning from player origin)
https://github.com/crashfort/SourceDemoRender/blob/f17f8de677cf0b2cc98f5582fb565a25274351ff/projects/svr_game/src/arch_000_source_1_win.cpp#L155

**Comment by ghost** [comment]
Would like this as well, only thing keeping me to switch from SDR

**Comment by dtugend** [comment]
Which games besides CS:GO would be needed?

Also please note that SDR is still faster than HLAE with FFMPEG, because it samples and encodes video on the GPU.

**Comment by dPexxIAM** [comment]
> Which games besides CS:GO would be needed?
> 
> Also please note that SDR is still faster than HLAE with FFMPEG, because it samples and encodes video on the GPU.

Any game which has any sort of movement game mode/community.

Namely, CS:S, MoM, TF2.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
