### ISSUE TITLE
injector.exe is showing a virus

### ISSUE THREAD

**Issue by finlaywebster** [advancedfx/advancedfx#348]
when i use the software my antivirus (avast) blocks the file injector.exe it says it contains IDP.generic and trojan files this is only since the newest update of HLAE please can you help me as i dont want to infect my computer.

**Comment by Dechno1337** [comment]
I also use Avast and almost every single new HLAE version triggers Avast. But it only takes their lab 5-60 minutes to scan it themselves and find nothing.

**Comment by dtugend** [comment]
We recommend to contact Avast as Dec described and have them look at the file.

If you downloaded from the official location ( https://github.com/advancedfx/advancedfx/releases / https://www.advancedfx.org/download/ ), then you should be fine usually, at least we don't deliberately put bad stuff inside.
