### ISSUE TITLE
HLAE doesn't work when launching CSGO

### ISSUE THREAD

**Issue by nedassicus** [advancedfx/advancedfx#350]
I get this Error AfxHookSource message when I try to start CSGO. Updating to newer version doesn't help, the issue still remains. Please help someone.
https://imgur.com/a/YHsG5jJ
Thanks!

**Comment by Dechno1337** [comment]
Are you using version 2.100.**2**?
The _changelog.xml_ file inside the HLAE folder can tell you which version you are using.

**Comment by nedassicus** [comment]
> Are you using version 2.100.**2**?
> The _changelog.xml_ file inside the HLAE folder can tell you which version you are using.

Yes, the version is 2.100.2

**Comment by Dechno1337** [comment]
After you close the error message, does CS:GO still launch / are you still able to get in-game?

**Comment by nedassicus** [comment]
Yes, my bad. I thought that if I get this message, the program won't work, but I checked it, everything works fine. Thanks. Closing the issue

**Comment by dtugend** [comment]
You might want to check if you are one of those people that end up with two CS:GO installs after a while. This could explain why your CS:GO and HLAE version don't fit each other, since the 2.100.2 fits the latest CS:GO version.
Also check for updates / verify CS:GO game cache.
