### ISSUE TITLE
[Feedback] HLAE_Setup.exe / Installer

### ISSUE THREAD

**Issue by Dechno1337** [advancedfx/advancedfx#351]
1. [x] When installing HLAE for the first time, there should be enough room to put the installation path in the "main" window, without having to find the [Options] button? Or alternatively you could add a [Next] button that continues to another window with the installation path before the user can install the software?

2. [x] Why is there a checkbox for "License terms and conditions" when there isn't even any link or explanation of said terms? :frowning: 

3. [x] When uninstalling HLAE, what about options to delete the HLAE appdata folder <strike>+ mm cfg? The hlaeconfig.xml file has the file path to the mm cfg if enabled. I guess the problem would be if the user has set an mm cfg but not using _remember my changes_? :thinking: </strike>

**Comment by dtugend** [comment]
Edited your post, removing mmcfg folder is beyond what we should do, it's dangerous, since people tend to set all kinds of folders there.
