### ISSUE TITLE
problem in c:\source\advancedfx\AfxHook\addresses.cpp:796?

### ISSUE THREAD

**Issue by stereo1029** [advancedfx/advancedfx#352]
I've looked around for a fix, but all I could find is people saying to update. I'm on the latest version, I cleared cache, I tried older versions, I tried moving the folder strait into my F drive because i heard about something with special characters messing it up? anyone have any ideas on how to fix this? Thanks in advance!

**Comment by stereo1029** [comment]
also forgot to mention, disabled all real time anti virus stuff, didn't know if it would help or not

**Comment by dtugend** [comment]
This means:
- either your HLAE is not fully updated
- or the game path you launch is not fully updated

1) Right click CS:GO in Steam library -> Properties -> Local Files Tab -> Verify Game Cache and let it re-download missing / broken files.
2) Right click CS:GO in Steam library -> Properties -> Local Files Tab -> Browse Local Files button and copy & paste the full path into HLAE and append `\csgo.exe` to make sure you are using the right path in HLAE (some people end up with two installs after a while).

**Comment by stereo1029** [comment]
thanks for the insight, changing the directory fixed it. I was running through a steam library folder that I'm assuming was left over from before I swapped this drive to my boot drive lol
