### ISSUE TITLE
demos lagy/bug

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#367]
when i download and play my demo of faceit there is **no lag...**
but, when i play demo that i recorded ( record x ) is sooo lagy  the fps 10 i see 1 image every 3 sec....
.
it was normal before 3 or 4 days . (my fps is +200)

**Comment by Dechno1337** [comment]
POV demos are broken with the latest CS:GO update(s) - revert to another version, or wait for a fix from Valve.

**Comment by dtugend** [comment]
This is not HLAE related, but a bug they introcuded in CS:GO with one of the trusted mode updates:
https://www.reddit.com/r/GlobalOffensive/comments/hpa4w2/1_fps_csgo_demo/

I recommend to report it to the CS:GO devs by email  as recommenced here:
https://www.reddit.com/r/GlobalOffensive/comments/ho7k34/trusted_mode_feedbackbugs_megathread_update_7820/
