### ISSUE TITLE
voice GOTV

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#368]
-u can here the players voice in ****faceit**** demos/solo **pov** 
-cs go competitve demos : **no voice**.

is there any command or something to enable voice of csgo competitive demos **?!!!**

**Comment by xNWP** [comment]
Hi iqhl,

The player coms are stored in the demo, unfortunately CS:GO competitive doesn't save the voice data with the demo. So there is no way to get coms in MM demos with any commands.
