### ISSUE TITLE
(csgo) when i record with mirv_streams brightness is changing !!! 

### ISSUE THREAD

**Issue by iqhl** [advancedfx/advancedfx#37]
when i record with mirv_streams brightness is changing !!!
how to keep same brightness or gamma! i dont know...
![csgo 2018-02-01 17-53-01-30](https://user-images.githubusercontent.com/35741166/35691819-d6d44568-0779-11e8-9a0f-41e6bc4063fa.jpg)
![csgo 2018-02-01 17-56-04-93](https://user-images.githubusercontent.com/35741166/35691823-d79804b2-0779-11e8-9c45-6ded4beb8096.jpg)

**Comment by dtugend** [comment]
GitHub issues is mainly a bug tracker and not a support ticket system as far as I know, if you need a notable amount of normal support consider using the [forums](http://advancedfx.style-productions.net/forum/) or the [Discord](https://discord.gg/NGp8qhN) instead, if possible.

[My first reply (2nd post) in the thread](http://advancedfx.style-productions.net/forum/viewtopic.php?p=6879#p6879) I linked in [your last issue](https://github.com/advancedfx/advancedfx/issues/36) gives a complete solution on how to use startmovie for recording with mirv_streams.

I also linked a tool called [CS:GO Demos Manger there, that allows easy video recording too](https://csgo-demos-manager.com/docs/movie/getting-started).

If you want to use mirv_streams for image recording and only use one stream anyway, you can simply add this to your config:
```
mirv_streams record matPostprocessEnable 1
mirv_streams record matDynamicTonemapping 1
mirv_streams record matMotionBlurEnabled 0
mirv_streams record matForceTonemapScale 0
```
As said, this will only work with one stream, you cannot use these with multiple mirv_streams!

**Comment by iqhl** [comment]
questions about recording with startmovie and mirv_streams 
1- startmovie = recording video . and in same time mirv_streams =recording audio .  right ? 
2- but if mirv_streams changing the brightness startmovie it will record that !!! or no ?

**Comment by dtugend** [comment]
1 - yes
2 - yes, that is why I linked the post that has a complete config for a .cfg file you can use, that also includes the settings I posted above - when using these settings, it won't change brightness and other stuff.
