### ISSUE TITLE
FFMPEG image stream encoding on Laptop

### ISSUE THREAD

**Issue by cherinyy** [advancedfx/advancedfx#370]
![ffmpeg](https://user-images.githubusercontent.com/9050713/88014136-c750b980-cb50-11ea-9340-9270089d5420.png)
![hlae](https://user-images.githubusercontent.com/9050713/88014141-ca4baa00-cb50-11ea-98b4-116dc84c8841.png)
HLAE and FFmpeg work on the integrated graphics card by default, but CS:GO runs on the discrete graphics card, so this causes CS:GO to crash (not responding) when starting recording.

My solution is to manually specify HLAE.exe and ffmpeg.exe as "run on discrete graphics card".

It is worth noting that if "Hardware-Accelerated GPU Scheduling" is enabled in Win10 2004 and above, then you need to go to Windows Settings - Default Graphics Settings for settings, not the NVIDIA Control Panel.

**Comment by dtugend** [comment]
This should not cause any crash, because AfxHookSource currently feeds the image data through a standard input pipe to ffmpeg.exe, meaning it's not relevant if it's on same GPU or not.

More likely you forgot to set host_framerate other than 0 before starting recording, which will cause the behaviour your described.
Please make sure that host_framerate is set to the recording FPS before starting recording.

I will ask someone from the HLAE team if they can help testing, but as said, I expect it to be due to host_framerate being default (0) when recording.

**Comment by cherinyy** [comment]
> This should not cause any crash, because AfxHookSource currently feeds the image data through a standard input pipe to ffmpeg.exe, meaning it's not relevant if it's on same GPU or not.
> 
> More likely you forgot to set host_framerate other than 0 before starting recording, which will cause the behaviour your described.
> Please make sure that host_framerate is set to the recording FPS before starting recording.
> 
> I will ask someone from the HLAE team if they can help testing, but as said, I expect it to be due to host_framerate being default (0) when recording.

I see. But I have checked the problem many times, including anti-virus programs, but I have never found the problem.

About `host_framerate`, I bound it to the button.
![cfg](https://user-images.githubusercontent.com/9050713/88035714-24f6fd00-cb75-11ea-887f-87a5408a2a01.png)

**Comment by dtugend** [comment]
Hi, we didn't find someone else that can help to check the issue yet, however can you tell us the FFMPEG settings you use in HLAE, do they even make use of CPU accelerated encoding? Also let us know the FFMPEG version you use please (see `ffmpeg\README.txt`)

**Comment by cherinyy** [comment]
> Hi, we didn't find someone else that can help to check the issue yet, however can you tell us the FFMPEG settings you use in HLAE, do they even make use of CPU accelerated encoding? Also let us know the FFMPEG version you use please (see `ffmpeg\README.txt`)

I am in the mountain village now, and I will test it again tomorrow or the day after I go home.

FFMPEG settings
> mirv_streams add normal norm
mirv_streams edit norm settings afxFfmpeg

FFMPEG Version is 4.3, 64-bit, Static, GPL.

**Comment by cherinyy** [comment]
I'm very sorry, because some things have delayed some time.

I retested and confirmed that the problem is not related to GPU preferences.

Thank you for your patient answers :)
