### ISSUE TITLE
Explicit Version File

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#372]
In order to check the version of local hlae, adding a file containing version info in it would be helpful. I'm trying to make a tool that checks and automatically update hlae, so if u know how to get this done without it, pls let me know.

**Comment by dtugend** [comment]
HLAE has a changelog.xml file that comes with it, that contains version info too.

At least for the installer version an easier update process is already planned:
https://github.com/advancedfx/advancedfx/issues/321#issuecomment-656967529

**Comment by Purple-CSGO** [comment]
Ok. I've known how to achieve it. thx.

**Comment by dtugend** [comment]
(This file is going to be removed in HLAE 2.103.1 again.)
