### ISSUE TITLE
AGR recordInvisible 1 animation error

### ISSUE THREAD

**Issue by Devostated** [advancedfx/advancedfx#376]
When you record AGR, while being in first person spectating, the animation of the spectated character model will be quite off.

Used commands:
```
host_timescale 0
host_framerate 30
mirv_streams record agr enabled 1
mirv_streams record agr recordCamera 1
mirv_streams record agr recordPlayers 1
mirv_streams record agr recordWeapons 1
mirv_streams record agr recordProjectiles 1
mirv_streams record agr recordInvisible 1
mirv_streams record agr recordViewmodel 1
```

Here is a comparison between firstperson and freecam recording.

Firstperson spectating:
![image](https://user-images.githubusercontent.com/30211694/89760313-6c293b80-daec-11ea-9ead-c0e8c2aa3a34.png)

Freecam spectating:
![image](https://user-images.githubusercontent.com/30211694/89760327-72b7b300-daec-11ea-8585-0e4b2026ede7.png)

This problem has been reported to me by multiple users and tested it myself.

**Comment by dtugend** [comment]
Solution is to record thirdperson and use the new HLAE v2.104.0 + with AGR 5, which records player cameras and view models:
https://github.com/advancedfx/advancedfx/releases/tag/v2.104.0
https://github.com/advancedfx/afx-blender-scripts/releases/tag/v1.11.0
https://github.com/advancedfx/afx-sfm-scripts/releases/tag/v1.7.0

Edit: recordInvisible should not be required anymore!
