### ISSUE TITLE
Version not supported

### ISSUE THREAD

**Issue by Joness07** [advancedfx/advancedfx#377]
I'm using SFM scripts to import a .agr, whenever I do, I get an error saying version 4 not supported. I tried old and new versions of the scripts and it seems to be the HLAE version. I just tried the latest version and it now says "version 5 not supported". Which one would I need to use?

**Comment by dtugend** [comment]
Already answerred that here https://github.com/advancedfx/afx-sfm-scripts/issues/1

**Comment by dtugend** [comment]
I linked version 4 and 5 script there now, I see your question changed a bit.
