### ISSUE TITLE
HLAE error:12 pls help!

### ISSUE THREAD

**Issue by KrashM** [advancedfx/advancedfx#38]
When I try to start CSGO from HLAE this pops on my screen.
https://imgur.com/vQBzWm4
I don't know what to do. I've tryed reinstalling it several times and cheking if any of CSGO,Steam or HLAE are set to start as administrators, but nothing works. Please help! Thanks in advance.

**Comment by xNWP** [comment]
In general do not set either CS:GO or HLAE to administrator. Are you using any antivirus? If so try disabling it temporarily (or making an exception for HLAE), then redownload and try again. If that doesn't work check if you have any anticheat software running, ESEA, Faceit, challangeme.gg, etc. You may need to uninstall these programs to have HLAE work at all. Let me know if any of these solve the problem :-)

**Comment by xNWP** [comment]
Also I noticed that you have some non-ascii (non-english) characters in your location, try putting HLAE into its own folder absent of these characters, i.e. D:\HLAE

**Comment by dtugend** [comment]
Make sure that the user account that runs HLAE has sufficient access rights. If you can't create a new folder in the csgo.exe folder without using an operation that has an admin shield icon next to it, then it's an access rights problem.
Also avoid running HLAE from folders with special UTF characters, there used to be problems related to that, not sure if they are fixed. Also do not put HLAE into the CS:GO folder, this is not required and not recommended.

**Comment by KrashM** [comment]
xNWP I reinstalled it in a folder on my desctop and that fixed the error but now it doesn't want to start.
https://www.youtube.com/watch?v=LHo4kPfmMOM&feature=youtu.be

**Comment by dtugend** [comment]
1) Where did the title bar of HLAE go? The Windows is Maximized but has no title bar? This is not standard Windows behaviour?
2) Which operating system are you on?

**Comment by KrashM** [comment]
1.This happened because of the recording softwear. I am sorry.
2.I'm on Win7

**Comment by dtugend** [comment]
1. Please make sure to first check your system for maleware / spyware / adware / trojans, i.e. using these:
  * https://www.malwarebytes.com/adwcleaner/
  * https://www.kaspersky.com/free-antivirus

2. If it's not a geniune windows versio check that you are not missing fonts essential for a Windows Installation, especially the **Tahoma (Regular)** font!
<br />Please Google for the font, but be aware not to download SpyWare etc..
One place to get the font might be here:
http://fontsgeek.com/fonts/Tahoma-Regular/download (use ZIP download option!)
<br />* To install the font copy the .ttf file to the C:\WINDOWS\Fonts folder

3. Also follow this Guide to fix broken .NET installations on Windows 7 (assumes you have a genuine Windows 7 version, otherwise it might make things worse):
https://github.com/advancedfx/advancedfx/wiki/FAQ#windows-7--vista

**Comment by dtugend** [comment]
If that doesn't help make sure to check your Windows 7 install for errors / damages:
http://computerstepbystep.com/windows_integrity_windows_7.html

**Comment by dtugend** [comment]
That all is assuming you didn't cut the File -> Launch CS:GO dialogue from the video.
Did you cut that dialogue?

**Comment by dtugend** [comment]
Another question, do you have multiple monitors? Any chance the dialogure popped up on an other screen?

**Comment by KrashM** [comment]
No after I end the video nothing happens and no dialogue pops up.
It just continues to run as I have not done anything.

**Comment by KrashM** [comment]
I just fixed it IDK how.
Just cleaned my PC from junk files and programs that I didn't use to free up some space and it works now.
PS I had like 3GB left on C: maybe that was the problem I don't rellay know.
Thank you for all the help I really apreciate it <3

**Comment by KrashM** [comment]
I had it working yesterday but know it can't start again.
When I Launch CSGO it crashes or something like that end just ends the process.

**Comment by KrashM** [comment]
Here is a video of it(sorry about the bad quallity I think youtube makes some sort of a problem).
https://www.youtube.com/watch?v=EEnstcbzwg4&feature=youtu.be

**Comment by dtugend** [comment]
1) Please make sure to first check your system for maleware / spyware / adware / trojans, i.e. using these (if you want then both):
* https://www.malwarebytes.com/adwcleaner/
* https://www.kaspersky.com/free-antivirus

2) Right click CS:GO in Steam Library ->Properties -> Local Files tab -> Browse Local Files button,
compare if that path is the one you set in HLAE for launching, sometimes people end up with two differen CS:GO installs.

3) Right click CS:GO in Steam Library ->Properties -> Local Files tab -> Verify Game Cache button

**Comment by KrashM** [comment]
Nothing worked :(
Any other ideas why it worked yesterday but now doesn't?

**Comment by KrashM** [comment]
Yesterday I just started Avast and CCleaner to clean my PC's softwear and my browsers and it suddenly HLAE started working.But after a restart it stoped.

**Comment by KrashM** [comment]
I'm trully lost :(

**Comment by dtugend** [comment]
Add me in steam: https://steamcommunity.com/id/ripieces

**Comment by dtugend** [comment]
The problem was a modified xinput1_3.dll in the csgo.exe folder (according to KrashM used by a relative for using a controller, so can't judge if it's safe to use or not, I recommend against using that), movie the file away solved the problem.

**Comment by MARINA-FAITH** [comment]
I can not run CS: GO through HLAE. Writes an error: Problem in addresses.cpp: 334
How to solve this problem?

**Comment by xNWP** [comment]
Please update to the latest version of HLAE, also if you have problem please open a new issue, don't post it onto another.
