### ISSUE TITLE
mirv_voice  recorded sound files have "clip" issue

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#380]
I've tried with and without setting a stream, here's what i'm using to record
```
snd_setmixer voip vol 0;
mirv_streams record voices 1;
demo_timescale 1;
mirv_snd_timescale 1;
host_timescale 0;
mirv_streams record start;
```
The main music soundtrack has no problem, but those sound files of seperate entities have clip issue very explicitly, and are painful to listen to.

I've collected two samples, one with `snd_setmixer voip vol 0;` and main soundtrack does not contain caster voice. the other without it and has caster voice both in main and sub sound files and could be used to compare.
- link↓
https://drive.google.com/file/d/1Je9eT5wty4X_0keTBz2hIQ2ydcpgulvO/view?usp=sharing

**Comment by dtugend** [comment]
have you set host_framerate?

**Comment by Purple-CSGO** [comment]
I set 60fps but issue is still there:
https://drive.google.com/file/d/1sl77MDYsXazfBI0sSWcdah-ixZxGcPBK/view?usp=sharing

**Comment by dtugend** [comment]
requested access to the files several times by now, I hope it also includes a demo with audio so I can test myself :(

**Comment by dtugend** [comment]
Also be aware that the default voip mixer volume is 0.7 not 1.0, which would explain your clipping issue if you set it to 1.0:
```
] developer 2
] snd_getmixer voip
voip:
	VOL: 0.700000
	LVL: 1.000000
	DSP: 0.000000
	MUTE: 0.000000
	SOLO: 0.000000
```

**Comment by Purple-CSGO** [comment]
> requested access to the files several times by now, I hope it also includes a demo with audio so I can test myself :(

This is a demo with players' voice, but i'd recommend downloading in-game major demos. These demos have continuous caster voices and are better for testing.

https://drive.google.com/file/d/1QVwKtSl3n95pQc1jtLtFwDQQIeifnEn2/view?usp=sharing

When i set up things using:
```
snd_setmixer voip vol 0;
mirv_streams record voices 1;
demo_timescale 1;
mirv_snd_timescale 1;
host_timescale 0;
mirv_streams record start;
```

mixer voip is following:
```
] snd_getmixer voip
voip:
	VOL: 0.000000
	LVL: 1.000000
	DSP: 0.000000
	MUTE: 0.000000
	SOLO: 0.000000
```

by default:
```
] snd_getmixer voip
voip:
	VOL: 0.700000
	LVL: 1.000000
	DSP: 0.000000
	MUTE: 0.000000
	SOLO: 0.000000
```
