### ISSUE TITLE
What are the settings for the afxSampler30 mirv_stream setting?

### ISSUE THREAD

**Issue by Minoo7** [advancedfx/advancedfx#382]
(Please search exiting **open and closed** issues first to verify this is a new question.)
I would like to create a new mirv_stream setting behaving the same as afxSampler30 but converting it to 60fps instead of 30. I know I can add new mirv settings with mirv_stream settings add but I don't know the settings afxSampler30 is using to get the motion blur etc. Does anyone know the setting for it, I searched in forums, wiki and in the HLAE files but with no luck.
Thank you in advance!

**Comment by Dechno1337** [comment]
`mirv_streams settings edit <name>`

If you enter the name of your newly added setting, do you get a list of options you can edit? It should be enough to edit the fps setting to 60, and then the host_framerate value will be used to downsample into 60 fps.

The rest of the sampler settings should be the same as afxSampler30 (default).

**Comment by Minoo7** [comment]
So there is no more settings to the afxSampler30 other than it changes it to 30fps? Like is there no different setting that makes the motion blur happen?. 

> The rest of the sampler settings should be the same as afxSampler30 (default).

How do I know those settings?

**Comment by dtugend** [comment]
They are the same by default
`mirv_streams settings edit <name>`  should display all available options with a brief description.

Example:
```
mirv_streams settings add sampler mySampler
mirv_streams settings edit mySampler fps 60
mirv_streams settings edit afxDefault settings mySampler // use mySampler as default setting instead of afxClassic (images)
mirv_streams settings edit mySampler // this will print other options to console (make sure con_filter_enable is 0)
```

The settings are the same / similar to the ones in GoldSrc, described / linked in this article:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ASampling-System

**Comment by dtugend** [comment]
Considering this answerred.
