### ISSUE TITLE
Can I use the player HUD in GOTV?

### ISSUE THREAD

**Issue by cherinyy** [advancedfx/advancedfx#383]
I want to record POV via GOTV.

I looked for it, but I only found this: #283

But I don't need to modify the HUD, I only need to use the player HUD.

Is it possible to completely pretend to be a player?

There are two more questions: whether the radar can only display the team radar, and whether the voice can only play the team voice.

**Comment by dtugend** [comment]
## HUD:
https://www.youtube.com/watch?v=FTDCTG6ZJBs
Contrary to what the description says the HUD works with latest HLAE version, only the folder where the files need to be got changed to `%APPDATA%/HLAE` as mentioned in HLAE Wiki.

## Teamradar:
Not sure what you mean, try the HUD above and go into in-eye (POV) view in demo.
Edit: If you mean you want round radar, I am afraid that's a bit very difficult and not solved by the HUD.

## Voice:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_voice#mirv_voice-block

**Comment by cherinyy** [comment]
@dtugend 
Thank you! I also found this [wiki](https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI), but it shows 

> As of CS:GO 10/23/2018 update Panorama Debugger is no longer available.

I thought it meant that it could not be modified.

> Not sure what you mean, try the HUD above and go into in-eye (POV) view in demo.

I mean: GOTV's radar will show everyone's location. Is there a way to only show the team's location information?

**Comment by dtugend** [comment]
> I thought it meant that it could not be modified.

No it only means the Debugger GUI, it can still be modified.

> I mean: GOTV's radar will show everyone's location. Is there a way to only show the team's location information?

That is currently not easily possible, sorry.

If you want make a feature request for tricking the engine into thinking another player in the demo is the "local" player, which *might* make it work and render the Panorama UI modification redundant.

**Comment by cherinyy** [comment]
> If you want make a feature request for tricking the engine into thinking another player in the demo is the "local" player, which might make it work and render the Panorama UI modification redundant.

Yes! I want to request this feature because I found that GOTV does not show the characteristics of `cl_crosshairstyle 5` and other functions that exist "locally".

But I think it is extremely difficult to realize this function.  So at this stage, I just want to restore the player's first-person perspective as much as possible.

**Comment by dtugend** [comment]
Ok, the issue is now tracked here: https://github.com/advancedfx/advancedfx/issues/384
The other questions have been answerred I think?

**Comment by cherinyy** [comment]
> Ok, the issue is now tracked here: #384
> The other questions have been answerred I think?

OK, yes, thank you again!
