### ISSUE TITLE
[GoldSrc] Add suport for ReGameDLL_CS

### ISSUE THREAD

**Issue by Lopol2010** [advancedfx/advancedfx#385]
There is ReHLDS and ReGameDLL_CS. It means reversed cs mod and hlds, then rewriten and optimized. As i know these are faster and with fixed bugs and vulnerabilities. Im not good at understanding such big projects, but seems they have good enough API which should make transition of hlae super easy? 

There is also [GSClient 1.6](https://gsclient.com/) which is client based on these new dlls. This thing can work as steam cs if you have enabled steam, otherwise it will launch as nonsteam. 

P.S.
There is actually a lot of new things related to these reversed things, such as re-metamod and support for amxx 1.9 and 1.10, reapi (for plugin makers) and many other cool things such as ban system, anti cheats.... You can see all this here: https://dev-cs.ru/resources/categories/1/

**Comment by Lopol2010** [comment]
Also i have question, do current goldsrc hlae support recording video with ffmpeg directly to mp4? i see you added ffmpeg but i can't see mirv_streams record start.

**Comment by dtugend** [comment]
We only support the latest official Steam version officially. Sorry.
