### ISSUE TITLE
ffmpeg for goldsrc

### ISSUE THREAD

**Issue by Lopol2010** [advancedfx/advancedfx#386]
I see you added ffmpeg for goldsrc but not added way to use it, is this right? Currently goldsrc not support direct video record on windows?

**Comment by dtugend** [comment]
The new command for GoldSrc is `mirv_movie_ffmpeg`, enter it in console without options to get built in-help text.

For it to work FFMPEG needs to be installed the same way it is required for CS:GO.
To install FFMPEG, either use the HLAE_Setup.exe version of HLAE, which assits with that or follow the instructions in the [readme.advancedfx.txt in the ffmpeg folder of the ZIP version](https://github.com/advancedfx/advancedfx/blob/master/resources/ffmpeg/readme.advancedfx.txt).

The presets for each stream / group of streams can be edited with mirv_movie_ffmpeg, presets syntax is the same as in CS:GO, maybe edit an exisiting one  (without options)to get an idea.

**Comment by Dechno1337** [comment]
Added some info to the wiki page: https://github.com/advancedfx/advancedfx/wiki/GoldSrc:mirv_movie_ffmpeg

**Comment by dtugend** [comment]
I think this is answerred.
