### ISSUE TITLE
Option to generate certain xml/json file containing HUD info

### ISSUE THREAD

**Issue by Purple-CSGO** [advancedfx/advancedfx#387]
Before afx-cefhud-interop feature finally releases, could hlae add an option to generate files containing HUD info like Crosshair - Deathnotices - HP - Helmet/Armor - Bullet stats.

This file should contain some basic and neccessary info and a matrix of `items` based on `time`. Each `item` shows at `what time`, `which thing` such as Crosshair is set or changed.

In the process of recording, generating such files does not need too much work and therefore I could make programs to drag-and-drop-and-generate HUD stream .mov files, since Crosshair & Deathnotices become an issue when using MotionBlur VFX.. they keep shaking and do harm to feeling of audience.

Consider a command like `mirv_record GenerateHUDInfo 1` to open it up and set to 0 by default. xml/json file ends up in the takexxxxx directory.

**Comment by dtugend** [comment]
Why not just extend this to write gameEvents as JSON to a file?
https://github.com/advancedfx/advancedfx/blob/main/misc/mirv_pgl_test/server.js
We don't have access to crosshair info currently though, if it's not part of gamevents at least.

**Comment by dtugend** [comment]
Closed in favor of #761
