### ISSUE TITLE
ffmpeg.zeranoe.com will close on Sep 18, 2020.

### ISSUE THREAD

**Issue by cherinyy** [advancedfx/advancedfx#388]
The automatic download of the installer needs to look for other sources.

**Comment by dtugend** [comment]
Thank you for notifying us.

**Comment by dtugend** [comment]
- https://twitter.com/Zeranoe/status/1300596971934224385
- https://github.com/Zeranoe/mingw-w64-build
- https://github.com/rdp/ffmpeg-windows-build-helpers
- https://github.com/m-ab-s/media-autobuild_suite

**Comment by dtugend** [comment]
@Purple-CSGO Since there's still the custom option, would it be okay to mirror them on a GitHub repo and make the installer download from there for now?

**Comment by Purple-CSGO** [comment]
I have been mantaining [this repo](https://github.com/Purple-CSGO/FFmpeg-Archieve) to archieve release files. For static build, i only preserve `./bin` dir and `./bin/ffmpeg.exe` file and 7z to make it <20MB, thus we could use jsdelivr to speed up download probably anywhere. But It's made manually, so I could not make sure it is the latest at anytime.

**Comment by Purple-CSGO** [comment]
Also there's auto build repo like the following:
https://github.com/AnimMouse/ffmpeg-stable-autobuild
