### ISSUE TITLE
FFMPEG: support newer builds by ourselves or someone else

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#390]
Due to https://github.com/advancedfx/advancedfx/issues/388 currently no new builds are avaialble.

**Comment by cherinyy** [comment]
ffmpeg.org now has a new build: https://www.gyan.dev/ffmpeg/builds/

**Comment by dtugend** [comment]
Thank you for informing us. I will try to look into these by next week.

**Comment by dtugend** [comment]
We will probably continue adding BtbN autobuilds now and then to HLAE, since they don't disappear that quickly from GitHub probably:
https://github.com/BtbN/FFmpeg-Builds/releases
(As has been done in HLAE 2.109.6 already.)
