### ISSUE TITLE
replacing the random death ragdolls for death animations

### ISSUE THREAD

**Issue by iniw** [advancedfx/advancedfx#392]
i don't know how this would even work/be made but here are some cool suggestions !

mirv_deathAnim_ player -> determines which player's ragdolls will be replaced through index or xuid dunno

mirv_deathAnim_mode 0 | 1 | 2 | 3 -> replaces death closest to current tick | replaces death closest to a specified tick | replaces death number (1st death, 2nd death, etc.) | replaces all deaths

mirv_deathAnim_speed -> multiplies the speed of the animation to this value ( don't know if this is possible )

not sure how the individual configurations for the ticks and stuff would work, this is just a general idea

**Comment by dtugend** [comment]
And it replaces them with what(?)
Do you mean with non-random ones?

**Comment by iniw** [comment]
yeahhh u see thats the issue, maybe there could be a command like mirv_deathAnim_path that would take a path to an animation file exported from something like blender or cinema4d

**Comment by Dechno1337** [comment]
Why complicate it, just have a `mirv_fix deathAnim 0|1` command whether to enable (1) or disable (0) static ragdoll physics.

If you want to make custom animations, can't you use SFM for that, or `mirv_agr`(?)

**Comment by dtugend** [comment]
I don't plan to do this currently.
