### ISSUE TITLE
(mirv_pov) Crosshair of spectated player isn't show despite "cl_show_observer_crosshair 2" enabled

### ISSUE THREAD

**Issue by nthnwllms** [advancedfx/advancedfx#394]
The crosshair is stored in the demo and is visible normally (when not using mirv_pov) if you set "cl_show_observer_crosshair" to 2 but this feature does not function when using mirv_pov and will instead show your own crosshair, not the crosshair of the player you're watching.

**Comment by dtugend** [comment]
This is also closed by https://github.com/advancedfx/advancedfx/commit/cb1af1a2e0d16458452f7b45438666fd011850c1
