### ISSUE TITLE
(mirv_pov) Occlusion flickering

### ISSUE THREAD

**Issue by nthnwllms** [advancedfx/advancedfx#395]
It seems like some of the occlusion gets confused when using mirv_pov.

Ex. Watching elige (mirv_pov 6) on this Inferno demo - https://www.hltv.org/matches/2343652/evil-geniuses-vs-liquid-esl-pro-league-season-12-north-america

You can see the trees outside of the map flickering a bit in Terrorist spawn but it becomes very obvious when he goes boiler and looks up the stairs.

![image](https://user-images.githubusercontent.com/17016985/94036157-01794a00-fd92-11ea-81ff-3958f57a29be.png)

**Comment by dtugend** [comment]
Until this is fixed you can work around it with:
```
mirv_cvar_unhide_all; r_portalsopenall 1
```
