### ISSUE TITLE
Missing and doubled viewmodels

### ISSUE THREAD

**Issue by Devostated** [advancedfx/advancedfx#400]
Missing:

While being in PoV of another character with recordViewmodels -1, the other character will only have weapons but no arms and gloves
![image](https://user-images.githubusercontent.com/30211694/94996194-5cd1e600-05a3-11eb-82a6-de5fefc98462.png)

Doubled:

While recording with recordViewmodels <playerIndex>, the arm and gloves get recorded / imported multiple times.
![image](https://user-images.githubusercontent.com/30211694/94996200-66f3e480-05a3-11eb-87dd-e4ce0fc6cf4f.png)

**Comment by dtugend** [comment]
Not sure if I understand, but for AGR please record in **free cam** instead, should be fine when #399 is fixed.

**Comment by dtugend** [comment]
The doubling comes from recordInvisible 1, should not be used anymore, unless absolutely required.
