### ISSUE TITLE
Disable Aim Lines

### ISSUE THREAD

**Issue by XIIIG** [advancedfx/advancedfx#401]
Hello,

I would love to see a command to hide player aim lines - https://i.imgur.com/Xok0Ktw.png
I was looking for a command to disable these lines, but unfortunately, I think there is no command to achieve this.

Cheers

**Comment by NESTOWL** [comment]
@XIIIG `spec_show_xray 0` and reload demo, should help.

**Comment by XIIIG** [comment]
> 
> 
> @XIIIG `spec_show_xray 0` and reload demo, should help.

It disables the entire xray :( I just want to disable aim lines and leave xray enabled.

**Comment by dtugend** [comment]
```
mirv_streams add basefx myNorm
mirv_streams edit myNorm doBloomAndToneMapping default
mirv_streams edit myNorm doDepthOfField default
mirv_streams edit myNorm actionFilter add __utilwireframe noDraw
mirv_streams edit myNorm actionFilter add __utilwireframeignorez noDraw
mirv_streams edit myNorm actionFilter add __utilvertexcolorignorez noDraw
mirv_streams preview myNorm
```

For finding materials see https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#related-tutorials mirv_streams picker tutorials.

**Comment by dtugend** [comment]
For example see (updated) comment above.
For finding materials see https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#related-tutorials mirv_streams picker tutorials.

**Comment by dtugend** [comment]
Forgot the `mirv_streams preview myNorm`, fixed.

**Comment by XIIIG** [comment]
> 
> 
> ```
> mirv_streams add basefx myNorm
> mirv_streams edit myNorm doBloomAndToneMapping default
> mirv_streams edit myNorm doDepthOfField default
> mirv_streams edit myNorm actionFilter add __utilwireframe noDraw
> mirv_streams edit myNorm actionFilter add __utilwireframeignorez noDraw
> mirv_streams edit myNorm actionFilter add __utilvertexcolorignorez noDraw
> mirv_streams preview myNorm
> ```
> 
> For finding materials see https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_streams#related-tutorials mirv_streams picker tutorials.

Works flawlessly! Thank you.
