### ISSUE TITLE
Money instead of health in overhead

### ISSUE THREAD

**Issue by XIIIG** [advancedfx/advancedfx#403]
Hello,

I was wondering if it would be possible to display player money instead of health in overhead during a live round.

So I'm trying to display this - https://i.imgur.com/iUCYhwV.jpg but for the whole round not just during a freezetime.

What I was trying to do:

Changing this line: (csgo_english.txt)
`"Panorama_HUD_playerid_overhead_t"				"<font color='#fecd25'>{s:player_name}</font><font color='#ccc08c'> {d:player_health}%</font>"`
to
`"Panorama_HUD_playerid_overhead_t"				"<font color='#fecd25'>{s:player_name}</font><font color='#ccc08c'> {d:r:player_money}</font>"`
and
`"Panorama_HUD_playerid_overhead_t"				"<font color='#fecd25'>{s:player_name}</font><font color='#ccc08c'> {d:player_money}</font>"`

Result - https://i.imgur.com/84kw1vt.png

and messing with this line: (layout/hud/hudreticle.xml) using this tutorial - https://github.com/advancedfx/advancedfx/wiki/How-to-change-Panorama-UI
`<Label id="NameBG" class="playerid__nameBG" html="false" text="{s:player_name}XXXXX"/>`

but no luck. Is there anything else I could try to force displaying player money over the head?

**Comment by dtugend** [comment]
Panorama_HUD_playerid_overhead_t is for T-Models, however your screenshot shows a CT model, you probably want to change Panorama_HUD_playerid_overhead_ct_lowhealth and Panorama_HUD_playerid_overhead_ct instead?

**Comment by dtugend** [comment]
I am sorry to disappoint you, but CS:GO has this code path only enabled for POV and during freezetime, it will not work on GOTV demos without a hook or cheat, sorry.

Edit: Basically the player_money variable is not filled for GOTV demos.

**Comment by XIIIG** [comment]
ah, at least I can edit overhead CSS, thank you anyway.
