### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by bobsoverad** [advancedfx/advancedfx#406]
When I run hlae it gives me an error-something went wrong and at the top of the message there is AFXSourceProcesses, it was working the day before and suddenly stopped. I have re-installed it many times but there was no fix

**Comment by dtugend** [comment]
Please provide more information and a screenshot of the message.
Also try if rebooting fixes it.
Also make sure no anti-cheat is running in background.

**Comment by bobsoverad** [comment]
I have this message :     __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at advancedfx.injector.interop.Formatter.System.Runtime.Serialization.IFormatter.Deserialize(Stream serializationStream)
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Its says there is no solution.

![Screenshot (2)](https://user-images.githubusercontent.com/54459065/100557239-a4e84e80-325c-11eb-8ff0-28fdd71b39ee.png)

**Comment by dtugend** [comment]
Most likely your Anti-Virus either blocks or deleted the injector.exe in the HLAE.exe folder (the one in the "x64" sub-folder is a **different** one and does not matter).
Please make sure to allow / unblock / undelete the injector.exe in your Anti-Virus (and maybe redownload and repair / reinstall HLAE).

If you are using Comodo Anti-Virus software, there's a known problem with them: https://github.com/advancedfx/advancedfx/issues/345

**Comment by bobsoverad** [comment]
I have the antivirus off and have tried reinstalling it and reparing but the error still shows up

**Comment by dtugend** [comment]
Which AV do you use? (Only disabling Comdo didn't disable the component last time that causes it for some users either.)

**Comment by bobsoverad** [comment]
I use the integrated windows antivirus, also does hlae have any relation to a process called synaptics pointing device driver, this always gets promoted for me to press yes to run it as admin.

**Comment by dtugend** [comment]
> does hlae have any relation to a process called synaptics pointing device driver, this always gets promoted for me to press yes to run it as admin

No HLAE is completely unrelated to that.
Edit2: Also HLAE does not need to be run as admin.

Consider running adwcleaner from MalwareBytes: https://www.malwarebytes.com/adwcleaner/

Windows Defender does not cause these problems you have between HLAE and injector.exe, it must be some other software that causes it.

If nothing helps, try to ask for help in HLAE Discord tomorrow or so, when I am online and have time I will try to help you there, but maybe someone else of the HLAE team is able to help as well, maybe not though.

Edit:
If you have a tool to sandbox software, it might be also that, HLAE won't work sanboxed.

**Comment by dtugend** [comment]
This issue seems stalled, any news?
