### ISSUE TITLE
Sometimes an error box pops up

### ISSUE THREAD

**Issue by xiexiangchao** [advancedfx/advancedfx#408]
(Please search existing **open and closed** issues first to verify this is a new bug report.)
<img width="217" alt="微信图片_20201207173028" src="https://user-images.githubusercontent.com/68836665/101333726-ea86c600-38b1-11eb-9954-29e3e915f8bb.png">

**Comment by xiexiangchao** [comment]
Version 2.109.4

**Comment by dtugend** [comment]
What does "sometimes" mean?
What's your CS:GO version?

**Comment by xiexiangchao** [comment]
ClientVersion=1210
ServerVersion=1210
PatchVersion=1.37.7.2
ProductName=csgo
appID=730
SourceRevision=6244269
VersionDate=Dec 04 2020
VersionTime=22:10:14

I will give you demo url soon.

**Comment by xiexiangchao** [comment]
I recorded lots of csgo video. This bug rarely appeared.

**Comment by xiexiangchao** [comment]
I recorded this demo on another machine. This bug didn't appear again. Thanks!

**Comment by dtugend** [comment]
This _could_ mean your CS:GO install was incosistent or s.th. altered the DLLs or the memory of CS:GO or the RAM was faulty.
Sometimes this error happens randomly after updating HLAE, might be a Windows 10 bug with DLL caching (?).
A reboot usually fixes it though.
