### ISSUE TITLE
HLAE

### ISSUE THREAD

**Issue by svetjana** [advancedfx/advancedfx#41]
Why won't hlae save my settings? Always when I restart it, it says "Check for updates automatically?" and I have to put launch options again. Frustrating

**Comment by xNWP** [comment]
Hi, which folder have you put HLAE into?

**Comment by svetjana** [comment]
nevermind.. It is in my "downloads" -folder and shortcut is in my desktop. I just removed everything, and unpacked it again. Maybe week ago I freshly installed windows and cutted and pasted everything from "downloads" -folder to another hdd. And after reinstalling windows cutted and pasted back. I think creating "hlaeconfig.xml" newly was the fix?

**Comment by xNWP** [comment]
Okay sounds about right, glad to hear it's working :-)

**Comment by svetjana** [comment]
Yeah, but nice to know that here is almost all the time support available :) Fast replying

**Comment by xNWP** [comment]
You just happened to catch me at a good time ;) But we do try to be as fast as possible, max wait time is probably about 12 hours

**Comment by svetjana** [comment]
Haha :D good :)
