### ISSUE TITLE
Loader could not create requested process, Error Code: 2002

### ISSUE THREAD

**Issue by sagarpatel9591** [advancedfx/advancedfx#411]
![error](https://user-images.githubusercontent.com/71030584/102156114-e414c300-3e4a-11eb-8395-91b3a85f5b78.JPG)

I have not been able to run csgo from HLAE. Not working for me as I keep getting this error. I have tried re-installing steam, csgo, hlae, tried running them as admin, disabled anti-virus, tried everything but nothing worked so far.

**Comment by dtugend** [comment]
Have you disabled Anti-Cheat?
E.g. closing the Anit-Cheat UI often is not enough, you need to tell it to shut down / quit.

Which Anti-Virus you use?
E.g. disabling Comdo Anti-Virus won't disable the behavior blocking component of it. Instead add an exception to that one for HLAE.exe / injector.exe.

**Comment by dtugend** [comment]
Also what's your path to csgo.exe in HLAE?
Make sure csgo.exe is not missing at the end:

Example:

Wrong: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\
Correct: `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

**Comment by sagarpatel9591** [comment]
I am using windows defender currently. Just uninstalled my other antivirus AVG security. I disabled all the components of Windows Defender seperately. Virus & protection, account protection, firewall & network protection, app& Browser control, device security. Disabled them all one by one.

As for the path in HLAE, it is same as the real path: C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe

As you suggested I tried adding an exception for HLAE, to the file as well to the folder itself but didn't work.

**Comment by dtugend** [comment]
Please do not deactivate Windows Defender because of HLAE, except for temporary testing, it should just work fine with it in most cases. It's important to have basic antivirus protection.

I'd suggest to meet in the official advancedfx Discord chat, since I am currently out of ideas about what might be causing it from what you described: https://discord.com/invite/NGp8qhN

**Comment by sagarpatel9591** [comment]
I just joined the Discord chat. Should I just re-write my issue there? Or how do I reach out?

**Comment by dtugend** [comment]
We usually avoid this route, but this time the user decided to format his system, since there were also loads of other troubles involved. This also solved the problem.
