### ISSUE TITLE
Camera goes crazy with mirv_input end + camera smooth

### ISSUE THREAD

**Issue by XIIIG** [advancedfx/advancedfx#413]
Hi,

I have some issues using smooth camera with inputs disabled (mirv_input end).

I'm using this config to make camera smooth - https://github.com/advancedfx/advancedfx/wiki/Tutorial%3A-Spectator-smooth

With this config above I use `mirv_input end` - I use this command because I want camera to follow players using `spec_mode 5`
Unfortunately `spec_mode 5` with `mirv_input camera` doesn't follow players :(

Here is the video showing what happens when using `mirv_input end` with smooth camera:
https://streamable.com/k5bnbc

In certain spots camera goes totally crazy and it's spins around. It always happens in the same spots.

What can cause that?

**Comment by dtugend** [comment]
You are rotating more than 180° per smooth interval with the mouse and it will always take the shortest path.
Did you change any of the values? It seems notably smoother than the original values.

**Comment by XIIIG** [comment]
I didn't change anything in the config file, maybe it seems smoother because i'm using `sv_specspeed 1`

Is there anything I can try to fix it?

**Comment by dtugend** [comment]
I can not test right now, but I think it should not be that slow in default settiings.
If `sv_specspeed` affects the speed of it then you pressed [ESC] after entering `afx_smooth_on` in console.
Do not press ESC that will end mirv_input mode and result in different mouse / keyboard movement etc.

If that's not cause of the problem, then please read the comments in the script / uncomment the parts that you want to adjust.

```
// This is a comment
echo This is not a comment.
```

**Comment by XIIIG** [comment]
> Do not press ESC that will end mirv_input

That's the whole point :P 

I want to use smooth camera with `mirv_input end`.
Only with `mirv_input end` I'm able to follow players using `spec_mode 5`.

Example:
https://streamable.com/bnlnvq

I don't know if there is a way to achieve this using `mirv_input camera`.

and yes, with `mirv_input camera` everything works fine, camera doesn't spin around.

**Comment by dtugend** [comment]
You can use mirv_aim together with the smooth config: and make it aim and the currently selected player:

```
mirv_calcs handle add localPlayer localPlayer
mirv_calcs handle add observerTarget observerTarget localPlayer
mirv_calcs vecAng add handleEye observerTargetEye observerTarget
mirv_aim calcVecAng observerTargetEye 
mirv_aim snapTo 1

```

You also will need to update aliases:
```
alias "afx_smooth_on" "mirv_cam order move input 0; mirv_cam order move aim 1; mirv_cam source calcVecAng smooth; mirv_cam fov calc smooth; mirv_input camera; mirv_input cfg offsetMode ownLast; mirv_input cfg mouseMoveSupport 1; mirv_aim active 1"
alias "afx_smooth_off" "mirv_input end; mirv_aim active 0; mirv_cam source calcVecAngClear; mirv_cam fov calcClear; mirv_cam order default; mirv_input cfg offsetMode last; mirv_input cfg mouseMoveSupport 0"
```

(The config might not be 100% correct, I can not test it right now, will correct it in case I find an issue later.)

**Comment by dtugend** [comment]
Ah you want a the camera to be following the player I understood now sorry. I will need to think about that.

**Comment by dtugend** [comment]
Which HLAE version are you using?
Because I did a few fixes not long ago.

If it's latest HLAE 2.109.4 you can try to lower the smoothing time of the rotation for now:
```
mirv_calcs cam edit smooth halfTimeAng 0.1
```

Also try 0.025 / 0.0125 / ... in case it's still too slow for rotation

**Comment by XIIIG** [comment]
Yes, I'm using the latest version.

I tried to lower the smoothing and here is the result:
https://streamable.com/ewc1b0

It always happens in this exact map spot, isn't it weird?

**Comment by dtugend** [comment]
can you use spec_pos to print the approximate position on the map
I suppose without smoothing it doesn't happen?
Where can I get the map?

**Comment by dtugend** [comment]
I looked at the mirv_calcs code.
Contrary to what I said it doesn't take the shortest path for the quaternion interpolation, which leads to issues, since the engine does an floating point modulo on the angle values sort of.
I will fix that and add an option for it that will default to taking the shortest path.

However it should not depend on the map position itself, it should instead depend on the direction you are looking.

**Comment by XIIIG** [comment]
You are right, it happens when I point the camera at the specific direction and move my mouse - sorry for misleading.

When can I expect the fix to be rolled out?

**Comment by dtugend** [comment]
Please updat to HLAE 2.109.6 (2020-12-21T08:09Z) or newer.

**Comment by XIIIG** [comment]
It works fine now, thank you!
