### ISSUE TITLE
mirv_deathmsg fake doesn't work

### ISSUE THREAD

**Issue by needyourhelp1** [advancedfx/advancedfx#420]
I've tried everything.
Still coming back with just a skull and nothing else in the killfeed.
Is this not available anymore?

**Comment by dtugend** [comment]
Please give the exact command used and explain where you got the numbers from you enterred (e.g. XUID or UID numbers).

**Comment by needyourhelp1** [comment]
> Please give the exact command used and explain where you got the numbers from you enterred (e.g. XUID or UID numbers).

just the XUID where required (victim and attacker), same format as HLAE example
I even tried with attacker name and victim name and it still produced just a skull

**Comment by dtugend** [comment]
Please just copy and paste here what you enter, also consider providing the demo please.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
