### ISSUE TITLE
Mirv Calc Commands for Cinematics

### ISSUE THREAD

**Issue by Xeqtre** [advancedfx/advancedfx#423]
Hello, 

i want to use some calc hlae commands like its used in this youtube tutorial: https://www.youtube.com/watch?v=WtKC8uz57o8&feature=youtu.be 

But it does not work for some reason. I do not get it. I will post the config of the youtuber here. i try to use it for the cinematic:

//mirv_calcs handle add key key <number>  enter this command first with the number of your player
// then execute this cfg
mirv_calcs handle add activeWeapon aw key 1 ;
mirv_calcs vecAng add handleAttachment awm aw muzzle_flash ;
mirv_calcs vecAng add handleAttachment awh aw weapon_hand_R ;
mirv_calcs vecAng add or awmh awm awh ;
mirv_calcs vecAng add value weaponOfs 20 0 0 0 0 179.9 ;
mirv_calcs vecAng add offset awmOfs awmh weaponOfs 1 ;
mirv_cam source calcVecAng awmOfs ;
mirv_cam offset none ;
spec_mode 5

//mirv_cam offset translateX translateY translateZ rotateX rotateY rotateZ
//you can save your camera offsets here and even bind them or something

//mirv_cam source calcVecAngClear ; to disable the mirv_calcs commands
//mirv_cam offset none ; to reset the offset of the camera

The console does not say anything, so i thought it works but the camera position is not changing to the setup i posted at top of this Question.

**Comment by dtugend** [comment]
How do you load / execute the cfg?
Is your cfg file named name.cfg or name.cfg.txt (make sure that hiding default file extensions is disabled in Windows explorer).

I am guessing your cfg is not being executed at all.
In norder to test this, put an
```
echo TEST TEST TEST
```
at the end, it shoudl print `TEST TEST TEST` in console when loading the cfg, if not, it's not loading the cfg (config file) correctly.

**Comment by dtugend** [comment]
Additionally:
if you are using the File -> Launch CS:GO dialogue:
We recommend to enable "mmcfg" folder feature and set an (empty) folder there.
Inside that folder the game will then create a `cfg` folder, where you can put your movie making config files for executiong loading them with `exec name`.

**Comment by Xeqtre** [comment]
@dtugend 

I go inside the demo and type "exec cam.cfg", the answer in console is: "exec: couldn't exec cam.cfg"

**Comment by dtugend** [comment]
And where did you put cam.cfg?
And what's your mmcfg folder settings path in File -> Launch CS:GO?

**Comment by Xeqtre** [comment]
i put the cam.cfg into the cfg folder of my cs:go installation path

i do not understand whats the "mmcfg" ?

Do you mean the "Elternordner für Filmerstellungs Konfiguration" ?


Now i made a movie making cfg folder for the HLAE Path and created a Folder (CFG) inside my cs go folder. i sucessfully loaded 
the cfg with the command "exec cam" (for some reason exec cam.cfg does not work with the cfg in its name, so i deleted the word "cfg". after this it worked). I guess the new problem is that i have to put values (0-9) into the cfg.

Question: What to set for "key","aw","awm", "awmh" and "awmOfs" ?

The Error appeared when i loaded the "cam cfg"
exec cam
Error: No handle calc with name "key" found.
Error: No handle calc with name "aw" found.
Error: No handle calc with name "aw" found.
Error: No handle calcA with name "awm" found.
Error: No handle offset with name "awmh" found.
No vecAng calc "awmOfs" exists.

**Comment by dtugend** [comment]
There's stuff missing before the snippet you ahve.

**Comment by dtugend** [comment]
I didn't read the cfg properly sorry.

There's a comment:
```
//mirv_calcs handle add key key <number>  enter this command first with the number of your player
```

This means before executing the config enter this lien without the `//` infront and replace `<number>` with the spectator slot your want.

Also read the other comments in the script snippet.

----

Example:

```
mirv_calcs handle add key key 9
````
Only after that do
```
exec cam
````

Pro tip: to change the key use
```
mirv_calcs handle edit key key xxx
```

**Comment by Xeqtre** [comment]
i was successful with your explanation. i can create a front view of the player and the camera finally moves with the model if its moving.

**Comment by Xeqtre** [comment]
Did u see the tutorial, at the beginning of it their is a nice perspective with deagle, how can i get there ?

**Comment by dtugend** [comment]
I recommend studying this manual entry:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_calcs

At the end there's a good example config linked that even works in live observing.

**Comment by Xeqtre** [comment]
thanks

**Comment by dtugend** [comment]
Also read the pinned comment on the tutorial you found.
