### ISSUE TITLE
mirv_cvar_unhide_all crashes Counter Strike: Global Offensive

### ISSUE THREAD

**Issue by OfficerObese** [advancedfx/advancedfx#46]
no matter when the command is entered (in game or on menu) the game will crash.

**Comment by xNWP** [comment]
Can confirm that I am also seeing the same behavior. This is a new bug then. I'll pass this onto @ripieces to look into.

**Comment by dtugend** [comment]
Thank you for reporting the issue, please update to
HLAE 2.49.1 (2018-04-18T10:34Z)

or newer.
