### ISSUE TITLE
Csgo won't launch

### ISSUE THREAD

**Issue by JacquesGarre** [advancedfx/advancedfx#47]
System.ApplicationException: Failed to launch program, error code: 5
   à AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

I unzipped the archive to a new folder called 'hlae'. I launch it with Tools/Developer/Custom Loader
and injected c:\Users\{username}\Desktop\hlae\AfxHookSource.dll as a DLL. the csgo.exe path is good in ProgramPath and CommandLine is '-steam -insecure +sv_lan 1 -window -console'

**Comment by dtugend** [comment]
Please make sure that no Anti-Cheat client is running when using HLAE!

Turn off:
- Challengeme.gg
- ESEA Client
- FaceIt AnitChet Client
- ...

Please report back, if your problem is solved or not.

**Comment by JacquesGarre** [comment]
Damn, why didn't i think of this?! 

Works like a charm now, thank you very much!

**Comment by dtugend** [comment]
Btw make sure to update your HLAE to 2.49.2, there was an CS:GO Update.

**Comment by JacquesGarre** [comment]
Yup, just downloaded the new version 2.49.2 just before opening the issue ;) thanks anyway

**Comment by Devalisk** [comment]
I have the same problem 

System.ApplicationException: Failed to launch program, error code: 740
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)

**Comment by JacquesGarre** [comment]
> Please make sure that no Anti-Cheat client is running when using HLAE!
> 
> Turn off:
> 
> * Challengeme.gg
> * ESEA Client
> * FaceIt AnitChet Client
> * ...
> 
> Please report back, if your problem is solved or not.

:D

**Comment by dtugend** [comment]
```
ERROR_ELEVATION_REQUIRED

    740 (0x2E4)

    The requested operation requires elevation.
```

Please make sure that you do **not** have set any of these to run as admin
- **Steam.exe**
- **csgo.exe**
- **HLAE.exe**

Rightclick the .exe files -> Properties -> Compatibility tab -> Make sure that nothing is checked there -> Change settings for all users button -> after that OK button.

----

**Please do not hijack closed issues of other people @Devalisk**

**Comment by Devalisk** [comment]
My apologies. But, I did have some of these checked admins and turned them off. Now on HLAE, when I click launch CSGO, my cursor gets a circle indicating it's loading, but nothing shows up. I'm thinking of restarting my PC.

**Comment by dtugend** [comment]
Yes, rebooting might help

**Comment by Devalisk** [comment]
Rebooted. but neither HLAE loads CSGO or the .exe file. Wondering what to do?

**Comment by dtugend** [comment]
1) Right click CS:GO in Steam Library (when online) -> Properties -> Local Files tab -> Verify Game Cache Button - let it verify and re-download required files
2) Right click CS:GO in Steam Library (when online) -> Properties -> Local Files tab -> Browse Local Files Button, note down the FULL path it gives when you click into the path bar in the explorer window opened, this is important because in the past some people ended up with two CS:GO installs.
3) Use the File ->Launch CS:GO dialogue instead of Custom Loader and use the path for csgo.exe from the last step, usually it is `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe`

Please report back if this solved your problem or not, or if you ran into any problems (if so please describe anything that might be helpful for solving it later).

**Comment by Devalisk** [comment]
Would you recommend reinstalling the game? Maybe the base game is fine, but when I use HLAE, it messes it up? That could be a possibility.

**Comment by dtugend** [comment]
HLAE should not alter the game, it's an access rights problem, not sure if reinstalling fixes it.
As said you could just set HLAE to run as admin, but I usually don't recommend that.

**Comment by Devalisk** [comment]
Just curious, why would you not recommend running HLAE as admin? Reinstalling currently as we speak.

**Comment by dtugend** [comment]
It's always good to not trust programs to do the right thing, otherwise it would be fine =D

**Comment by Devalisk** [comment]
Okay CSGO works by itself when I reinstalled it. It works now. I think my reshaders messed everything up. Any clue how to install reshaders properly?

**Comment by dtugend** [comment]
https://www.reddit.com/r/advancedfx/comments/96xxnr/better_hlae_reshade_in_2018_tutorial_by_alan/

**Comment by Devalisk** [comment]
Good video. However, when I press SHIFT + F2, my demo playback keeps popping up. The reshader box never pops up when I press SHIFT + F2. I was wondering how to solve that?

**Comment by Devalisk** [comment]
Found the answer. Had to press home on my keyboard.

**Comment by neon1999** [comment]
same problem plz help

none of them have the permission to run as adminstrator
and also no antivirus is running behind

![Untitled](https://user-images.githubusercontent.com/46276144/66066253-cff6e580-e566-11e9-8c6d-4e6a2748fa65.jpg)

**Comment by dtugend** [comment]
https://twitter.com/advancedfx_org/status/1179444963895054337
