### ISSUE TITLE
It wont open, error says that there's no solution

### ISSUE THREAD

**Issue by JacKyNdLuma** [advancedfx/advancedfx#49]
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 123
   en AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 123
   en AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```

> I need help to fix this as soon as possible

**Comment by dtugend** [comment]
```
ERROR_INVALID_NAME

    123 (0x7B)

    The filename, directory name, or volume label syntax is incorrect.
```

1) What's the path you set for csgo.exe? Check that it is a full path and correct (it's probably wrong).
2) Make sure that no Anit-Cheat tools like ESEA / ChalengeMe.gg / FaceIt client are running.
3) Make sure that you don't have neither Steam.exe nor csgo.exe nor HLAE.exe set to run as admin.

**Comment by JacKyNdLuma** [comment]
Thank you for the response, I'll try <3

**Comment by dtugend** [comment]
Closing this due to lacking feedback. If it's not resolved feel free to leave a comment at a later time.
