### ISSUE TITLE
Automatically limit deathnotices to POV player

### ISSUE THREAD

**Issue by nkoep** [advancedfx/advancedfx#50]
I mentioned this before in private but figured I should maybe post this here as well for reference.

With the recently added `mirv_traceentity`, we got the added advantage that finding the player ID (or xuid for that matter) now reduces to executing the above command once inside the POV of the player whose ID we're interested in. I still think it would be worthwhile to take this one step further by introducing something like `mirv_deathmsg block !pov *` or `mirv_deathmsg block !-1 *` to automatically use this information and apply it to deathnotices. What previously required

1. enabling `mirv_deathmsg debug 1`,
2. playing past the scene of interest,
3. checking the console for the correct player ID,
4. executing `mirv_deathmsg block !id *`

would now be as simple as executing a single command.

**Comment by dtugend** [comment]
Not sure if I will enhance it for console commands, maybe will be part of #52 and #53 .

**Comment by dtugend** [comment]
Will be solved in #PanoramaUI edition, closing.
