### ISSUE TITLE
HLAE 3 GUI draft

### ISSUE THREAD

**Issue by dtugend** [advancedfx/advancedfx#52]
We will need to do GUI mockups with drawings or whatever to figure out things:

I want this in first HLAE 3 GUI version (preferably in this order):

1. JOBS / CLIPS [mirv_jobqueue / mirv_clips](https://github.com/advancedfx/advancedfx/issues/52#issuecomment-1097237082), actually it will just be jobs that can be reordered / grouped or grouped by demo to minimize loading time
-- should be possilbe for clips to overlap / then we will need multiple demo passes to record them) (e.g. one records campath, antoher POV, etc, not to be confused with streams that are in sync.
2. mirv_streams will not be in first version, instead there will be "mirv_cmd" (commands you can issue).
3. TIME (mirv_time), time will be a function like a path, not sure if we will allow zero (paused) time (maybe) / negative time (would need snapshot feature we talked about, which might be impossible for now).
4. CAMPATHS (mirv_campath) + GUI for quick editing ( e.g. https://github.com/advancedfx/advancedfx/issues/333 )

We will have:
- Main GUI Winodw
- Ingame Overlay GUI
- Optional panel windows mabye later

Requirements:
- Must work with single screen in full-screen (having the overlay doing the game picuture-in-picture and having panels around is acceptable). 

Design principles:
- Use focus and context(s) to minimize input actions required?

## See also
- Dedicated notice area/module/bar #277
- Unbind leftarrow/rightarrow from nextplayer/prevplayer #318 
- Faster Campath Editing #333 
- how to rebind "mirv_input camera mod"? #412 
- https://github.com/advancedfx/advancedfx/issues/704
- https://www.reddit.com/r/GlobalOffensive/comments/s43xuw/redesign_of_the_developer_console_concept/
- Trackmania demo editor

## Designs

* [Design July 2020 by shadoweee (Google drive)](https://drive.google.com/drive/folders/12z-G0uNHlFlpJ8E8ulFb5hYhV9TizUZv?usp=sharing) @Shadoweee77
* [Old design by RusTCSMoViES](https://github.com/advancedfx/advancedfx/issues/52#issuecomment-403822953)

**Comment by dtugend** [comment]
Post from old forum, probably not very relevant anymore, but keeping it here for now:

**by RusTCSMoViES » 2014-12-24T23:02Z**
> I thought a lot about demo tool that I want to write. And I understood that if I write it and if it work, all moviemaking recording process will become too annoying. It will be all in "trying to fix demo file" and "trying to include some packets to file" and "trying to kill laggs in this demo" and "trying to include commands to demofile to automatize recording process"... Brrrr! I feel, how I don't want to work now!))
> 
> So, I want to make this stupid process more interesting ant interactive! I think, that HLAE must have an INTERFACE. No no no, not interface. I said INTERFACE!!! =)
> 
> I drew, how I see HLAE with INTERFACE. You can find it interesting.
> 
> So, here it is:
> [![img](http://i63.fastpic.ru/thumb/2014/1225/47/_49c7d98c80c93df81c73f2e33557b647.jpeg)](http://fastpic.ru/view/63/2014/1225/_49c7d98c80c93df81c73f2e33557b647.jpg.html)
> 
> It must have a timeline, eventEditor, packetEditor, fileBrowser and engineWindow. All process will be interactive like in a video editor.
> 
> I hope you like it.
> Sorry for bad english. I'm from Russia =)

**Comment by WilliamRagstad** [comment]
This would be truely awesome, but I think it should look more like the demoui GUI

**Comment by dtugend** [comment]
depends on #192

**Comment by dtugend** [comment]
* [Design July 2020 by shadoweee (Google drive)](https://drive.google.com/drive/folders/12z-G0uNHlFlpJ8E8ulFb5hYhV9TizUZv?usp=sharing) @Shadoweee77

**Comment by dtugend** [comment]
-maV. worte on Discord:

```
*******************
*****Job Queue*****
*******************

Mirv_jobqueue - How the job queue listing is tracked

mirv_jobqueue print (see jobs from global demo list)
mirv_jobqueue setindex <demoName> <spotInQueue>
mirv_jobqueue start - starts jobQueue with first demo in queue index
mirv_jobqueue stop - stops jobQueue at current spot unless current spot is processing a clip
mirv_jobqueue cancel - immediately halts jobQueue, cancelling clip in process
mirv_jobqueue save - saves clips and campaths (via auto-save) to jobQueue index

Mirv_clips - separation of FirstPerson clips + Campath on tick/time basis

mirv_clips print - outputs clips list similar to campath lists with start end times/ticks 
mirv_clips <clipIndexHere> addLocal - add clip at current time/tick
mirv_clips <clipIndexHere> add ##:##:## (time/tick here)
mirv_clips <clipIndexHere> addStop (time/tick here)
mirv_clips campath load <loadCampathsXMLHere>, - comma separated loading of campath files for current demo


HLAE Additions:

mirv_campath(s) autosave <0/1> - for autosaving campaths on demo close, meanwhile linking to jobqueue for that demo

mirv_streams save/load/auto-save - saving streams list as templates creating easier mirv_clip instances
```

**Comment by dtugend** [comment]
The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
