### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by In-line** [advancedfx/advancedfx#6]

**Comment by dtugend** [comment]
https://github.com/ripieces/advancedfx-prop/issues/13

**Comment by YaLTeR** [comment]
Perhaps [hl-capture](https://github.com/YaLTeR/hl-capture) would do? It lacks advanced functionality but it can capture videos very well.

**Comment by In-line** [comment]
I need HLAE for hitboxes visualization, but I already started to implement it in https://github.com/dreamstalker/rehlds .

**Comment by dtugend** [comment]
The code related to that should be under MIT by now, feel free to use it as you see fit.
I am already busy with supporting Windows and supporting Linux would put about twice the workload in case of update breakage on me, so I have to reject that at least as of now.

**Comment by dtugend** [comment]
It's a hard decision for me and I took quite some time to decide it.

I decided
- to not support Linux for HLAE 3 for now
- to try to make several code parts easily portable for later instead.
- try to make sure it will still run in Wine as good as possible

Sorry, I simply don't see I can pull it off properly alone in the time I can dedicate.

**Comment by maxpain** [comment]
Any updates? We render CS:GO clips in Docker/Kubernetes environment and I want to use HLAE there.

**Comment by dtugend** [comment]
You can run Steam + CS:GO + HLAE in Wine on Linux (if you install the required .NET with winetricks), but there's no native Linux port yet.
It's not decided yet if HLAE 3 will be Linux first, Windows first or Windows only or maybe even Linux onlym HLAE 3 development is currently stuck. HLAE 2 will not support Linux natively.
Sorry.

**Comment by maxpain** [comment]
@dtugend I managed to run CS:GO with HLAE in Wine in a container environment, but I have a problem with FFmpeg. As I understand correctly, HLAE spawns ffmpeg as a child process and passes the image stream to it. The problem is that ffmpeg also runs under Wine, which is a performance drawback. Is there a way to work around this?

**Comment by dtugend** [comment]
There is a WONTFIX Wine "bug" related to that: https://bugs.winehq.org/show_bug.cgi?id=18335 - so might be complicated to run a Linux command line FFMPEG from wine from HLAE successfully.

There's a repo that claims to fix this, but I don't know if it works and have doubts it actually fixes it:
https://github.com/ruv/wine-runio

However unless you wanted to use Hardware accelerated encoding in FFMPEG (which is limited to certain number of streams), there shouldn't be a relevant performance drawback to running FFMPEG on Wine - the bottle neck would probably be the piping via stdin / stdout in either way I guess.

**Comment by maxpain** [comment]
> However unless you wanted to use Hardware accelerated encoding in FFMPEG
Yes, I want to use NVENC.

For some reason, `ffmpeg` doesn't work under Wine. I Installed HLAE with bundled ffmpeg:

```
mirv_streams settings add ffmpeg n2p "-c:v hevc_nvenc -g 300 -preset medium -tune hq -rc constqp -qp 20 -pix_fmt yuv444p {QUOTE}{AFX_STREAM_PATH}.mp4{QUOTE}"
mirv_streams settings edit afxDefault settings n2p
host_framerate 60
mirv_streams add normal test
mirv_streams record start
```

<img width="785" alt="image" src="https://github.com/advancedfx/advancedfx/assets/5875582/1bca8540-a968-42e8-b72f-a6c8439a3e6a">

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
