### ISSUE TITLE
AGR CS 1.6

### ISSUE THREAD

**Issue by instincthns** [advancedfx/advancedfx#617]
When I import AGR in cs 1.6 It creates 1000+ models at one point and the import is done for 2-10 hours.
On 1 image it creates animations with 1 frame.
![creating_models_1frame_animation](https://user-images.githubusercontent.com/68025673/113613141-6f63cf80-9659-11eb-9ee8-5216e48d39e2.png)
In the 2nd image, the end of the render with a very long time
![end_import](https://user-images.githubusercontent.com/68025673/113613157-77237400-9659-11eb-9339-293b8984e828.png)
On the 3rd image, there are 1000+ corpses lying at one point
![bug](https://user-images.githubusercontent.com/68025673/113613160-7a1e6480-9659-11eb-90ec-0f9b2036a3b0.png)

**Comment by dtugend** [comment]
It is probably not able to merge them for some reason.
I will need the demo in question (+ demo time) if possible.

**Comment by instincthns** [comment]
@dtugend 
demos https://drive.google.com/file/d/1xUboDDXNZlzy_FS_fPxU07LMVKN4ocUt/view?usp=sharing
agr https://drive.google.com/file/d/1ApBEL_gTp4DtyN9FaANcsB9oNqAlY-qr/view?usp=sharing

**Comment by dtugend** [comment]
And which demo is it?

**Comment by dtugend** [comment]
(The AGR should not be recorded at more than 30 FPS (it's more than enough for AGR, but 60 is really enough), the file size hints that it's more.)

**Comment by dtugend** [comment]
Thanks.
I am working on a fix.

**Comment by instincthns** [comment]
if in cs 1.6 to record AGR 30 fps then there will be bugs like this
https://www.youtube.com/watch?v=y6FcylG_XFg

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.113.1
