### ISSUE TITLE
AGR CS 1.6 

### ISSUE THREAD

**Issue by instincthns** [advancedfx/advancedfx#618]
Hello again, the next bug is in the movement of models. For some reason they turn around when they run to the side.
video
https://www.youtube.com/watch?v=X9dPMKub7UQ

**Comment by instincthns** [comment]
maybe the problem is that in the game, when running to the side, the legs turn around, and in AGR, the hands turn around
https://www.youtube.com/watch?v=rvNSgEZSsBU

**Comment by dtugend** [comment]
- Which HLAE version are you using? Asking because weaponmodels are missing on the player, which should be there.

**Comment by dtugend** [comment]
(You probably just didn't extract them I guess.)
I guess I know what's causing the bug, will try to fix it tomorrow.
(it uses ent origin and angles, and doesn't make an intermediate transform between those and the root rotation matrix.)

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.113.2
