### ISSUE TITLE
Error 2000

### ISSUE THREAD

**Issue by ArtvlZ** [advancedfx/advancedfx#619]
(Please search existing **open and closed** issues first to verify this is a new bug report.)
It says that it failed to launch the injector, despite the fact that i have antivirus off and i extracted files and didn't just take them out of the zip archive.

**Comment by onepass1** [comment]
Does your "injector.exe" file still exists ? In my case, I can't use HLAE because Avast AV says that this exe is a Trojan. I sent them the file several time for analysis but Avast still always refuses it...

**Comment by dtugend** [comment]
@ArtvlZ Did the idea of onepass1 help?
