### ISSUE TITLE
AGR CS 1.6 sideways movement

### ISSUE THREAD

**Issue by instincthns** [advancedfx/advancedfx#621]
Again the movement in the side is not displayed like this
https://www.youtube.com/watch?v=V1WxEBwmxac

**Comment by dtugend** [comment]
is this from the same recording with the same FPS?
replaying with different FPS etc can cause discrepancis?
You could record with host_framerate 0.01 and mirv_recordmovie_start / mirv_recordmovie_stop to get matching footage, otherwise it might just mismatch due to FPS etc.

**Comment by instincthns** [comment]
I do not write mirv_movie_start, it does not affect anything (I have tried many ways, and they are all the same) 
when the model moves sideways, the legs turn in the game, and the hands turn in agr
u check video? 
https://www.youtube.com/watch?v=NMAckCeXDDI
demo
https://drive.google.com/file/d/1mtkqT-n5tursR8tHfLJHTYbK_6REVTKm/view?usp=sharing

**Comment by instincthns** [comment]
in the previous version(2.113.2), running sideways was normal

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.113.4
