### ISSUE TITLE
My AGR takes a very long time to import into blender, please help (agr cs 1.6)

### ISSUE THREAD

**Issue by denismvm** [advancedfx/advancedfx#654]
It takes a very long time to import AGR into a blender

- https://prnt.sc/13cs7es

[de_inferno_cine.zip](https://github.com/advancedfx/advancedfx/files/6533442/de_inferno_cine.zip)

**Comment by dtugend** [comment]
- **Which HLAE version are you using?**
- What was your host_framerate / FPS when recording?

**Comment by denismvm** [comment]
> * **Which HLAE version are you using?**
> * What was your host_framerate / FPS when recording?

sorry my mistake, I didn't update HLAE
