### ISSUE TITLE
Failed to load the launcher DLL:

### ISSUE THREAD

**Issue by groubik** [advancedfx/advancedfx#659]
(Please search existing **open and closed** issues first to verify this is a new bug report.)
 i dont no 
![Скриншот 29-05-2021 02_37_42](https://user-images.githubusercontent.com/84998718/120050835-dfbe1a00-c026-11eb-8205-b536de7511c8.jpg)

**Comment by Dechno1337** [comment]
1. How are you trying to launch the game?
2. Which HLAE version and did you use the .zip or setup?
