### ISSUE TITLE
[Panorama UI Version] mirv_deathmsg debug 1 Crash

### ISSUE THREAD

**Issue by Emancyphur** [advancedfx/advancedfx#66]
I've compared this on both of the most recent versions for Scaleform UI, as well as the Panorama Version. 

Inputting **"mirv_deathmsg debug 1"** into the console **crashes the game** when resuming the demo, **only for the Panorama Version.** I've tried different methods with this, such as inputting the command prior to opening the demo, as well as at different stages of rounds, all resulting in the game crashing.

**Comment by dtugend** [comment]
Hi, this happened with the CS:GO update 6/25/18 (1.36.3.9).

It should be fixed now in the latest #PanoramaUI release: https://github.com/advancedfx/advancedfx/releases/tag/v2.50.7-panoramaui

Thank you for reporting the problem.

**Comment by Emancyphur** [comment]
No problem. Thank you for creating this amazing program, it's helped the community tons, and has contributed to the development of CS:GO. You're very appreciated!
