### ISSUE TITLE
Hlae custom loader failed

### ISSUE THREAD

**Issue by hAcKeRbOi-Zexus** [advancedfx/advancedfx#675]
Hlae returned that "custom loader failed", is there any chance for a VAC ban?
It said in the custom loader that insecure was in the launch options.
Do i have worry about my acc? 

https://github.com/advancedfx/advancedfx/discussions/categories/q-a

**Comment by dtugend** [comment]
If the game is launched with `-insecure`, then you can not join VAC protected servers.
If you inject AfxHookSource.dll in Custom Loader it will refuse to run / continue without -insecure.
In both cases you are safe and no need to worry.

**Comment by hAcKeRbOi-Zexus** [comment]
thank you for answering
