### ISSUE TITLE
CSGO WONT OPEN

### ISSUE THREAD

**Issue by srihaasreddy87** [advancedfx/advancedfx#679]
![Screenshot (78)](https://user-images.githubusercontent.com/86337380/123138036-3ece4d80-d472-11eb-967c-68b539e6e0d7.png)
(Please search existing **open and closed** issues first to verify this is a new bug report.)

Someone please help me. I can't open Csgo with HLAE. It shows the following error. I have tried everything moving the game files, uninstalled and re-installed csgo but still can't get through this. Please help if someone knows what to do. The same error pops for both launch csgo and custom loader options

**Comment by dtugend** [comment]
1) What's the full contents of the csgo.exe file box? Does it end with `\csgo.exe` or not`?
2) What's the actual error message?
