### ISSUE TITLE
CS:GO Don`t starts using HLAE

### ISSUE THREAD

**Issue by NeverRIEght** [advancedfx/advancedfx#68]
Code of stop:
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 267
   в AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 267
   в AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
I`m update Steam client to the last version, turn off antivirus program, disconnect Steam from internet and check cache of CS:GO files. I don`t play in network resources, like ESEA. Help me, please! Custom loader don`t work too.

OTHER PROBLEM:

Yesterday I try to open CS:GO with HLAE and I saw this only, without stop code:

FATAL ERROR: Failed to connect Steam Client process!
Please make sure that you are running latest version of Steam Client.

But I have last version of CS:GO. And I haven`t problems with start CS:GO without HLAE. And I don`t have other versions of CS on my PC.
![issue](https://user-images.githubusercontent.com/40734767/42133916-8717fcea-7d3a-11e8-9a73-91bb686c877f.png)

**Comment by NeverRIEght** [comment]
In aditional, I don`t ever play with Panorama UI.

**Comment by NeverRIEght** [comment]
It`s standart edition

**Comment by dtugend** [comment]
```
ERROR_DIRECTORY

    267 (0x10B)

    The directory name is invalid.
```

1) Please make sure you selected csgo.exe correctly in the Launcher. Please use File -> Launch CS:GO and not Custom Loader, Custom Loader is easier to get wrong.

2) Some people happen to have multiple installs of CS:GO on their computer for various reasons, usually the correct install is here `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe` please try this one (you can check the path of your Install in Steam Library, right click CS:GO, Local Files tab, browse local files button (make sure to check full path in explorer and not only shortened version)).

3) Make sure that neither HLAE.exe nor csgo.exe nor Steam.exe are set to be run as admin! (Right Click in explorer -> Properties -> Compatibilty tab, there should be nothing checked).

**Comment by dtugend** [comment]
Closing because of lack of feedback. If issue is not solved feel free to leave a comment.

**Comment by neon1999** [comment]
hlae latest version not working 

showing LOADER FAILED
System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
![Untitled](https://user-images.githubusercontent.com/46276144/66066198-b3f34400-e566-11e9-98e0-79c8f0e8fccf.jpg)

**Comment by dtugend** [comment]
https://twitter.com/advancedfx_org/status/1179444963895054337

**Comment by JohnGrass69** [comment]
If You Run CS:GO With Run As Administrator You Need to turn off

**Comment by JohnGrass69** [comment]
It Fixed My Problem
