### ISSUE TITLE
mirv_listentities and mirv_cmd's bugs

### ISSUE THREAD

**Issue by DuKeM-CSGO** [advancedfx/advancedfx#680]
1. mirv_listentities
When `mirv_listentities` is submitted to the console, there's a _Usage_ description:
`mirv_listentites [isPlayer=1] [sort=distance]`
And that's not "mirv_listentites" but "mirv_listentities" hahhahahaha!
2. mirv_cmd addCurves time
I've used `mirv_cmd addCurves tick` to add some curves successfully.
But when mirv_time's mode is resumePaused, the game's tick will not resume like gametime, so I need to use `mirv_cmd addCurves time`
Unfortunately, both the _tick_ version and the _time_ version will add the curve based on tick. Only I write a xml and load it, there could be a curve based on time and be active when mirv_time's mode is resumePaused.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.117.1
