### ISSUE TITLE
Momentum Mod (Re)Support

### ISSUE THREAD

**Issue by Gocnak** [advancedfx/advancedfx#693]
Hello!

I reached out back last year about getting support into [Momentum Mod](https://momentum-mod.org) and dtugend helped me out directly, adding support to our 2013 version.

We've since then got access to the Source Engine license, specifically the CS:GO branch, and are now based on it. I was contacted by Devostated about making an issue here for fixing compatibility with the game.

1. The game and engine closest to Momentum is CS:GO, as we are directly based on the CS:GO branch now. This means we are exclusively 64 bit, and plan to have a DX11 renderer by 1.0.0.
2. There's this error when trying to hook:
```
AfxError #13: 
Title: AfxHook errorDescription: DLL can't be found.
```

3. 
> I need to know classNames or common prefix of
> 1) Weapons
> 2) Projectiles
> 3) Players
> 4) Viewmodels

1) `C_Weapon` or `mom_weapon_`
2) `C_MomExplosive`
3) `C_MomentumPlayer`
4) `C_MomentumViewModel`

Dtugend should have a key to the game but if there's other developers that may require one, you may contact me on Discord `(Gocnak#2453)` for one!

Thanks all, let me know if you need more information!

**Comment by dtugend** [comment]
CS:GO on Windows is 32 bit and while HLAE can inject into 64 bit, the AfxHookSource component is 32 bit only at the moment.

Side note: Also CS:GO is based on DirectX 9.0c.

**Comment by dtugend** [comment]
Currently not planned.
