### ISSUE TITLE
Enable x-ray whilst in pov demo

### ISSUE THREAD

**Issue by NoahRandall01** [advancedfx/advancedfx#697]
Hi there, 

I just downloaded HLAE and the pov demo's are great for watching pro players and really getting into their perspective. However, I also like to watch my own demos this way but I would like to be able to enable xray but it seems you can't. I have used r_drawothermodels 2 but the range on this isn't very far and it is quite glitchy on some surfaces. Is there a way I can have the pov demo on the go but also use spec_show_xray 1?

Just to clarify this is for csgo.

**Comment by Dechno1337** [comment]
POV demos have limited data on other players so it makes sense that x-ray functions are not working properly.

If you are turning a GOTV demo into POV (with mirv_pov) then maybe there is a possibility to add x-ray? Though I haven't actually checked how that command affects the x-ray effects.
