### ISSUE TITLE
error-afxhooksource

### ISSUE THREAD

**Issue by circassianghost** [advancedfx/advancedfx#7]
![1](https://user-images.githubusercontent.com/29989542/27978393-d9cc3f74-6377-11e7-882d-37eb105320c2.PNG)

**Comment by tadashilima** [comment]
Did u fix it?? i have the same problemmmm

**Comment by tadashilima** [comment]
Helpppp !!! [http://i.imgur.com/VS3nyk8.jpg](url)

**Comment by ilyz1121** [comment]
me too pls help

**Comment by GandhiEdits** [comment]
I think this is because of the recent update with csgo, including what is going on with the major. I am sure a new update will come out soon.

**Comment by circassianghost** [comment]
Let's wait a couple of days and see what will happen !


On Jul 8, 2017, at 5:35 AM, GandhiEdits <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this is because of the recent update with csgo, including what is going on with the major. I am sure a new update will come out soon.

**Comment by dtugend** [comment]
Please update to HLAE 2.34.4 or newer.

As said in the changelog, audio data for mirv_streams is currently not available, due to a mistake that Valve did in the startmovie related code (they removed the function for appending audio data to the .WAV file).
