### ISSUE TITLE
comandos que nao estao funcionando na nova versao do panorama

### ISSUE THREAD

**Issue by Kamiiiiii** [advancedfx/advancedfx#70]
mirv_deathmsg debug 1
mirv_deathmsg block !  *
mirv_deathmsg highlightid
mirv_deathmsg cfg noticelifetime
mirv_replace_name debug 1
mirv_replace_name

**Comment by dtugend** [comment]
## ScaleformUI HLAE version:

If you want the old ScalefromUI version (not PanoramaUI) check here:
https://github.com/advancedfx/advancedfx/releases/tag/v2.50.3.2 !!!

## PanoramaUI HLAE version:

Please read the changelog, the commands changed:

**AfxHookSource 1.40.6-panoramaui (2018-06-24T14:30Z)**

* Readded mirv_deathmsg, the interface changed, but it has all features it used to have (even more, i.e. every id can be userID or XUID of a player, also trace (userId) or xTrace (XUID) to use current POV, see mirv_deathmsg help id for more info).  
 Examples:
  1) `mirv_deathmsg fake attackerId=4 victimId=5 weapon=ak47 headshot=1` // will make a death notice for the player with userID 4 killing the player with userId 5 with an headshot from ak47, will only work if one death message has been shown already.
  2) `mirv_deathsmg localPlayer xTrace` // sets the current POV player as localPlayer by their XUID.
  3) `mirv_deathsmg lifeTime 100.5` // sets the next default death notice life time to 100.5 seconds, to clear notices jump back to i.e. round start.
  4) `mirv_deathsmg lifeTimeMod 1.0` // sets the next default death notice life time multiplier for local player time 1.
  5) `mirv_deathsmg lifeTimeMod defaul`t // Restores default life time multiplier.
  6) `mirv_deathmsg filter add attackerMatch=!xTrace victimMatch=!xTrace block=1 lastRule=1` // block all death messages except of the player by XUID in the current POV:

* Readded mirv_replace_name, the interface changed, but it has all features it used to have (even more, i.e. every id can be userID or XUID of a player, also trace (userId) or xTrace (XUID) to use current POV, see mirv_replace_name help id for more info).

**Comment by dtugend** [comment]
If you want the old ScalefromUI version (not PanoramaUI) check here:
https://github.com/advancedfx/advancedfx/releases/tag/v2.50.3.2 !!!

**Comment by dtugend** [comment]
Please ignore the post above and update to latest HLAE:
https://github.com/advancedfx/advancedfx/releases/latest
Also read changelog, since mirv_deathmsg and mirv_replace_name changed: https://github.com/advancedfx/advancedfx/releases/tag/v2.51.0
