### ISSUE TITLE
AGR for GoldSrcs

### ISSUE THREAD

**Issue by Devostated** [advancedfx/advancedfx#700]
Question:
mirv_agr only has start and end record. Is this as intended?

```
mirv_agr start <sFilePath> - Start recording to file <sFilePath>, you should set a low host_framerate before (i.e. 30) and give the ".agr" file extension.
mirv_agr stop - Stop recording.
```

Bug:
mirv_agr start recommends host_framerate 30, but GoldSrcs (tested in cs 1.6) doesn't really support that and the recordings will be at 100fps.

**Comment by dtugend** [comment]
The bug is only in the HLAE command description:
In GoldSrc host_framerate needs to be the actual framerate (meaning 1 / FPS) and can not be FPS too.
So e.g. to get 25 FPS you would set host_framerate 0.04

**Comment by dtugend** [comment]
> mirv_agr only has start and end record. Is this as intended?

Yes.
