### ISSUE TITLE
Some sounds in mirv_pov

### ISSUE THREAD

**Issue by Gray661** [advancedfx/advancedfx#701]
When I am watching POV demo using "mirv_pov" , I will hear some sound from enemy ,which cannot be heard in normal demo , for example, the sound of the enemy switching weapons ,and the sound of inspect butterfly knife from other player.
How i should do to mute these sound? Is it a bug？

**Comment by dtugend** [comment]
Hi. Can you provide an example demo file (preferably a recent one, since old demos might be bugged in this regard originally), the approximate demo time (round, tick or time in demui), and the mirv_pov value used, please?

**Comment by Gray661** [comment]
Thanks for reply!
Every demo I watched has the same sound issue.In one pov demo,I can hear the sound of switching weapons from teammate in every round freeze time ,while I cannot not hear the sound in nomal demo,l can also hear the sound from enemy.
The sounds will let me know that there are enemies behind the wall.
There is a example demo I wathched.
Rencetly Navi VS Faze 
ESL Pro League Season 14 (1st of September 2021)
https://www.hltv.org/matches/2350360/natus-vincere-vs-faze-esl-pro-league-season-14
GOTV DEMO
Map : natus-vincere-vs-faze-m1-inferno (INFERNO)
mirv_pov 14
round 5
tick:70800-72000,you can hear the sound of switching weapons from teammate
tick:82000 =82500 (0:47-0:43) you can hear the sound of switching weapons from enemy (In normal demo, the sound never be heard)

**Comment by dtugend** [comment]
When exactly do you set ` mirv_pov 14`? It !!! **needs to be set before _(re-)starting_  the demo** !!! (e.g. use playdemo \<demoName\>). Setting during a live demo is not supported and will lead to bugs.

The demo ticks you posted seem inaccurate, but I tried to guess the time.

I have issues reproducing the issue (on latest HLAE 2.120.0):
```
sv_cheats 1
mirv_cvar_unhide_all
snd_filter "glock"
snd_show_print 1
snd_show 1
```
For me correctly only stuff of the enemies like reloading / shooting the glock is audible, the draw is inaudible (and thus also displayed as grey on-screen correctly).
Additionally test if setting `demo_index 0`  (also be-fore (re-)loading the demo) makes any difference, for me it does not (set it back to 1 for better demo performance if it does not for you as well).

**Comment by Gray661** [comment]
The number 14 is obtained through mirv_listentities isPlayer=1, which represents Simple's id in the demo.
And I set mirv_pov 14 before restart the demo  (on latest HLAE 2.120.0)
Here are the clip I upload youtube：
https://youtu.be/2N2wu__f6TA

These issues always exists ,I dont know whether it's my own setting problem
Thanks!

**Comment by dtugend** [comment]
Thanks, I will try again to reproduce it.

**Comment by dtugend** [comment]
I was able to find some issues in the sound attribution in mirv_pov, however it's a bit different from what you observed for me, but maybe it's also a bit random:

```
sv_cheats 1; developer 1; snd_show 1; snd_show_print 0; snd_filter draw
```

The "draw" sounds I actually hear in mirv_pov 14 (simple) at 0:45-0:43:
![image](https://user-images.githubusercontent.com/3610128/132299331-88d7363c-833c-4228-8266-1207fea248c8.png)
Basicall you are hearing teammates switch weapons, not broky (look at ent number, it's same as in show voice_mute).

However a bit earlier (1.01) there seems to be indeed a bug, the sound of broky would play for simple technically (even though I can't hear it), mirv_pov 8 (broky):
![image](https://user-images.githubusercontent.com/3610128/132303974-b31ca553-273b-4366-9ff3-206987c1e456.png)

mrtv_pov 14 (simple):
![image](https://user-images.githubusercontent.com/3610128/132305617-e3b39bff-a455-4c7d-a37b-d2ceed077f24.png)

GOTV broky in-eye:
![image](https://user-images.githubusercontent.com/3610128/132306141-35619578-bbb0-4507-8a74-a2d65a83741a.png)

I will try to see if I can improve the situation somehow (at least fixing the bug I found) and also the teammate switching being so audible seems a bit over the board for POV.

**Comment by dtugend** [comment]
Please update to HLAE 2.120.1 or newer: https://github.com/advancedfx/advancedfx/releases/tag/v2.120.1

**Comment by Gray661** [comment]
Thanks a lot !
HLAE 2.120.1 solve the problem
The POV demo never hear the sounds of switching weapons
