### ISSUE TITLE
Older demos crash upon loading with PanoramaUI

### ISSUE THREAD

**Issue by vex-ms** [advancedfx/advancedfx#72]
I have the latest hlae_2_51.0 and need to view an old demo on the old inferno, specifically VP vs Hellraisers from way back in 2015. The loading screen for the map shows and when it gets to nearing completion my csgo no longer responds. Any help or suggestions would be fantastic, thank you very much:D

**Comment by dtugend** [comment]
Hi, I am afraid this is a problem with Valve's Panorama UI and would happen without HLAE too.
If you want to report the bug with them (consider also providing them with a demo), their email can be found here: http://blog.counter-strike.net/index.php/2018/06/20497/

So the only option I know of is to not use Panorama UI, but the old Scaleform UI, for that only remove `-panorama` from the launch options (assuming you have latest CS:GO update).

**Comment by dtugend** [comment]
Closing due to no feedback in 9+ days.
