### ISSUE TITLE
Failed to connect to the steam client.

### ISSUE THREAD

**Issue by spoooks** [advancedfx/advancedfx#73]
I verified CS:GO files, ended every task asscoiated with steam, reinstalled HLAE. Note, this is 2.51 and my steam client is fully updated ( no updates available ) . Any help would be appricated, thanks
![capture](https://user-images.githubusercontent.com/40952169/42419980-af32434e-82b6-11e8-871d-1201ea91fd8f.PNG)

**Comment by dtugend** [comment]
Steam needs to be running, is it running?
Also make sure that neither HLAE, nor CS:GO, nor Steam are running as Admin please.

**Comment by spoooks** [comment]
Yes, my steam is running and yet i still get this error. Im not sure what else i can do to solve this

**Comment by dtugend** [comment]
As said you need to make sure neither HLAE.exe nor csgo.exe nor Steam are running as Admin:

Right click the HLAE.exe / csgo.exe (in CS:GO folder) and Steam.exe ( in Steam folder + the Shortcurt) -> Properties -> Compatibility tab, make sure that nothing is selected there (especially NOT run as admin or similar), click Okay or restart the program(s) and or reboot

**Comment by dtugend** [comment]
See previous message of me and additionally make sure you are launching the correct CS:GO install, some people somehow have multiple installs, the install / csgo.exe to use should be in `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive` most of the time.

**Comment by dtugend** [comment]
Glad it is solved.
