### ISSUE TITLE
[Launch Bug?] HLAE not launching with Panorama UI unless in "Custom Command Line Options"

### ISSUE THREAD

**Issue by Emancyphur** [advancedfx/advancedfx#78]
HLAE will not launch with the new Panorama UI as of right now, **even if you have -panorama in the Steam CS:GO's Launch Options** (as I said in my tutorial too). It launches with the Scaleform UI version, although I have -panorama in the CS:GO Launch Options. I'd assume that the custom command line is for extra commands you'd like to have launched there, along with the one's from Steam.

I have other Launch Options I use when going to record a frag, and it seems to work properly through the Steam one, however with Panorama it doesn't seem to detect it properly.

I may just be gauging this incorrectly (with the explanation of the command line being "extra commands"), but just curious anyways, even if Panorama will be fully released later on.

**Comment by dtugend** [comment]
This is by design, the HLAE Launch Options are independent of the Steam Library Launch options.

Edit: meaning you should add -panorama in HLAE if you want it.
