### ISSUE TITLE
Provide download URL that always points to latest version

### ISSUE THREAD

**Issue by wluxion** [advancedfx/advancedfx#8]
We have update scripts that download and install HLAE on remote machines. It'd be nice if we could point them to a URL representing the latest version. E.g., something like: https://github.com/ripieces/advancedfx/releases/download/latest/hlae_latest.zip

Thank you!

**Comment by dtugend** [comment]
You can use the GitHub API to find the latest release and download URL:
https://api.github.com/repos/ripieces/advancedfx/releases/latest

An example is how CSGO Demos Manager does it, but I cannot guarantee it's 100% accurate:
https://github.com/akiver/CSGO-Demos-Manager/blob/master/Manager/Services/HlaeService.cs

**Comment by wluxion** [comment]
Thanks, that's workable.

If it helps anyone, here's a bit of Powershell script for that:
```
$hlaeLatest = Invoke-WebRequest https://github.com/ripieces/advancedfx/releases/latest -Headers @{"Accept"="application/json"}
$hlaeJson = $hlaeLatest.Content | ConvertFrom-Json
$hlaeVersion = $hlaeJson.tag_name
$hlaeFile = "hlae_" + $hlaeVersion.TrimStart("v") -replace "\.", "_"
$hlaeURL = "https://github.com/ripieces/advancedfx/releases/download/$hlaeVersion/$hlaeFile.zip"
Invoke-WebRequest $hlaeURL -OutFile 'C:\Users\[username]\Downloads\hlae.zip'
Expand-Archive 'C:\Users\[username]\Downloads\hlae.zip' -DestinationPath 'C:\Program Files (x86)\HLAE' -Force
```

**Comment by dtugend** [comment]
Thank you for sharing the code.

Not sure if you saw the link I edited in above:
https://api.github.com/repos/ripieces/advancedfx/releases/latest
Might be more reliable / contains more info (i.e. download URL), but I see you already solved it.

**Comment by dtugend** [comment]
@wluxion The repository URL changed to https://github.com/advancedfx/advancedfx 2 days ago, GitHub will try to redirect it, not sure how well it will work though.

**Comment by wluxion** [comment]
That was thoughtful of you, thank you.
