### ISSUE TITLE
Can't exec afx/updateWorkaround

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#80]
For whatever reason I can't actually exec afx/updateWorkaround. It just simply says: "couldn't exec afx/updateWorkaround".
Any idea what it is that I'm doing wrong?

**Comment by dtugend** [comment]
Please see issue #65 for a workaround.

**Comment by ghost** [comment]
I was an idiot and somehow didn't actually have the "resources" folder in my HLAE folder...

Thanks anyways though.
