### ISSUE TITLE
mirv_listentities isPlayer=1 - Returns nothing

### ISSUE THREAD

**Issue by ghost** [advancedfx/advancedfx#81]
Hello,

Would like to know if I could solve the following issue. When I write `mirv_listentities isPlayer=1` in the console, I should get all the playerdata from everyone. Unfortunately the online thing it returns is:

```
Results:
index (distance): className::enitityName :entityHandle
```

Could someone help me? Thanks.

**Comment by dtugend** [comment]
1) Make sure that you loaded a demo and it's playing or paused with players inside.
2) Make sure you CS:GO is fully updated and in a consistent state: Right click CS:GO -> Properties -> Local Files tab -> Verify Game Cache button, let it verify and re-download required files.
3) Make sure you are using correct CS:GO path in HLAE for csgo.exe, compare it with the one in Steam library: Right click CS:GO -> Properties -> Local Files tab -> Brows Local Files button

**Comment by ghost** [comment]
I know that my console was getting spammed cause this `con_filter_enable` command. And I set that to `0` and I also verified the game cache. Somehow it's working now :)

Solved.
