### ISSUE TITLE
HLAE Csgo recording glitch

### ISSUE THREAD

**Issue by jameel-ansari** [advancedfx/advancedfx#83]
![screenshot 2](https://user-images.githubusercontent.com/41630454/43137773-a8204034-8f44-11e8-9dff-1d3bfae8574b.png)

![screenshot 5](https://user-images.githubusercontent.com/41630454/43138039-9caba756-8f45-11e8-863e-2f4d92f2ea38.png)

So I have been recording clips for a long time and I record my guns layer and models layer separately but each time I import my tga files into Adobe AE, you can either see the guns overlap the models or the models overlap the guns (including pov). In the 2nd screenshot you can see the model is overlapping the gun pov and this gets worse as the clip plays on. Is there any way like a command or another way when recording/editing to stop this from happening? Thanks.

**Comment by dtugend** [comment]
You need to re-visit your stream settings.
For example you probably want the playerModelsAction set to mask instead of noDraw on the "guns" stream and things like that.

**Comment by jameel-ansari** [comment]
Ah finally, I can't thank you enough! I've been trying to find a solution for so long and thanks to you it is fixed! :D

**Comment by dtugend** [comment]
Thanks for reporting back, if you have further related questions, please comment. Please note we also have a chat (Discord) and a forum (Reddit) linked on the support page on advancedfx.org - which might be more appropriate for support questions.
