### ISSUE TITLE
Error - AfxHookSource

### ISSUE THREAD

**Issue by KNOWPEIN** [advancedfx/advancedfx#84]
Started using HLAE in new PC it gives following error
![image](https://user-images.githubusercontent.com/16850243/43199923-33b71478-9031-11e8-8c60-9f6f4d2f67d3.png)

**Comment by KNOWPEIN** [comment]
Game : CSGO

**Comment by gnsx** [comment]
Can confirm
![github error](https://user-images.githubusercontent.com/3590121/43221046-441f078e-9069-11e8-9083-f11a38207d71.PNG)
