### ISSUE TITLE
Problem with afx/updateWorkaround

### ISSUE THREAD

**Issue by seiqin** [advancedfx/advancedfx#85]
Hello, i can't exec afx/updateWorkaround. When I write this command, I write back that "exec: could not exec afx / updateWorkaround". Can u help me with this problem? I use lastest version of hlae.

**Comment by seiqin** [comment]
These problems began after the update of Panorama UI came out, before that everything worked. 

I tried to move the program to drive C and got this error on startup. Unfortunately, nothing has helped to solve this problem.

```
AfxError #12: 
Title: AfxHook error
```
Screen
![screenshot_499](https://user-images.githubusercontent.com/41740838/43320033-b935d5f6-91af-11e8-8af2-f2ba3e99c623.png)

**Comment by dtugend** [comment]
1) Make sure you are using the latest HLAE and extract all files and folders.
2) In which folder did you put HLAE.exe and the files and folders from the zip?
3) Please provide a screen shot of your File -> Launch CS:GO settings (you should not use custom loader unless required, it's too easy to make mistakes there).

**Comment by dtugend** [comment]
Closing due to lacking feedback.
If it's not solved, please comment.

**Comment by seiqin** [comment]
With the new update, it all went well.
