### ISSUE TITLE
How remove Highlighted player from CS:GO's Tournament Demo?

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#88]
Hi!
I want make a edit on CS:GO with bigest pro-player plays.
So, I take Demos from CS:GO's Tournaments, where players and projectiles are Highlighted like this:

![csgofuk](https://user-images.githubusercontent.com/42187538/43799049-aaf20272-9a8c-11e8-9136-12386f02395a.PNG)

Do you know how remove this ugly Highlight?
Any CS:GO command?
Thank you for helping me.

**Comment by dtugend** [comment]
Enter this in console during the demo
```
mirv_cvar_unhide_all
spec_autodirector 0
spec_autodirector_cameraman 0
spec_cameraman_ui 0
spec_cameraman_xray 0
spec_show_xray 0
```

**Comment by qriosserra** [comment]
Thank you! I just need the "spec_show_xray 0" command actually. :D
