### ISSUE TITLE
Hlae issues

### ISSUE THREAD

**Issue by LilRacc** [advancedfx/advancedfx#89]
I have been using hlae for a while now and everything works so far but I have some problems that really frustrate me, the following commands don't work at all for me. mirv_deathmsg block !# * and mirv_deathmsg highlightid !#, nothing happens when I write in those commands and I'm stuck with my frag movie making and don't know what to do, have been looking around for solutions but haven't found any good help so I decided to ask here on the forums instead. Would really appreciate some help :D 
![help](https://user-images.githubusercontent.com/42251432/43921109-1d7eac52-9c1b-11e8-9a7c-991e2abe73db.jpg)

**Comment by dtugend** [comment]
See https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_deathmsg#this-page-needs-to-be-updated

**Comment by LilRacc** [comment]
@dtugend So i just copy paste that into the console??? and then press h????

**Comment by LilRacc** [comment]
@dtugend Thank you very much, it helped a lot, glad you could help.
