### ISSUE TITLE
How remove/hide others players & weapons models. But not our weapons from POV

### ISSUE THREAD

**Issue by qriosserra** [advancedfx/advancedfx#90]
Hi!
I want make a edit on CS:GO, but I need one more help.
It is possible with HLAE to hide others players & weapons models?
But not our weapons from POV. (for myMatte layer)

To have a view like that :
![00316](https://user-images.githubusercontent.com/42187538/43987023-c6388bb0-9d1a-11e8-8696-fbf969cdfac2.png)

But of course, when the player shot a ennemy. He see him... :
![00465](https://user-images.githubusercontent.com/42187538/43987040-fc1ef890-9d1a-11e8-8628-175f949cf52e.png

I search some CS:GO command for this... but I find nothing
Thank you for your attention and help :D

**Comment by dtugend** [comment]
This is actually a weakness of the current way mirv_streams is implemented.

If you don't need the map fog (most official maps don't have fog), you can use the fogui to work around that problem, add these to your config.

Add this to your config **if you don't need stickery anyway**:

```
// This settings need to be one after the demo is loaded, since some can change with demo:
fog_enable 0
fog_color "0 255 0"
fog_start 1
fog_end 1
fog_override 1
fog_hdrcolorscale 1
fog_maxdensity 1
mirv_streams edit myMatte attachCommands "fog_enable 1"
mirv_streams edit myMatte detachCommands "fog_enable 0"
mirv_streams edit myMatte stickerAction noDraw
```

**If you need stickers**, then the only option is to make another stream in order to mask the viewmodel with it, **then use this instead**:

```
// This settings need to be one after the demo is loaded, since some can change with demo:
fog_enable 0
fog_color "0 255 0"
fog_start 1
fog_end 1
fog_override 1
fog_hdrcolorscale 1
fog_maxdensity 1
mirv_streams add matteEntity vmMask
mirv_streams edit vmMask attachCommands "fog_enable 1"
mirv_streams edit vmMask detachCommands "fog_enable 0"
mirv_streams edit vmMask stickerAction noDraw
```

**Comment by qriosserra** [comment]
Thank you so much. Really helpful ! :D

**Comment by qriosserra** [comment]
Yeah, I test your config and it doesn't work first time.
I wanted retry to be sure, but thank you for correct before.
