### ISSUE TITLE
The new command system is weird

### ISSUE THREAD

**Issue by imjohne** [advancedfx/advancedfx#91]
Tbh! why even change it when it was already very good and not that hard to understand now it's hard and I don't understand it. Some commands are also pretty buggy like the mirv_deathmsg localplayer cause it removes the id you put in...

**Comment by dtugend** [comment]
We are not planing to change it back again.

Please have a look at the first Twitter **thread** linked on this page, it has multiple examples.
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_deathmsg#this-page-needs-to-be-updated

You might also find the script bellow there useful too.

**Comment by dtugend** [comment]
If you have Twitter and want, you can vote here:
https://twitter.com/dtugend/status/1030348546887901184
