### ISSUE TITLE
HLAE crashes whenever I use the custom loader (Source2)

### ISSUE THREAD

**Issue by wolfycs** [advancedfx/advancedfx#914]
Background info: AfxHookSource2.dll is inside HLAE installation folder. My custom loader commands are "-insecure -sv_lan 1". HLAE is in latest version 2.154.3.0 (27 February)

Whenever I try to load in HLAE the game shows up, the Valve logo appears, and then the game shuts down immediately. Couldnt find a fix, bug started since I updated to latest version.

**Comment by Dechno1337** [comment]
> Background info: AfxHookSource2.dll is inside HLAE installation folder.

The base folder or the x64 sub-folder? It needs to be in the x64 folder.

**Comment by dtugend** [comment]
We've had reports of crashes that were related to FaceIT anti-cheat game overlay and or browser running in the background.
The user said that FaceIT anti-cheat was disabled, but we could still see `C:\Users\username\AppData\Local\FACEIT\app-1.33.0\resources\app\modules\overlay\n_overlay.x64.dll` being injected into CS2 and conflicting with HLAE.
Can you check if it's related to that, please?

**Comment by dtugend** [comment]
Note: Closing the FaceIT GUI is not enough, you must "disable driver":

> In our latest versions of the FACEIT Anti-cheat, you are given more control over the driver operation. In particular, you can go to the Anti-cheat tray icon and choose “disable driver”. This will allow you to unload our driver without uninstalling the Anti-cheat. Please keep in mind that if you do disable the driver, you will be asked to restart your PC before being able to play any of the games we protect.

Source: https://support.faceit.com/hc/en-us/articles/9394666828188-What-is-FACEIT-Anti-cheat-and-how-does-it-work

**Comment by wolfycs** [comment]
> > Background info: AfxHookSource2.dll is inside HLAE installation folder.
> 
> The base folder or the x64 sub-folder? It needs to be in the x64 folder.

Hi, thank you for your reply. Here is a screenshot from my file browser showing the exact directory & folder that has AfkHookSource2.dll

![afxhook](https://github.com/advancedfx/advancedfx/assets/161418886/24facf10-6878-445f-9b6a-5320e90cf184)

I believe it is in the right folder, I will try dtugend's solution and send another message if it fixes the problem

**Comment by wolfycs** [comment]
> We've had reports of crashes that were related to FaceIT anti-cheat game overlay and or browser running in the background. The user said that FaceIT anti-cheat was disabled, but we could still see `C:\Users\username\AppData\Local\FACEIT\app-1.33.0\resources\app\modules\overlay\n_overlay.x64.dll` being injected into CS2 and conflicting with HLAE. Can you check if it's related to that, please?

> Note: Closing the FaceIT GUI is not enough, you must "disable driver":

In our latest versions of the FACEIT Anti-cheat, you are given more control over the driver operation. In particular, you can go to the Anti-cheat tray icon and choose “disable driver”. This will allow you to unload our driver without uninstalling the Anti-cheat. Please keep in mind that if you do disable the driver, you will be asked to restart your PC before being able to play any of the games we protect.

Source: https://support.faceit.com/hc/en-us/articles/9394666828188-What-is-FACEIT-Anti-cheat-and-how-does-it-work

-

Hi dtugend, 

Thank you for your reply. See attachment for file browser search results. Couldn't find anything that matches "n_overlay.x64.dll". Also cannot find a button to disable driver when I click the "ANTI-CHEAT" tray on my FACEIT app. Currently uninstalling another anti cheat that I had on my PC for CS 1.6, unlikely that it is the cause but I'll see if it works or not. I'll keep you updated.

![Screenshot 2024-02-27 143415](https://github.com/advancedfx/advancedfx/assets/161418886/8ec1e89a-d001-4355-ba1e-4c9bbb0607af)

**Comment by dtugend** [comment]
Hm. The n_overlay.x64.dll is installed in the User accounts Local AppData folder by FACEIT, not sure if you searched there.
Not sure if Closing the App from tray icon does same in the version you have.

**Comment by wolfycs** [comment]
> Hm. The n_overlay.x64.dll is installed in the User accounts Local AppData folder by FACEIT, not sure if you searched there. Not sure if Closing the App from tray icon does same in the version you have.

I updated my FACEIT AC and then disabled it through the tray on the windows bar, now I can use HLAE properly. Game loads and everything works properly. Therefore, I'll be closing the thread, thank you very much dtugend and Dechno1337 for your help! 

To anyone else here who is having the same issue, make sure you deactivate kernel anti-cheat programs like FACEIT AC before you run HLAE.
