### ISSUE TITLE
CS:GO Don`t starts using HLAE

### ISSUE THREAD

**Issue by DuSTeR2001** [advancedfx/advancedfx#95]
HLAE is not working ive tried everything , nothing works , pls help me ! It gives me erros everytime . Even when its newest version . Exact same thing everytime and i dont know how to fix it , so i beg u if u know how to fix it ,pls reply !
![error](https://user-images.githubusercontent.com/42980760/45054130-bdc12400-b094-11e8-9168-35b8b84a0b1e.png)

**Comment by dtugend** [comment]
Please make sure that no Anti-Cheat client like ESEA client / FaceIt client / ChallengeMe.gg is running before using HLAE.

**Comment by DuSTeR2001** [comment]
![same thing](https://user-images.githubusercontent.com/42980760/45055181-c1a27580-b097-11e8-87e9-f96f019b314a.png)
i stopped it and yet nothing happens , look :/

**Comment by dtugend** [comment]
```
ERROR_INVALID_NAME

    123 (0x7B)

    The filename, directory name, or volume label syntax is incorrect.
```

1) What's the path you set for csgo.exe? Check that it is a full path and correct (it's probably wrong).
2) Make sure that no Anit-Cheat tools like ESEA / ChalengeMe.gg / FaceIt client are running.
3) Make sure that you don't have neither Steam.exe nor csgo.exe nor HLAE.exe set to run as admin.

**Comment by DuSTeR2001** [comment]
Ths for everything ! You helped me a lot and i appreciate it !

**Comment by dtugend** [comment]
👍
