### ISSUE TITLE
Add mirv_cmd edit start

### ISSUE THREAD

**Issue by FlowingSPDG** [advancedfx/advancedfx#97]
Hello. Im, using HLAE for my tournament broadcasting.

I'm using `mirv_campath edit start` to load/enable campath.
but there's not `mirv_cmd edit` start for mirv_cmd. I really want it.

I want to use it becasuse there is no `wait` command for CS:GO.

Sorry for Bad Engish.
Thanks.

**Comment by nnnet** [comment]
@FlowingSPDG Hi!
Could you give an example of how this is done?
The commands to run HLAE, cfg-files and XML-files?

**Comment by FlowingSPDG** [comment]
@nnnet Hi.Thanks for reply :)
mirv_cmd is HLAE's command for executing multiple commands in specific time.

`mirv_cmd` can execute CS:GO commands in specific time.
`mirv_campath` can load camera animation in specific time.
`mirv_campath edit start` means load camera campath for current time.

Examples
type `mirv_cmd add echo 30SEC LEFT!` when demo is at 0:30,and return demo to 1:00.
So,Your console will reply "30SEC LEFT!" at 0:30.
which means you don't need to type command when you are playing demo,and also command will be executed more accurate time.

`mirv_cmd save CMDFILE` to save your commands and times to XML file.

**Comment by FlowingSPDG** [comment]
@nnnet 
No. First,I play demo and `mirv_cmd add echo 123` and `mirv_cmd save CMDFILE` to save CMDFILE.
And edit that CMDFILE by notepad. and finally I'll execute `mirv_cmd load CMDFILE`.
But this is only for demo file. I can't use this for live insecure live server.

Maybe I have some misunderstanding because my English skill is not good :( sorry about it.

**Comment by dtugend** [comment]
@FlowingSPDG Thank you for your suggestion. I will try to add it in one of the next releases, but can't promise anything, because very busy with non-HLAE stuff at the moment.

Until it's done you could use a trick using a "normal" stream and it's attach command which is executed exactly once per rendering of the stream.

**Comment by FlowingSPDG** [comment]
@dtugend Thanks a lot!
Thanks for advice,but I guess it's not effective for me.

Im planning to use `mirv_campath`and`spec_goto`insted of `spec_lerpto` like [PGL](https://youtu.be/wCwbmUFy-fI?t=3m32s).
STEP1. `spec_goto (start pos)` // move to start position and wait
STEP2. `mirv_campath edit start` // execute campath
STEP3. `spec_goto (end pos)` // move camera to final destination for HLAE&CSGO camera.

So,I need to exec STEP3 after(or sametime with) STEP2.

If I can do it, it would be awesome.
here is a sample.
[mirv.zip](https://github.com/advancedfx/advancedfx/files/2355560/mirv.zip)

**Comment by dtugend** [comment]
You can use an external tool like https://autohotkey.com until it is done.

The camera override + spec pos being different is a problem that I might need to address separately, since it has an impact on some visibility checks.
