### ISSUE TITLE
How to use afx_interop with UnityAR

### ISSUE THREAD

**Issue by FlowingSPDG** [advancedfx/advancedfx#98]
Hi. I'm using Unity AR project for my tournament.
So, I found [afx-unity-interop](https://github.com/advancedfx/afx-unity-interop/blob/master/Assets/AdvancedfxInterop.cs) and `afx_interop` function from HLAE's Sourcecode.
I've succeed to build AfxHookUnity.dll and link to Unity.
but How can I connect this?
I tried those two commands but still not working.
`afx_interop pipeName advancedfxInterop`
`afx_interop connect 1` 

console says 
`Could not open pipe. GLE=2
AfxInterop::Connect: Error in line 194.`.

Please help me.
Thanks

**Comment by dtugend** [comment]
This feature is still in development and not operational. Sorry.
https://github.com/advancedfx/advancedfx/issues/55

Will probably not be continued before these are solved: https://github.com/advancedfx/advancedfx/projects/2

**Comment by dtugend** [comment]
Additional Hint: The old AR features are still available of course, i.e.
the `mirv_pgl draw` command, for which this sample project is: https://github.com/advancedfx/advancedfx/tree/master/misc/MirvPglDrawTest

**Comment by dtugend** [comment]
This Project is for decoding the `mirv_pgl draw` color code in a fixed position on pixel input.

The program it self works if you drag and drop an image (PNG / TGA / BMP) onto the executable, then it should decode the code, but only if the settings in Program.cs are correct (they are for default mirv_pgl_draw codes).
Might be good idea to not use default settings and lower the Bits Per Pixel from 6 to 1, to be more stable against encoding errors etc (needs to be set both in the mirv_pgl draw sub-commands and the decoder.)

The main purpose of this project is to give an example decoder for the pixels.

**Comment by FlowingSPDG** [comment]
@dtugend Thanks! Now I could decode example images.
So, How can I save `mirv_pgl draw`'s image?
Also,looks like `mirv_pgl draw start`does nothing on my screen.

**Comment by dtugend** [comment]
mirv_pgl draw start draws the color code near the top of the (old) radar area, it's not very big in default settings (9 blocks in a row of 4x4 pixels).
It can't be captured with mirv_streams record, because it is drawn later as last thing before the image is swapped onto the screen.

**Comment by FlowingSPDG** [comment]
@dtugend Thx!
I tried startmovie tga record,but I still couldn't find these pixels. and maybe MirvPglDrawTest.exe returned wrong code.

`T=0, X=-9472, Y=-16384, Z=-16384, XR=75.99792, YR=-171.8646, ZR=-128.573, FOV=51.427`

executed commands
`cl_draw_only_deathnotices 1`
`mirv_pgl draw red 1 0.062745 0.921569`
`mirv_pgl draw green 1 0.062745 0.921569`
`mirv_pgl draw blue 1 0.062745 0.921569`
`mirv_pgl draw start`
`startmovie mirvpgldrawtest jpg jpeg_qality 95`

MirvPglDrawTest.exe's color bit is (probably) 1bit.

**Comment by dtugend** [comment]
- I am not sure if startmovie can catch them either. It is meant for live screen captures. Print screen will work.
- The code can and will be broken if vsync is off.
- You should not change the color bit depth settings unless you change them in decoder too.

**Comment by FlowingSPDG** [comment]
@dtugend tried PrintScreen and V-Sync off,default bit depth,but the output is still broken.
I guess my settings are not good...
Thanks for help,I will look for another way.

**Comment by dtugend** [comment]
it won't detect the position of the code by itself, you need to crop it after print-screen to the original res

**Comment by dtugend** [comment]
Hi, apparently you really meant the code is not there at all.
It's indeed a bug, see #99

**Comment by FlowingSPDG** [comment]
okay,Goodluck in coding :) thanks!

**Comment by FlowingSPDG** [comment]
@dtugend 
It worked properly! Thanks a lot :)

**Comment by dtugend** [comment]
I doubt it's that useful (I mean you can do some stuff with it when you use multi streams preivew), but it's not something I'd recommend too much. The Unity AR will be more interesting when hopefully finishes something.

Don't forget that vsync off will break the code.
